"""Berlekamp-Massey algorithm plugin for Algorithm Atlas."""
from __future__ import annotations

from typing import Generator, List

from algorithm_atlas_sdk import (
    AlgorithmMetadata,
    AlgorithmPlugin,
    DPState,
    SimulationParams,
)

# m-sequence of period 7 generated by x^3+x+1 starting from [1,1,0]
_SEQ = [1, 1, 0, 1, 0, 0, 1]


class BerlekampMasseySimulation(AlgorithmPlugin):
    def metadata(self) -> AlgorithmMetadata:
        return AlgorithmMetadata(
            slug="berlekamp-massey",
            name="Berlekamp-Massey Algorithm",
            category="number-theory",
            visualization_type="MATRIX",
            description="Find the shortest LFSR (linear-feedback shift register) that generates a given binary sequence.",
            intuition=(
                "Maintain connection polynomial C(x) and its length L. "
                "For each new term, compute the discrepancy d. "
                "If d≠0, update C(x) using a shifted copy of the previous polynomial. "
                "Double the register length only when needed."
            ),
            complexity_time_best="O(n²)",
            complexity_time_average="O(n²)",
            complexity_time_worst="O(n²)",
            complexity_space="O(n)",
            tags=("number-theory", "berlekamp-massey", "lfsr", "sequence", "coding-theory"),
        )

    def initialize(self, params: SimulationParams) -> DPState:
        n = len(_SEQ)
        return DPState(
            table=(
                tuple(_SEQ),
                tuple([1] + [0] * (n - 1)),   # C polynomial (padded)
            ),
            current_cell=None,
            computed_cells=frozenset(),
            description=f"sequence={_SEQ}  Initial C=[1]  L=0",
        )

    def steps(self, initial_state: DPState) -> Generator[DPState, None, DPState]:
        s = list(_SEQ)
        N = len(s)
        C: List[int] = [1]   # connection polynomial (GF(2))
        B: List[int] = [1]   # previous C
        L = 0
        m = 1   # shift counter
        computed: set = set()

        def poly_str(p):
            terms = []
            for i, c in enumerate(p):
                if c:
                    terms.append(f"x^{i}" if i > 0 else "1")
            return "+".join(terms) if terms else "0"

        def pad(p, length):
            return list(p) + [0] * max(0, length - len(p))

        for n_idx in range(N):
            # Discrepancy
            d = s[n_idx]
            for j in range(1, L + 1):
                d ^= C[j] * s[n_idx - j]
            d &= 1
            computed.add((0, n_idx))
            if d == 0:
                m += 1
                yield DPState(
                    table=(tuple(s), tuple(pad(C, N))),
                    current_cell=(0, n_idx),
                    computed_cells=frozenset(computed),
                    description=(
                        f"n={n_idx} s={s[n_idx]} d=0 (no update) "
                        f"C={poly_str(C)} L={L}"
                    ),
                )
            else:
                T = C[:]
                # C = C XOR x^m * B  (in GF(2))
                new_len = max(len(C), len(B) + m)
                C_new = [0] * new_len
                for i_c, ci in enumerate(C):
                    C_new[i_c] ^= ci
                for i_b, bi in enumerate(B):
                    if i_b + m < new_len:
                        C_new[i_b + m] ^= bi
                # Trim trailing zeros (except C[0])
                while len(C_new) > 1 and C_new[-1] == 0:
                    C_new.pop()
                if 2 * L <= n_idx:
                    L = n_idx + 1 - L
                    B = T
                    m = 1
                else:
                    m += 1
                C = C_new
                computed.add((1, n_idx))
                yield DPState(
                    table=(tuple(s), tuple(pad(C, N))),
                    current_cell=(1, n_idx),
                    computed_cells=frozenset(computed),
                    description=(
                        f"n={n_idx} s={s[n_idx]} d={d} → update "
                        f"C={poly_str(C)} L={L}"
                    ),
                )

        final = DPState(
            table=(tuple(s), tuple(pad(C, N))),
            current_cell=None,
            computed_cells=frozenset(computed),
            description=f"LFSR length={L}  C(x)={poly_str(C)}",
        )
        yield final
        return final
