"""Program Mode expansion, batch 10: string-family problems (valid-
parentheses, valid-palindrome-string, valid-anagram, edit-distance,
longest-common-subsequence, longest-common-substring,
minimum-window-substring-length, longest-substring-without-repeating,
longest-repeating-char-replacement, longest-substring-at-most-k-distinct,
regular-expression-matching, wildcard-matching, restore-ip-addresses-count)
through the all-15-language shape harness.

distinct-subsequences and kmp-string-matching were deliberately EXCLUDED:
distinct-subsequences' expected values reach ~1.9e10, overflowing the
32-bit `int`/`i32` that rt() hard-maps java/cpp/csharp/c/rust's "int" kind
to (same class of gap as reverse-bits, not yet worth a schema change);
kmp-string-matching returns an ARRAY of match positions, a shape the
harness doesn't support yet (int/bool kinds only).
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import logging
logging.disable(logging.CRITICAL)

import atlascode_shapes_all15 as sh

add = sh.add

# ═════════════════════════════════════════════════════════════════════════
# is_valid(s) -> bool, matching brackets via stack
# ═════════════════════════════════════════════════════════════════════════
add("valid-parentheses", "str1", "is_valid", "bool", {
    "go": "stack := []byte{}\nresult := true\nfor i := 0; i < len(s); i++ {\n\tc := s[i]\n\tif c == '(' || c == '[' || c == '{' {\n\t\tstack = append(stack, c)\n\t} else {\n\t\tif len(stack) == 0 { result = false; break }\n\t\ttop := stack[len(stack)-1]\n\t\tstack = stack[:len(stack)-1]\n\t\tif (c == ')' && top != '(') || (c == ']' && top != '[') || (c == '}' && top != '{') { result = false; break }\n\t}\n}\nif len(stack) != 0 { result = false }",
    "ruby": "stack = []\nresult = true\ns.each_char do |c|\n  if ['(', '[', '{'].include?(c)\n    stack.push(c)\n  else\n    if stack.empty?\n      result = false\n      break\n    end\n    top = stack.pop\n    if (c == ')' && top != '(') || (c == ']' && top != '[') || (c == '}' && top != '{')\n      result = false\n      break\n    end\n  end\nend\nresult = false if result && !stack.empty?",
    "kotlin": "val stack = ArrayDeque<Char>()\nvar result = true\nfor (c in s) {\n    if (c == '(' || c == '[' || c == '{') {\n        stack.addLast(c)\n    } else {\n        if (stack.isEmpty()) { result = false; break }\n        val top = stack.removeLast()\n        if ((c == ')' && top != '(') || (c == ']' && top != '[') || (c == '}' && top != '{')) { result = false; break }\n    }\n}\nif (stack.isNotEmpty()) result = false",
    "php": "$stack = [];\n$result = true;\nfor ($i = 0; $i < strlen($s); $i++) {\n    $c = $s[$i];\n    if ($c == '(' || $c == '[' || $c == '{') { $stack[] = $c; }\n    else {\n        if (empty($stack)) { $result = false; break; }\n        $top = array_pop($stack);\n        if (($c == ')' && $top != '(') || ($c == ']' && $top != '[') || ($c == '}' && $top != '{')) { $result = false; break; }\n    }\n}\nif (!empty($stack)) { $result = false; }",
    "scala": "val stack = scala.collection.mutable.ArrayBuffer[Char]()\nvar result = true\nvar stop = false\nfor (c <- s if !stop) {\n  if (c == '(' || c == '[' || c == '{') stack += c\n  else {\n    if (stack.isEmpty) { result = false; stop = true }\n    else {\n      val top = stack.remove(stack.length - 1)\n      if ((c == ')' && top != '(') || (c == ']' && top != '[') || (c == '}' && top != '{')) { result = false; stop = true }\n    }\n  }\n}\nif (stack.nonEmpty) result = false",
    "r": "stack <- c()\nresult <- TRUE\nchars <- strsplit(s, \"\")[[1]]\nfor (c in chars) {\n  if (c == '(' || c == '[' || c == '{') { stack <- c(stack, c) }\n  else {\n    if (length(stack) == 0) { result <- FALSE; break }\n    top <- stack[length(stack)]\n    stack <- stack[-length(stack)]\n    if ((c == ')' && top != '(') || (c == ']' && top != '[') || (c == '}' && top != '{')) { result <- FALSE; break }\n  }\n}\nif (length(stack) != 0) result <- FALSE",
    "javascript": "const stack = [];\nlet result = true;\nfor (const c of s) {\n    if (c === '(' || c === '[' || c === '{') stack.push(c);\n    else {\n        if (stack.length === 0) { result = false; break; }\n        const top = stack.pop();\n        if ((c === ')' && top !== '(') || (c === ']' && top !== '[') || (c === '}' && top !== '{')) { result = false; break; }\n    }\n}\nif (stack.length !== 0) result = false;",
    "typescript": "const stack: string[] = [];\nlet result = true;\nfor (const c of s) {\n    if (c === '(' || c === '[' || c === '{') stack.push(c);\n    else {\n        if (stack.length === 0) { result = false; break; }\n        const top = stack.pop();\n        if ((c === ')' && top !== '(') || (c === ']' && top !== '[') || (c === '}' && top !== '{')) { result = false; break; }\n    }\n}\nif (stack.length !== 0) result = false;",
    "perl": "my @stack;\nmy $result = 1;\nforeach my $c (split //, $s) {\n    if ($c eq '(' || $c eq '[' || $c eq '{') { push @stack, $c; }\n    else {\n        if (!@stack) { $result = 0; last; }\n        my $top = pop @stack;\n        if (($c eq ')' && $top ne '(') || ($c eq ']' && $top ne '[') || ($c eq '}' && $top ne '{')) { $result = 0; last; }\n    }\n}\n$result = 0 if @stack;",
    "java": "java.util.Deque<Character> stack = new java.util.ArrayDeque<>();\nboolean result = true;\nfor (char c : s.toCharArray()) {\n    if (c == '(' || c == '[' || c == '{') stack.push(c);\n    else {\n        if (stack.isEmpty()) { result = false; break; }\n        char top = stack.pop();\n        if ((c == ')' && top != '(') || (c == ']' && top != '[') || (c == '}' && top != '{')) { result = false; break; }\n    }\n}\nif (!stack.isEmpty()) result = false;",
    "cpp": "std::vector<char> stack;\nbool result = true;\nfor (char c : s) {\n    if (c == '(' || c == '[' || c == '{') stack.push_back(c);\n    else {\n        if (stack.empty()) { result = false; break; }\n        char top = stack.back(); stack.pop_back();\n        if ((c == ')' && top != '(') || (c == ']' && top != '[') || (c == '}' && top != '{')) { result = false; break; }\n    }\n}\nif (!stack.empty()) result = false;",
    "csharp": "var stack = new System.Collections.Generic.Stack<char>();\nbool result = true;\nforeach (char c in s) {\n    if (c == '(' || c == '[' || c == '{') stack.Push(c);\n    else {\n        if (stack.Count == 0) { result = false; break; }\n        char top = stack.Pop();\n        if ((c == ')' && top != '(') || (c == ']' && top != '[') || (c == '}' && top != '{')) { result = false; break; }\n    }\n}\nif (stack.Count != 0) result = false;",
    "c": "char stack[100000];\nint top = 0;\nint result = 1;\nint n = (int) strlen(s);\nfor (int i = 0; i < n; i++) {\n    char c = s[i];\n    if (c == '(' || c == '[' || c == '{') { stack[top++] = c; }\n    else {\n        if (top == 0) { result = 0; break; }\n        char t = stack[--top];\n        if ((c == ')' && t != '(') || (c == ']' && t != '[') || (c == '}' && t != '{')) { result = 0; break; }\n    }\n}\nif (top != 0) result = 0;",
    "rust": "let mut stack: Vec<char> = Vec::new();\nlet mut result = true;\nfor c in s.chars() {\n    if c == '(' || c == '[' || c == '{' { stack.push(c); }\n    else {\n        match stack.pop() {\n            None => { result = false; break; }\n            Some(top) => {\n                if (c == ')' && top != '(') || (c == ']' && top != '[') || (c == '}' && top != '{') { result = false; break; }\n            }\n        }\n    }\n}\nif !stack.is_empty() { result = false; }",
    "swift": "var stack: [Character] = []\nvar result = true\nfor c in s {\n    if c == \"(\" || c == \"[\" || c == \"{\" { stack.append(c) }\n    else {\n        if stack.isEmpty { result = false; break }\n        let top = stack.removeLast()\n        if (c == \")\" && top != \"(\") || (c == \"]\" && top != \"[\") || (c == \"}\" && top != \"{\") { result = false; break }\n    }\n}\nif !stack.isEmpty { result = false }",
})

# ═════════════════════════════════════════════════════════════════════════
# is_valid_palindrome(s) -> bool, alnum-only case-insensitive palindrome
# ═════════════════════════════════════════════════════════════════════════
add("valid-palindrome-string", "str1", "is_valid_palindrome", "bool", {
    "go": "clean := []rune{}\nfor _, c := range strings.ToLower(s) {\n\tif (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') { clean = append(clean, c) }\n}\nl, r := 0, len(clean)-1\nresult := true\nfor l < r {\n\tif clean[l] != clean[r] { result = false; break }\n\tl++; r--\n}",
    "ruby": "clean = s.downcase.chars.select { |c| c =~ /[a-z0-9]/ }\nl = 0\nr = clean.length - 1\nresult = true\nwhile l < r\n  if clean[l] != clean[r]\n    result = false\n    break\n  end\n  l += 1\n  r -= 1\nend",
    "kotlin": "val clean = s.lowercase().filter { it.isLetterOrDigit() && it.code < 128 }\nvar l = 0\nvar r = clean.length - 1\nvar result = true\nwhile (l < r) {\n    if (clean[l] != clean[r]) { result = false; break }\n    l++; r--\n}",
    "php": "$lower = strtolower($s);\n$clean = '';\nfor ($i = 0; $i < strlen($lower); $i++) { if (ctype_alnum($lower[$i])) { $clean .= $lower[$i]; } }\n$l = 0; $r = strlen($clean) - 1; $result = true;\nwhile ($l < $r) {\n    if ($clean[$l] != $clean[$r]) { $result = false; break; }\n    $l++; $r--;\n}",
    "scala": "val clean = s.toLowerCase.filter(c => c.isLetterOrDigit && c.toInt < 128)\nvar l = 0\nvar r = clean.length - 1\nvar result = true\nvar stop = false\nwhile (l < r && !stop) {\n  if (clean(l) != clean(r)) { result = false; stop = true }\n  l += 1; r -= 1\n}",
    "r": "lower <- tolower(s)\nchars <- strsplit(lower, \"\")[[1]]\nclean <- chars[grepl(\"[a-z0-9]\", chars)]\nl <- 1; r <- length(clean); result <- TRUE\nwhile (l < r) {\n  if (clean[l] != clean[r]) { result <- FALSE; break }\n  l <- l + 1; r <- r - 1\n}",
    "javascript": "const clean = s.toLowerCase().split('').filter(c => /[a-z0-9]/.test(c));\nlet l = 0, r = clean.length - 1;\nlet result = true;\nwhile (l < r) {\n    if (clean[l] !== clean[r]) { result = false; break; }\n    l++; r--;\n}",
    "typescript": "const clean = s.toLowerCase().split('').filter(c => /[a-z0-9]/.test(c));\nlet l = 0, r = clean.length - 1;\nlet result = true;\nwhile (l < r) {\n    if (clean[l] !== clean[r]) { result = false; break; }\n    l++; r--;\n}",
    "perl": "my $lower = lc($s);\nmy @clean = grep { /[a-z0-9]/ } split //, $lower;\nmy $l = 0; my $r = scalar(@clean) - 1; my $result = 1;\nwhile ($l < $r) {\n    if ($clean[$l] ne $clean[$r]) { $result = 0; last; }\n    $l++; $r--;\n}",
    "java": "String lower = s.toLowerCase();\nStringBuilder cb = new StringBuilder();\nfor (char c : lower.toCharArray()) { if (Character.isLetterOrDigit(c) && c < 128) cb.append(c); }\nString clean = cb.toString();\nint l = 0, r = clean.length() - 1;\nboolean result = true;\nwhile (l < r) {\n    if (clean.charAt(l) != clean.charAt(r)) { result = false; break; }\n    l++; r--;\n}",
    "cpp": "std::string lower = s;\nfor (auto &c : lower) c = tolower((unsigned char) c);\nstd::string clean;\nfor (char c : lower) { if (isalnum((unsigned char) c)) clean += c; }\nint l = 0, r = (int) clean.size() - 1;\nbool result = true;\nwhile (l < r) {\n    if (clean[l] != clean[r]) { result = false; break; }\n    l++; r--;\n}",
    "csharp": "string lower = s.ToLower();\nvar cb = new System.Text.StringBuilder();\nforeach (char c in lower) { if (char.IsLetterOrDigit(c) && c < 128) cb.Append(c); }\nstring clean = cb.ToString();\nint l = 0, r = clean.Length - 1;\nbool result = true;\nwhile (l < r) {\n    if (clean[l] != clean[r]) { result = false; break; }\n    l++; r--;\n}",
    "c": "int n = (int) strlen(s);\nchar *clean = (char *)malloc((size_t) n + 1);\nint cl = 0;\nfor (int i = 0; i < n; i++) {\n    char c = (char) tolower((unsigned char) s[i]);\n    if (isalnum((unsigned char) c)) clean[cl++] = c;\n}\nint l = 0, r = cl - 1;\nint result = 1;\nwhile (l < r) {\n    if (clean[l] != clean[r]) { result = 0; break; }\n    l++; r--;\n}\nfree(clean);",
    "rust": "let clean: Vec<char> = s.to_lowercase().chars().filter(|c| c.is_ascii_alphanumeric()).collect();\nlet mut l: i32 = 0;\nlet mut r: i32 = clean.len() as i32 - 1;\nlet mut result = true;\nwhile l < r {\n    if clean[l as usize] != clean[r as usize] { result = false; break; }\n    l += 1; r -= 1;\n}",
    "swift": "let clean = Array(s.lowercased().unicodeScalars.filter { CharacterSet.alphanumerics.contains($0) && $0.isASCII }.map { Character($0) })\nvar l = 0\nvar r = clean.count - 1\nvar result = true\nwhile l < r {\n    if clean[l] != clean[r] { result = false; break }\n    l += 1; r -= 1\n}",
})

# ═════════════════════════════════════════════════════════════════════════
# is_anagram(s, t) -> bool, same character multiset
# ═════════════════════════════════════════════════════════════════════════
add("valid-anagram", "str2", "is_anagram", "bool", {
    "go": "result := len(s) == len(t)\nif result {\n\tcounts := make(map[rune]int)\n\tfor _, c := range s { counts[c]++ }\n\tfor _, c := range t { counts[c]-- }\n\tfor _, v := range counts { if v != 0 { result = false; break } }\n}",
    "ruby": "result = s.length == t.length\nif result\n  counts = Hash.new(0)\n  s.each_char { |c| counts[c] += 1 }\n  t.each_char { |c| counts[c] -= 1 }\n  result = counts.values.all? { |v| v == 0 }\nend",
    "kotlin": "var result = s.length == t.length\nif (result) {\n    val counts = HashMap<Char, Int>()\n    for (c in s) counts[c] = (counts[c] ?: 0) + 1\n    for (c in t) counts[c] = (counts[c] ?: 0) - 1\n    result = counts.values.all { it == 0 }\n}",
    "php": "$result = strlen($s) == strlen($t);\nif ($result) {\n    $counts = [];\n    for ($i = 0; $i < strlen($s); $i++) { $counts[$s[$i]] = ($counts[$s[$i]] ?? 0) + 1; }\n    for ($i = 0; $i < strlen($t); $i++) { $counts[$t[$i]] = ($counts[$t[$i]] ?? 0) - 1; }\n    foreach ($counts as $v) { if ($v != 0) { $result = false; break; } }\n}",
    "scala": "var result = s.length == t.length\nif (result) {\n  val counts = scala.collection.mutable.HashMap[Char, Int]().withDefaultValue(0)\n  for (c <- s) counts(c) += 1\n  for (c <- t) counts(c) -= 1\n  result = counts.values.forall(_ == 0)\n}",
    "r": "result <- nchar(s) == nchar(t)\nif (result) {\n  sc <- strsplit(s, \"\")[[1]]\n  tc <- strsplit(t, \"\")[[1]]\n  ts <- table(sc)\n  tt <- table(tc)\n  allKeys <- union(names(ts), names(tt))\n  for (k in allKeys) {\n    a <- if (k %in% names(ts)) ts[[k]] else 0\n    b <- if (k %in% names(tt)) tt[[k]] else 0\n    if (a != b) { result <- FALSE; break }\n  }\n}",
    "javascript": "let result = s.length === t.length;\nif (result) {\n    const counts = new Map();\n    for (const c of s) counts.set(c, (counts.get(c) || 0) + 1);\n    for (const c of t) counts.set(c, (counts.get(c) || 0) - 1);\n    for (const v of counts.values()) { if (v !== 0) { result = false; break; } }\n}",
    "typescript": "let result = s.length === t.length;\nif (result) {\n    const counts = new Map<string, number>();\n    for (const c of s) counts.set(c, (counts.get(c) || 0) + 1);\n    for (const c of t) counts.set(c, (counts.get(c) || 0) - 1);\n    for (const v of counts.values()) { if (v !== 0) { result = false; break; } }\n}",
    "perl": "my $result = length($s) == length($t);\nif ($result) {\n    my %counts;\n    foreach my $c (split //, $s) { $counts{$c}++; }\n    foreach my $c (split //, $t) { $counts{$c}--; }\n    foreach my $v (values %counts) { if ($v != 0) { $result = 0; last; } }\n}",
    "java": "boolean result = s.length() == t.length();\nif (result) {\n    java.util.Map<Character, Integer> counts = new java.util.HashMap<>();\n    for (char c : s.toCharArray()) counts.merge(c, 1, Integer::sum);\n    for (char c : t.toCharArray()) counts.merge(c, -1, Integer::sum);\n    for (int v : counts.values()) { if (v != 0) { result = false; break; } }\n}",
    "cpp": "bool result = s.size() == t.size();\nif (result) {\n    std::unordered_map<char, int> counts;\n    for (char c : s) counts[c]++;\n    for (char c : t) counts[c]--;\n    for (auto &p : counts) { if (p.second != 0) { result = false; break; } }\n}",
    "csharp": "bool result = s.Length == t.Length;\nif (result) {\n    var counts = new System.Collections.Generic.Dictionary<char, int>();\n    foreach (char c in s) counts[c] = counts.ContainsKey(c) ? counts[c] + 1 : 1;\n    foreach (char c in t) counts[c] = counts.ContainsKey(c) ? counts[c] - 1 : -1;\n    foreach (var v in counts.Values) { if (v != 0) { result = false; break; } }\n}",
    "c": "int result = (int) strlen(s) == (int) strlen(t);\nif (result) {\n    int counts[256] = {0};\n    for (int i = 0; s[i]; i++) counts[(unsigned char) s[i]]++;\n    for (int i = 0; t[i]; i++) counts[(unsigned char) t[i]]--;\n    for (int i = 0; i < 256; i++) { if (counts[i] != 0) { result = 0; break; } }\n}",
    "rust": "let mut result = s.len() == t.len();\nif result {\n    let mut counts = std::collections::HashMap::new();\n    for c in s.chars() { *counts.entry(c).or_insert(0) += 1; }\n    for c in t.chars() { *counts.entry(c).or_insert(0) -= 1; }\n    result = counts.values().all(|&v| v == 0);\n}",
    "swift": "var result = s.count == t.count\nif result {\n    var counts: [Character: Int] = [:]\n    for c in s { counts[c, default: 0] += 1 }\n    for c in t { counts[c, default: 0] -= 1 }\n    result = counts.values.allSatisfy { $0 == 0 }\n}",
})

# ═════════════════════════════════════════════════════════════════════════
# edit_distance(s, t) -> int, classic Levenshtein DP
# ═════════════════════════════════════════════════════════════════════════
add("edit-distance", "str2", "edit_distance", "int", {
    "go": "n, m := len(s), len(t)\ndp := make([][]int, n+1)\nfor i := range dp { dp[i] = make([]int, m+1) }\nfor i := 0; i <= n; i++ { dp[i][0] = i }\nfor j := 0; j <= m; j++ { dp[0][j] = j }\nfor i := 1; i <= n; i++ {\n\tfor j := 1; j <= m; j++ {\n\t\tif s[i-1] == t[j-1] { dp[i][j] = dp[i-1][j-1] } else {\n\t\t\tmn := dp[i-1][j-1]\n\t\t\tif dp[i-1][j] < mn { mn = dp[i-1][j] }\n\t\t\tif dp[i][j-1] < mn { mn = dp[i][j-1] }\n\t\t\tdp[i][j] = mn + 1\n\t\t}\n\t}\n}\nresult := int64(dp[n][m])",
    "ruby": "n = s.length\nm = t.length\ndp = Array.new(n + 1) { Array.new(m + 1, 0) }\n(0..n).each { |i| dp[i][0] = i }\n(0..m).each { |j| dp[0][j] = j }\n(1..n).each do |i|\n  (1..m).each do |j|\n    if s[i - 1] == t[j - 1]\n      dp[i][j] = dp[i - 1][j - 1]\n    else\n      dp[i][j] = 1 + [dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]].min\n    end\n  end\nend\nresult = dp[n][m]",
    "kotlin": "val n = s.length\nval m = t.length\nval dp = Array(n + 1) { IntArray(m + 1) }\nfor (i in 0..n) dp[i][0] = i\nfor (j in 0..m) dp[0][j] = j\nfor (i in 1..n) {\n    for (j in 1..m) {\n        dp[i][j] = if (s[i - 1] == t[j - 1]) dp[i - 1][j - 1]\n            else 1 + minOf(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1])\n    }\n}\nval result = dp[n][m].toLong()",
    "php": "$n = strlen($s); $m = strlen($t);\n$dp = array_fill(0, $n + 1, array_fill(0, $m + 1, 0));\nfor ($i = 0; $i <= $n; $i++) { $dp[$i][0] = $i; }\nfor ($j = 0; $j <= $m; $j++) { $dp[0][$j] = $j; }\nfor ($i = 1; $i <= $n; $i++) {\n    for ($j = 1; $j <= $m; $j++) {\n        if ($s[$i - 1] == $t[$j - 1]) { $dp[$i][$j] = $dp[$i - 1][$j - 1]; }\n        else { $dp[$i][$j] = 1 + min($dp[$i - 1][$j - 1], $dp[$i - 1][$j], $dp[$i][$j - 1]); }\n    }\n}\n$result = $dp[$n][$m];",
    "scala": "val n = s.length\nval m = t.length\nval dp = Array.ofDim[Int](n + 1, m + 1)\nfor (i <- 0 to n) dp(i)(0) = i\nfor (j <- 0 to m) dp(0)(j) = j\nfor (i <- 1 to n) {\n  for (j <- 1 to m) {\n    dp(i)(j) = if (s(i - 1) == t(j - 1)) dp(i - 1)(j - 1)\n      else 1 + math.min(dp(i - 1)(j - 1), math.min(dp(i - 1)(j), dp(i)(j - 1)))\n  }\n}\nval result: Long = dp(n)(m)",
    "r": "n <- nchar(s); m <- nchar(t)\nsc <- strsplit(s, \"\")[[1]]\ntc <- strsplit(t, \"\")[[1]]\ndp <- matrix(0, nrow = n + 1, ncol = m + 1)\nfor (i in 0:n) dp[i + 1, 1] <- i\nfor (j in 0:m) dp[1, j + 1] <- j\nif (n > 0 && m > 0) {\n  for (i in 1:n) {\n    for (j in 1:m) {\n      if (sc[i] == tc[j]) { dp[i + 1, j + 1] <- dp[i, j] }\n      else { dp[i + 1, j + 1] <- 1 + min(dp[i, j], dp[i, j + 1], dp[i + 1, j]) }\n    }\n  }\n}\nresult <- dp[n + 1, m + 1]",
    "javascript": "const n = s.length, m = t.length;\nconst dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));\nfor (let i = 0; i <= n; i++) dp[i][0] = i;\nfor (let j = 0; j <= m; j++) dp[0][j] = j;\nfor (let i = 1; i <= n; i++) {\n    for (let j = 1; j <= m; j++) {\n        dp[i][j] = s[i - 1] === t[j - 1] ? dp[i - 1][j - 1] : 1 + Math.min(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]);\n    }\n}\nconst result = dp[n][m];",
    "typescript": "const n = s.length, m = t.length;\nconst dp: number[][] = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));\nfor (let i = 0; i <= n; i++) dp[i][0] = i;\nfor (let j = 0; j <= m; j++) dp[0][j] = j;\nfor (let i = 1; i <= n; i++) {\n    for (let j = 1; j <= m; j++) {\n        dp[i][j] = s[i - 1] === t[j - 1] ? dp[i - 1][j - 1] : 1 + Math.min(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]);\n    }\n}\nconst result = dp[n][m];",
    "perl": "my $n = length($s); my $m = length($t);\nmy @dp;\nfor my $i (0..$n) { $dp[$i][0] = $i; }\nfor my $j (0..$m) { $dp[0][$j] = $j; }\nfor my $i (1..$n) {\n    for my $j (1..$m) {\n        if (substr($s, $i - 1, 1) eq substr($t, $j - 1, 1)) { $dp[$i][$j] = $dp[$i - 1][$j - 1]; }\n        else {\n            my $mn = $dp[$i - 1][$j - 1];\n            $mn = $dp[$i - 1][$j] if $dp[$i - 1][$j] < $mn;\n            $mn = $dp[$i][$j - 1] if $dp[$i][$j - 1] < $mn;\n            $dp[$i][$j] = $mn + 1;\n        }\n    }\n}\nmy $result = $dp[$n][$m];",
    "java": "int n = s.length(), m = t.length();\nint[][] dp = new int[n + 1][m + 1];\nfor (int i = 0; i <= n; i++) dp[i][0] = i;\nfor (int j = 0; j <= m; j++) dp[0][j] = j;\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        dp[i][j] = s.charAt(i - 1) == t.charAt(j - 1) ? dp[i - 1][j - 1] : 1 + Math.min(dp[i - 1][j - 1], Math.min(dp[i - 1][j], dp[i][j - 1]));\n    }\n}\nint result = dp[n][m];",
    "cpp": "int n = (int) s.size(), m = (int) t.size();\nstd::vector<std::vector<int>> dp(n + 1, std::vector<int>(m + 1, 0));\nfor (int i = 0; i <= n; i++) dp[i][0] = i;\nfor (int j = 0; j <= m; j++) dp[0][j] = j;\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        dp[i][j] = s[i - 1] == t[j - 1] ? dp[i - 1][j - 1] : 1 + std::min({dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]});\n    }\n}\nint result = dp[n][m];",
    "csharp": "int n = s.Length, m = t.Length;\nvar dp = new int[n + 1, m + 1];\nfor (int i = 0; i <= n; i++) dp[i, 0] = i;\nfor (int j = 0; j <= m; j++) dp[0, j] = j;\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        dp[i, j] = s[i - 1] == t[j - 1] ? dp[i - 1, j - 1] : 1 + System.Math.Min(dp[i - 1, j - 1], System.Math.Min(dp[i - 1, j], dp[i, j - 1]));\n    }\n}\nint result = dp[n, m];",
    "c": "int n = (int) strlen(s), m = (int) strlen(t);\nint **dp = (int **)malloc(sizeof(int *) * (size_t)(n + 1));\nfor (int i = 0; i <= n; i++) dp[i] = (int *)calloc((size_t)(m + 1), sizeof(int));\nfor (int i = 0; i <= n; i++) dp[i][0] = i;\nfor (int j = 0; j <= m; j++) dp[0][j] = j;\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        if (s[i - 1] == t[j - 1]) { dp[i][j] = dp[i - 1][j - 1]; }\n        else {\n            int mn = dp[i - 1][j - 1];\n            if (dp[i - 1][j] < mn) mn = dp[i - 1][j];\n            if (dp[i][j - 1] < mn) mn = dp[i][j - 1];\n            dp[i][j] = mn + 1;\n        }\n    }\n}\nint result = dp[n][m];",
    "rust": "let sc: Vec<char> = s.chars().collect();\nlet tc: Vec<char> = t.chars().collect();\nlet n = sc.len();\nlet m = tc.len();\nlet mut dp = vec![vec![0i32; m + 1]; n + 1];\nfor i in 0..=n { dp[i][0] = i as i32; }\nfor j in 0..=m { dp[0][j] = j as i32; }\nfor i in 1..=n {\n    for j in 1..=m {\n        dp[i][j] = if sc[i - 1] == tc[j - 1] { dp[i - 1][j - 1] }\n            else { 1 + *[dp[i-1][j-1], dp[i-1][j], dp[i][j-1]].iter().min().unwrap() };\n    }\n}\nlet result: i32 = dp[n][m];",
    "swift": "let sc = Array(s)\nlet tc = Array(t)\nlet n = sc.count\nlet m = tc.count\nvar dp = Array(repeating: Array(repeating: 0, count: m + 1), count: n + 1)\nfor i in 0...n { dp[i][0] = i }\nfor j in 0...m { dp[0][j] = j }\nif n > 0 && m > 0 {\n    for i in 1...n {\n        for j in 1...m {\n            if sc[i - 1] == tc[j - 1] { dp[i][j] = dp[i - 1][j - 1] }\n            else { dp[i][j] = 1 + min(dp[i - 1][j - 1], min(dp[i - 1][j], dp[i][j - 1])) }\n        }\n    }\n}\nlet result = dp[n][m]",
})


# ═════════════════════════════════════════════════════════════════════════
# lcs(s, t) -> int, longest common subsequence length DP
# ═════════════════════════════════════════════════════════════════════════
add("longest-common-subsequence", "str2", "lcs", "int", {
    "go": "n, m := len(s), len(t)\ndp := make([][]int, n+1)\nfor i := range dp { dp[i] = make([]int, m+1) }\nfor i := 1; i <= n; i++ {\n\tfor j := 1; j <= m; j++ {\n\t\tif s[i-1] == t[j-1] { dp[i][j] = dp[i-1][j-1] + 1 } else {\n\t\t\tif dp[i-1][j] > dp[i][j-1] { dp[i][j] = dp[i-1][j] } else { dp[i][j] = dp[i][j-1] }\n\t\t}\n\t}\n}\nresult := int64(dp[n][m])",
    "ruby": "n = s.length\nm = t.length\ndp = Array.new(n + 1) { Array.new(m + 1, 0) }\n(1..n).each do |i|\n  (1..m).each do |j|\n    if s[i - 1] == t[j - 1]\n      dp[i][j] = dp[i - 1][j - 1] + 1\n    else\n      dp[i][j] = [dp[i - 1][j], dp[i][j - 1]].max\n    end\n  end\nend\nresult = dp[n][m]",
    "kotlin": "val n = s.length\nval m = t.length\nval dp = Array(n + 1) { IntArray(m + 1) }\nfor (i in 1..n) {\n    for (j in 1..m) {\n        dp[i][j] = if (s[i - 1] == t[j - 1]) dp[i - 1][j - 1] + 1 else maxOf(dp[i - 1][j], dp[i][j - 1])\n    }\n}\nval result = dp[n][m].toLong()",
    "php": "$n = strlen($s); $m = strlen($t);\n$dp = array_fill(0, $n + 1, array_fill(0, $m + 1, 0));\nfor ($i = 1; $i <= $n; $i++) {\n    for ($j = 1; $j <= $m; $j++) {\n        if ($s[$i - 1] == $t[$j - 1]) { $dp[$i][$j] = $dp[$i - 1][$j - 1] + 1; }\n        else { $dp[$i][$j] = max($dp[$i - 1][$j], $dp[$i][$j - 1]); }\n    }\n}\n$result = $dp[$n][$m];",
    "scala": "val n = s.length\nval m = t.length\nval dp = Array.ofDim[Int](n + 1, m + 1)\nfor (i <- 1 to n) {\n  for (j <- 1 to m) {\n    dp(i)(j) = if (s(i - 1) == t(j - 1)) dp(i - 1)(j - 1) + 1 else math.max(dp(i - 1)(j), dp(i)(j - 1))\n  }\n}\nval result: Long = dp(n)(m)",
    "r": "n <- nchar(s); m <- nchar(t)\nsc <- strsplit(s, \"\")[[1]]\ntc <- strsplit(t, \"\")[[1]]\ndp <- matrix(0, nrow = n + 1, ncol = m + 1)\nif (n > 0 && m > 0) {\n  for (i in 1:n) {\n    for (j in 1:m) {\n      if (sc[i] == tc[j]) { dp[i + 1, j + 1] <- dp[i, j] + 1 }\n      else { dp[i + 1, j + 1] <- max(dp[i, j + 1], dp[i + 1, j]) }\n    }\n  }\n}\nresult <- dp[n + 1, m + 1]",
    "javascript": "const n = s.length, m = t.length;\nconst dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));\nfor (let i = 1; i <= n; i++) {\n    for (let j = 1; j <= m; j++) {\n        dp[i][j] = s[i - 1] === t[j - 1] ? dp[i - 1][j - 1] + 1 : Math.max(dp[i - 1][j], dp[i][j - 1]);\n    }\n}\nconst result = dp[n][m];",
    "typescript": "const n = s.length, m = t.length;\nconst dp: number[][] = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));\nfor (let i = 1; i <= n; i++) {\n    for (let j = 1; j <= m; j++) {\n        dp[i][j] = s[i - 1] === t[j - 1] ? dp[i - 1][j - 1] + 1 : Math.max(dp[i - 1][j], dp[i][j - 1]);\n    }\n}\nconst result = dp[n][m];",
    "perl": "my $n = length($s); my $m = length($t);\nmy @dp;\nfor my $i (0..$n) { for my $j (0..$m) { $dp[$i][$j] = 0; } }\nfor my $i (1..$n) {\n    for my $j (1..$m) {\n        if (substr($s, $i - 1, 1) eq substr($t, $j - 1, 1)) { $dp[$i][$j] = $dp[$i - 1][$j - 1] + 1; }\n        else { $dp[$i][$j] = $dp[$i - 1][$j] > $dp[$i][$j - 1] ? $dp[$i - 1][$j] : $dp[$i][$j - 1]; }\n    }\n}\nmy $result = $dp[$n][$m];",
    "java": "int n = s.length(), m = t.length();\nint[][] dp = new int[n + 1][m + 1];\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        dp[i][j] = s.charAt(i - 1) == t.charAt(j - 1) ? dp[i - 1][j - 1] + 1 : Math.max(dp[i - 1][j], dp[i][j - 1]);\n    }\n}\nint result = dp[n][m];",
    "cpp": "int n = (int) s.size(), m = (int) t.size();\nstd::vector<std::vector<int>> dp(n + 1, std::vector<int>(m + 1, 0));\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        dp[i][j] = s[i - 1] == t[j - 1] ? dp[i - 1][j - 1] + 1 : std::max(dp[i - 1][j], dp[i][j - 1]);\n    }\n}\nint result = dp[n][m];",
    "csharp": "int n = s.Length, m = t.Length;\nvar dp = new int[n + 1, m + 1];\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        dp[i, j] = s[i - 1] == t[j - 1] ? dp[i - 1, j - 1] + 1 : System.Math.Max(dp[i - 1, j], dp[i, j - 1]);\n    }\n}\nint result = dp[n, m];",
    "c": "int n = (int) strlen(s), m = (int) strlen(t);\nint **dp = (int **)malloc(sizeof(int *) * (size_t)(n + 1));\nfor (int i = 0; i <= n; i++) dp[i] = (int *)calloc((size_t)(m + 1), sizeof(int));\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        if (s[i - 1] == t[j - 1]) { dp[i][j] = dp[i - 1][j - 1] + 1; }\n        else { dp[i][j] = dp[i - 1][j] > dp[i][j - 1] ? dp[i - 1][j] : dp[i][j - 1]; }\n    }\n}\nint result = dp[n][m];",
    "rust": "let sc: Vec<char> = s.chars().collect();\nlet tc: Vec<char> = t.chars().collect();\nlet n = sc.len();\nlet m = tc.len();\nlet mut dp = vec![vec![0i32; m + 1]; n + 1];\nfor i in 1..=n {\n    for j in 1..=m {\n        dp[i][j] = if sc[i - 1] == tc[j - 1] { dp[i - 1][j - 1] + 1 } else { std::cmp::max(dp[i - 1][j], dp[i][j - 1]) };\n    }\n}\nlet result: i32 = dp[n][m];",
    "swift": "let sc = Array(s)\nlet tc = Array(t)\nlet n = sc.count\nlet m = tc.count\nvar dp = Array(repeating: Array(repeating: 0, count: m + 1), count: n + 1)\nif n > 0 && m > 0 {\n    for i in 1...n {\n        for j in 1...m {\n            if sc[i - 1] == tc[j - 1] { dp[i][j] = dp[i - 1][j - 1] + 1 }\n            else { dp[i][j] = max(dp[i - 1][j], dp[i][j - 1]) }\n        }\n    }\n}\nlet result = dp[n][m]",
})

# ═════════════════════════════════════════════════════════════════════════
# longest_common_substring(s, t) -> int, longest CONTIGUOUS common
# substring length DP
# ═════════════════════════════════════════════════════════════════════════
add("longest-common-substring", "str2", "longest_common_substring", "int", {
    "go": "n, m := len(s), len(t)\ndp := make([][]int, n+1)\nfor i := range dp { dp[i] = make([]int, m+1) }\nbest := 0\nfor i := 1; i <= n; i++ {\n\tfor j := 1; j <= m; j++ {\n\t\tif s[i-1] == t[j-1] {\n\t\t\tdp[i][j] = dp[i-1][j-1] + 1\n\t\t\tif dp[i][j] > best { best = dp[i][j] }\n\t\t}\n\t}\n}\nresult := int64(best)",
    "ruby": "n = s.length\nm = t.length\ndp = Array.new(n + 1) { Array.new(m + 1, 0) }\nbest = 0\n(1..n).each do |i|\n  (1..m).each do |j|\n    if s[i - 1] == t[j - 1]\n      dp[i][j] = dp[i - 1][j - 1] + 1\n      best = dp[i][j] if dp[i][j] > best\n    end\n  end\nend\nresult = best",
    "kotlin": "val n = s.length\nval m = t.length\nval dp = Array(n + 1) { IntArray(m + 1) }\nvar best = 0\nfor (i in 1..n) {\n    for (j in 1..m) {\n        if (s[i - 1] == t[j - 1]) {\n            dp[i][j] = dp[i - 1][j - 1] + 1\n            if (dp[i][j] > best) best = dp[i][j]\n        }\n    }\n}\nval result = best.toLong()",
    "php": "$n = strlen($s); $m = strlen($t);\n$dp = array_fill(0, $n + 1, array_fill(0, $m + 1, 0));\n$best = 0;\nfor ($i = 1; $i <= $n; $i++) {\n    for ($j = 1; $j <= $m; $j++) {\n        if ($s[$i - 1] == $t[$j - 1]) {\n            $dp[$i][$j] = $dp[$i - 1][$j - 1] + 1;\n            if ($dp[$i][$j] > $best) { $best = $dp[$i][$j]; }\n        }\n    }\n}\n$result = $best;",
    "scala": "val n = s.length\nval m = t.length\nval dp = Array.ofDim[Int](n + 1, m + 1)\nvar best = 0\nfor (i <- 1 to n) {\n  for (j <- 1 to m) {\n    if (s(i - 1) == t(j - 1)) {\n      dp(i)(j) = dp(i - 1)(j - 1) + 1\n      if (dp(i)(j) > best) best = dp(i)(j)\n    }\n  }\n}\nval result: Long = best",
    "r": "n <- nchar(s); m <- nchar(t)\nsc <- strsplit(s, \"\")[[1]]\ntc <- strsplit(t, \"\")[[1]]\ndp <- matrix(0, nrow = n + 1, ncol = m + 1)\nbest <- 0\nif (n > 0 && m > 0) {\n  for (i in 1:n) {\n    for (j in 1:m) {\n      if (sc[i] == tc[j]) {\n        dp[i + 1, j + 1] <- dp[i, j] + 1\n        if (dp[i + 1, j + 1] > best) best <- dp[i + 1, j + 1]\n      }\n    }\n  }\n}\nresult <- best",
    "javascript": "const n = s.length, m = t.length;\nconst dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));\nlet best = 0;\nfor (let i = 1; i <= n; i++) {\n    for (let j = 1; j <= m; j++) {\n        if (s[i - 1] === t[j - 1]) {\n            dp[i][j] = dp[i - 1][j - 1] + 1;\n            if (dp[i][j] > best) best = dp[i][j];\n        }\n    }\n}\nconst result = best;",
    "typescript": "const n = s.length, m = t.length;\nconst dp: number[][] = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));\nlet best = 0;\nfor (let i = 1; i <= n; i++) {\n    for (let j = 1; j <= m; j++) {\n        if (s[i - 1] === t[j - 1]) {\n            dp[i][j] = dp[i - 1][j - 1] + 1;\n            if (dp[i][j] > best) best = dp[i][j];\n        }\n    }\n}\nconst result = best;",
    "perl": "my $n = length($s); my $m = length($t);\nmy @dp;\nfor my $i (0..$n) { for my $j (0..$m) { $dp[$i][$j] = 0; } }\nmy $best = 0;\nfor my $i (1..$n) {\n    for my $j (1..$m) {\n        if (substr($s, $i - 1, 1) eq substr($t, $j - 1, 1)) {\n            $dp[$i][$j] = $dp[$i - 1][$j - 1] + 1;\n            $best = $dp[$i][$j] if $dp[$i][$j] > $best;\n        }\n    }\n}\nmy $result = $best;",
    "java": "int n = s.length(), m = t.length();\nint[][] dp = new int[n + 1][m + 1];\nint best = 0;\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        if (s.charAt(i - 1) == t.charAt(j - 1)) {\n            dp[i][j] = dp[i - 1][j - 1] + 1;\n            if (dp[i][j] > best) best = dp[i][j];\n        }\n    }\n}\nint result = best;",
    "cpp": "int n = (int) s.size(), m = (int) t.size();\nstd::vector<std::vector<int>> dp(n + 1, std::vector<int>(m + 1, 0));\nint best = 0;\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        if (s[i - 1] == t[j - 1]) {\n            dp[i][j] = dp[i - 1][j - 1] + 1;\n            if (dp[i][j] > best) best = dp[i][j];\n        }\n    }\n}\nint result = best;",
    "csharp": "int n = s.Length, m = t.Length;\nvar dp = new int[n + 1, m + 1];\nint best = 0;\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        if (s[i - 1] == t[j - 1]) {\n            dp[i, j] = dp[i - 1, j - 1] + 1;\n            if (dp[i, j] > best) best = dp[i, j];\n        }\n    }\n}\nint result = best;",
    "c": "int n = (int) strlen(s), m = (int) strlen(t);\nint **dp = (int **)malloc(sizeof(int *) * (size_t)(n + 1));\nfor (int i = 0; i <= n; i++) dp[i] = (int *)calloc((size_t)(m + 1), sizeof(int));\nint best = 0;\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        if (s[i - 1] == t[j - 1]) {\n            dp[i][j] = dp[i - 1][j - 1] + 1;\n            if (dp[i][j] > best) best = dp[i][j];\n        }\n    }\n}\nint result = best;",
    "rust": "let sc: Vec<char> = s.chars().collect();\nlet tc: Vec<char> = t.chars().collect();\nlet n = sc.len();\nlet m = tc.len();\nlet mut dp = vec![vec![0i32; m + 1]; n + 1];\nlet mut best = 0;\nfor i in 1..=n {\n    for j in 1..=m {\n        if sc[i - 1] == tc[j - 1] {\n            dp[i][j] = dp[i - 1][j - 1] + 1;\n            if dp[i][j] > best { best = dp[i][j]; }\n        }\n    }\n}\nlet result: i32 = best;",
    "swift": "let sc = Array(s)\nlet tc = Array(t)\nlet n = sc.count\nlet m = tc.count\nvar dp = Array(repeating: Array(repeating: 0, count: m + 1), count: n + 1)\nvar best = 0\nif n > 0 && m > 0 {\n    for i in 1...n {\n        for j in 1...m {\n            if sc[i - 1] == tc[j - 1] {\n                dp[i][j] = dp[i - 1][j - 1] + 1\n                if dp[i][j] > best { best = dp[i][j] }\n            }\n        }\n    }\n}\nlet result = best",
})

# ═════════════════════════════════════════════════════════════════════════
# min_window_length(s, t) -> int, minimum window substring length (0 if
# no valid window). Sliding window O(n).
# ═════════════════════════════════════════════════════════════════════════
add("minimum-window-substring-length", "str2", "min_window_length", "int", {
    "go": "need := make(map[byte]int)\nfor i := 0; i < len(t); i++ { need[t[i]]++ }\nrequired := len(need)\nformed := 0\nwindowCounts := make(map[byte]int)\nl := 0\nbest := 1 << 30\nfor r := 0; r < len(s); r++ {\n\tc := s[r]\n\twindowCounts[c]++\n\tif cnt, ok := need[c]; ok && windowCounts[c] == cnt { formed++ }\n\tfor l <= r && formed == required {\n\t\tif r-l+1 < best { best = r - l + 1 }\n\t\tlc := s[l]\n\t\twindowCounts[lc]--\n\t\tif cnt, ok := need[lc]; ok && windowCounts[lc] < cnt { formed-- }\n\t\tl++\n\t}\n}\nif best == 1<<30 { best = 0 }\nresult := int64(best)",
    "ruby": "need = Hash.new(0)\nt.each_char { |c| need[c] += 1 }\nrequired = need.size\nformed = 0\nwindow_counts = Hash.new(0)\nl = 0\nbest = 1 << 30\ns.each_char.with_index do |c, r|\n  window_counts[c] += 1\n  formed += 1 if need.key?(c) && window_counts[c] == need[c]\n  while l <= r && formed == required\n    best = [best, r - l + 1].min\n    lc = s[l]\n    window_counts[lc] -= 1\n    formed -= 1 if need.key?(lc) && window_counts[lc] < need[lc]\n    l += 1\n  end\nend\nbest = 0 if best == (1 << 30)\nresult = best",
    "kotlin": "val need = HashMap<Char, Int>()\nfor (c in t) need[c] = (need[c] ?: 0) + 1\nval required = need.size\nvar formed = 0\nval windowCounts = HashMap<Char, Int>()\nvar l = 0\nvar best = Int.MAX_VALUE\nfor (r in s.indices) {\n    val c = s[r]\n    windowCounts[c] = (windowCounts[c] ?: 0) + 1\n    if (need.containsKey(c) && windowCounts[c] == need[c]) formed++\n    while (l <= r && formed == required) {\n        if (r - l + 1 < best) best = r - l + 1\n        val lc = s[l]\n        windowCounts[lc] = windowCounts[lc]!! - 1\n        if (need.containsKey(lc) && windowCounts[lc]!! < need[lc]!!) formed--\n        l++\n    }\n}\nif (best == Int.MAX_VALUE) best = 0\nval result = best.toLong()",
    "php": "$need = [];\nfor ($i = 0; $i < strlen($t); $i++) { $need[$t[$i]] = ($need[$t[$i]] ?? 0) + 1; }\n$required = count($need);\n$formed = 0;\n$windowCounts = [];\n$l = 0;\n$best = PHP_INT_MAX;\nfor ($r = 0; $r < strlen($s); $r++) {\n    $c = $s[$r];\n    $windowCounts[$c] = ($windowCounts[$c] ?? 0) + 1;\n    if (isset($need[$c]) && $windowCounts[$c] == $need[$c]) { $formed++; }\n    while ($l <= $r && $formed == $required) {\n        if ($r - $l + 1 < $best) { $best = $r - $l + 1; }\n        $lc = $s[$l];\n        $windowCounts[$lc]--;\n        if (isset($need[$lc]) && $windowCounts[$lc] < $need[$lc]) { $formed--; }\n        $l++;\n    }\n}\nif ($best == PHP_INT_MAX) { $best = 0; }\n$result = $best;",
    "scala": "val need = scala.collection.mutable.HashMap[Char, Int]().withDefaultValue(0)\nfor (c <- t) need(c) += 1\nval required = need.size\nvar formed = 0\nval windowCounts = scala.collection.mutable.HashMap[Char, Int]().withDefaultValue(0)\nvar l = 0\nvar best = Int.MaxValue\nfor (r <- s.indices) {\n  val c = s(r)\n  windowCounts(c) += 1\n  if (need.contains(c) && windowCounts(c) == need(c)) formed += 1\n  while (l <= r && formed == required) {\n    if (r - l + 1 < best) best = r - l + 1\n    val lc = s(l)\n    windowCounts(lc) -= 1\n    if (need.contains(lc) && windowCounts(lc) < need(lc)) formed -= 1\n    l += 1\n  }\n}\nif (best == Int.MaxValue) best = 0\nval result: Long = best",
    "r": "sc <- strsplit(s, \"\")[[1]]\ntc <- strsplit(t, \"\")[[1]]\nneed <- new.env()\nfor (c in tc) { assign(c, (if (exists(c, envir = need)) get(c, envir = need) else 0) + 1, envir = need) }\nrequired <- length(ls(need))\nformed <- 0\nwc <- new.env()\ngetc <- function(env, k) if (exists(k, envir = env)) get(k, envir = env) else 0\nl <- 1\nbest <- .Machine$integer.max\nn <- length(sc)\nif (n > 0) { for (r in 1:n) {\n  c <- sc[r]\n  assign(c, getc(wc, c) + 1, envir = wc)\n  if (exists(c, envir = need) && getc(wc, c) == getc(need, c)) formed <- formed + 1\n  while (l <= r && formed == required) {\n    if (r - l + 1 < best) best <- r - l + 1\n    lc <- sc[l]\n    assign(lc, getc(wc, lc) - 1, envir = wc)\n    if (exists(lc, envir = need) && getc(wc, lc) < getc(need, lc)) formed <- formed - 1\n    l <- l + 1\n  }\n} }\nif (best == .Machine$integer.max) best <- 0\nresult <- best",
    "javascript": "const need = new Map();\nfor (const c of t) need.set(c, (need.get(c) || 0) + 1);\nconst required = need.size;\nlet formed = 0;\nconst windowCounts = new Map();\nlet l = 0;\nlet best = Infinity;\nfor (let r = 0; r < s.length; r++) {\n    const c = s[r];\n    windowCounts.set(c, (windowCounts.get(c) || 0) + 1);\n    if (need.has(c) && windowCounts.get(c) === need.get(c)) formed++;\n    while (l <= r && formed === required) {\n        if (r - l + 1 < best) best = r - l + 1;\n        const lc = s[l];\n        windowCounts.set(lc, windowCounts.get(lc) - 1);\n        if (need.has(lc) && windowCounts.get(lc) < need.get(lc)) formed--;\n        l++;\n    }\n}\nconst result = best === Infinity ? 0 : best;",
    "typescript": "const need = new Map<string, number>();\nfor (const c of t) need.set(c, (need.get(c) || 0) + 1);\nconst required = need.size;\nlet formed = 0;\nconst windowCounts = new Map<string, number>();\nlet l = 0;\nlet best = Infinity;\nfor (let r = 0; r < s.length; r++) {\n    const c = s[r];\n    windowCounts.set(c, (windowCounts.get(c) || 0) + 1);\n    if (need.has(c) && windowCounts.get(c) === need.get(c)) formed++;\n    while (l <= r && formed === required) {\n        if (r - l + 1 < best) best = r - l + 1;\n        const lc = s[l];\n        windowCounts.set(lc, windowCounts.get(lc)! - 1);\n        if (need.has(lc) && windowCounts.get(lc)! < need.get(lc)!) formed--;\n        l++;\n    }\n}\nconst result = best === Infinity ? 0 : best;",
    "perl": "my %need;\nforeach my $c (split //, $t) { $need{$c}++; }\nmy $required = scalar(keys %need);\nmy $formed = 0;\nmy %wc;\nmy $l = 0;\nmy $best = 2**31;\nmy @sc = split //, $s;\nfor (my $r = 0; $r < scalar(@sc); $r++) {\n    my $c = $sc[$r];\n    $wc{$c}++;\n    if (exists $need{$c} && $wc{$c} == $need{$c}) { $formed++; }\n    while ($l <= $r && $formed == $required) {\n        my $len = $r - $l + 1;\n        $best = $len if $len < $best;\n        my $lc = $sc[$l];\n        $wc{$lc}--;\n        if (exists $need{$lc} && $wc{$lc} < $need{$lc}) { $formed--; }\n        $l++;\n    }\n}\n$best = 0 if $best == 2**31;\nmy $result = $best;",
    "java": "java.util.Map<Character, Integer> need = new java.util.HashMap<>();\nfor (char c : t.toCharArray()) need.merge(c, 1, Integer::sum);\nint required = need.size();\nint formed = 0;\njava.util.Map<Character, Integer> windowCounts = new java.util.HashMap<>();\nint l = 0;\nint best = Integer.MAX_VALUE;\nfor (int r = 0; r < s.length(); r++) {\n    char c = s.charAt(r);\n    windowCounts.merge(c, 1, Integer::sum);\n    if (need.containsKey(c) && windowCounts.get(c).intValue() == need.get(c).intValue()) formed++;\n    while (l <= r && formed == required) {\n        if (r - l + 1 < best) best = r - l + 1;\n        char lc = s.charAt(l);\n        windowCounts.merge(lc, -1, Integer::sum);\n        if (need.containsKey(lc) && windowCounts.get(lc) < need.get(lc)) formed--;\n        l++;\n    }\n}\nint result = best == Integer.MAX_VALUE ? 0 : best;",
    "cpp": "std::unordered_map<char, int> need;\nfor (char c : t) need[c]++;\nint required = (int) need.size();\nint formed = 0;\nstd::unordered_map<char, int> windowCounts;\nint l = 0;\nint best = INT_MAX;\nfor (int r = 0; r < (int) s.size(); r++) {\n    char c = s[r];\n    windowCounts[c]++;\n    auto it = need.find(c);\n    if (it != need.end() && windowCounts[c] == it->second) formed++;\n    while (l <= r && formed == required) {\n        if (r - l + 1 < best) best = r - l + 1;\n        char lc = s[l];\n        windowCounts[lc]--;\n        auto it2 = need.find(lc);\n        if (it2 != need.end() && windowCounts[lc] < it2->second) formed--;\n        l++;\n    }\n}\nint result = best == INT_MAX ? 0 : best;",
    "csharp": "var need = new System.Collections.Generic.Dictionary<char, int>();\nforeach (char c in t) need[c] = need.ContainsKey(c) ? need[c] + 1 : 1;\nint required = need.Count;\nint formed = 0;\nvar windowCounts = new System.Collections.Generic.Dictionary<char, int>();\nint l = 0;\nint best = int.MaxValue;\nfor (int r = 0; r < s.Length; r++) {\n    char c = s[r];\n    windowCounts[c] = windowCounts.ContainsKey(c) ? windowCounts[c] + 1 : 1;\n    if (need.ContainsKey(c) && windowCounts[c] == need[c]) formed++;\n    while (l <= r && formed == required) {\n        if (r - l + 1 < best) best = r - l + 1;\n        char lc = s[l];\n        windowCounts[lc]--;\n        if (need.ContainsKey(lc) && windowCounts[lc] < need[lc]) formed--;\n        l++;\n    }\n}\nint result = best == int.MaxValue ? 0 : best;",
    "c": "int need[256] = {0};\nint present[256] = {0};\nint required = 0;\nfor (int i = 0; t[i]; i++) { if (!need[(unsigned char) t[i]]) { present[(unsigned char) t[i]] = 1; required++; } need[(unsigned char) t[i]]++; }\nint wc[256] = {0};\nint formed = 0;\nint l = 0;\nint best = 2000000000;\nint sn = (int) strlen(s);\nfor (int r = 0; r < sn; r++) {\n    unsigned char c = (unsigned char) s[r];\n    wc[c]++;\n    if (present[c] && wc[c] == need[c]) formed++;\n    while (l <= r && formed == required) {\n        if (r - l + 1 < best) best = r - l + 1;\n        unsigned char lc = (unsigned char) s[l];\n        wc[lc]--;\n        if (present[lc] && wc[lc] < need[lc]) formed--;\n        l++;\n    }\n}\nint result = best == 2000000000 ? 0 : best;",
    "rust": "let mut need = std::collections::HashMap::new();\nfor c in t.chars() { *need.entry(c).or_insert(0) += 1; }\nlet required = need.len();\nlet mut formed = 0;\nlet mut window_counts = std::collections::HashMap::new();\nlet mut l: i32 = 0;\nlet mut best = i32::MAX;\nlet sc: Vec<char> = s.chars().collect();\nfor r in 0..sc.len() {\n    let c = sc[r];\n    let wc = window_counts.entry(c).or_insert(0);\n    *wc += 1;\n    if let Some(&needed) = need.get(&c) { if *wc == needed { formed += 1; } }\n    while l <= r as i32 && formed == required {\n        if r as i32 - l + 1 < best { best = r as i32 - l + 1; }\n        let lc = sc[l as usize];\n        let lwc = window_counts.get_mut(&lc).unwrap();\n        *lwc -= 1;\n        if let Some(&needed) = need.get(&lc) { if *lwc < needed { formed -= 1; } }\n        l += 1;\n    }\n}\nlet result: i32 = if best == i32::MAX { 0 } else { best };",
    "swift": "var need: [Character: Int] = [:]\nfor c in t { need[c, default: 0] += 1 }\nlet required = need.count\nvar formed = 0\nvar windowCounts: [Character: Int] = [:]\nvar l = 0\nvar best = Int.max\nlet sc = Array(s)\nfor r in 0..<sc.count {\n    let c = sc[r]\n    windowCounts[c, default: 0] += 1\n    if let needed = need[c], windowCounts[c] == needed { formed += 1 }\n    while l <= r && formed == required {\n        if r - l + 1 < best { best = r - l + 1 }\n        let lc = sc[l]\n        windowCounts[lc]! -= 1\n        if let needed = need[lc], windowCounts[lc]! < needed { formed -= 1 }\n        l += 1\n    }\n}\nlet result = best == Int.max ? 0 : best",
})

# ═════════════════════════════════════════════════════════════════════════
# length_of_longest_substring(s) -> int, longest substring w/o repeating
# chars, sliding window O(n)
# ═════════════════════════════════════════════════════════════════════════
add("longest-substring-without-repeating", "str1", "length_of_longest_substring", "int", {
    "go": "lastSeen := make(map[byte]int)\nbest := 0\nl := 0\nfor r := 0; r < len(s); r++ {\n\tc := s[r]\n\tif p, ok := lastSeen[c]; ok && p >= l { l = p + 1 }\n\tlastSeen[c] = r\n\tif r-l+1 > best { best = r - l + 1 }\n}\nresult := int64(best)",
    "ruby": "last_seen = {}\nbest = 0\nl = 0\ns.each_char.with_index do |c, r|\n  if last_seen.key?(c) && last_seen[c] >= l\n    l = last_seen[c] + 1\n  end\n  last_seen[c] = r\n  best = r - l + 1 if r - l + 1 > best\nend\nresult = best",
    "kotlin": "val lastSeen = HashMap<Char, Int>()\nvar best = 0\nvar l = 0\nfor (r in s.indices) {\n    val c = s[r]\n    if (lastSeen.containsKey(c) && lastSeen[c]!! >= l) l = lastSeen[c]!! + 1\n    lastSeen[c] = r\n    if (r - l + 1 > best) best = r - l + 1\n}\nval result = best.toLong()",
    "php": "$lastSeen = [];\n$best = 0;\n$l = 0;\nfor ($r = 0; $r < strlen($s); $r++) {\n    $c = $s[$r];\n    if (isset($lastSeen[$c]) && $lastSeen[$c] >= $l) { $l = $lastSeen[$c] + 1; }\n    $lastSeen[$c] = $r;\n    if ($r - $l + 1 > $best) { $best = $r - $l + 1; }\n}\n$result = $best;",
    "scala": "val lastSeen = scala.collection.mutable.HashMap[Char, Int]()\nvar best = 0\nvar l = 0\nfor (r <- s.indices) {\n  val c = s(r)\n  if (lastSeen.contains(c) && lastSeen(c) >= l) l = lastSeen(c) + 1\n  lastSeen(c) = r\n  if (r - l + 1 > best) best = r - l + 1\n}\nval result: Long = best",
    "r": "sc <- strsplit(s, \"\")[[1]]\nlastSeen <- new.env()\nbest <- 0\nl <- 1\nn <- length(sc)\nif (n > 0) { for (r in 1:n) {\n  c <- sc[r]\n  if (exists(c, envir = lastSeen)) { p <- get(c, envir = lastSeen); if (p >= l) l <- p + 1 }\n  assign(c, r, envir = lastSeen)\n  if (r - l + 1 > best) best <- r - l + 1\n} }\nresult <- best",
    "javascript": "const lastSeen = new Map();\nlet best = 0, l = 0;\nfor (let r = 0; r < s.length; r++) {\n    const c = s[r];\n    if (lastSeen.has(c) && lastSeen.get(c) >= l) l = lastSeen.get(c) + 1;\n    lastSeen.set(c, r);\n    if (r - l + 1 > best) best = r - l + 1;\n}\nconst result = best;",
    "typescript": "const lastSeen = new Map<string, number>();\nlet best = 0, l = 0;\nfor (let r = 0; r < s.length; r++) {\n    const c = s[r];\n    if (lastSeen.has(c) && lastSeen.get(c)! >= l) l = lastSeen.get(c)! + 1;\n    lastSeen.set(c, r);\n    if (r - l + 1 > best) best = r - l + 1;\n}\nconst result = best;",
    "perl": "my %lastSeen;\nmy $best = 0;\nmy $l = 0;\nmy @sc = split //, $s;\nfor (my $r = 0; $r < scalar(@sc); $r++) {\n    my $c = $sc[$r];\n    if (exists $lastSeen{$c} && $lastSeen{$c} >= $l) { $l = $lastSeen{$c} + 1; }\n    $lastSeen{$c} = $r;\n    my $len = $r - $l + 1;\n    $best = $len if $len > $best;\n}\nmy $result = $best;",
    "java": "java.util.Map<Character, Integer> lastSeen = new java.util.HashMap<>();\nint best = 0, l = 0;\nfor (int r = 0; r < s.length(); r++) {\n    char c = s.charAt(r);\n    if (lastSeen.containsKey(c) && lastSeen.get(c) >= l) l = lastSeen.get(c) + 1;\n    lastSeen.put(c, r);\n    if (r - l + 1 > best) best = r - l + 1;\n}\nint result = best;",
    "cpp": "std::unordered_map<char, int> lastSeen;\nint best = 0, l = 0;\nfor (int r = 0; r < (int) s.size(); r++) {\n    char c = s[r];\n    auto it = lastSeen.find(c);\n    if (it != lastSeen.end() && it->second >= l) l = it->second + 1;\n    lastSeen[c] = r;\n    if (r - l + 1 > best) best = r - l + 1;\n}\nint result = best;",
    "csharp": "var lastSeen = new System.Collections.Generic.Dictionary<char, int>();\nint best = 0, l = 0;\nfor (int r = 0; r < s.Length; r++) {\n    char c = s[r];\n    if (lastSeen.ContainsKey(c) && lastSeen[c] >= l) l = lastSeen[c] + 1;\n    lastSeen[c] = r;\n    if (r - l + 1 > best) best = r - l + 1;\n}\nint result = best;",
    "c": "int lastSeen[256];\nfor (int i = 0; i < 256; i++) lastSeen[i] = -1;\nint best = 0, l = 0;\nint n = (int) strlen(s);\nfor (int r = 0; r < n; r++) {\n    unsigned char c = (unsigned char) s[r];\n    if (lastSeen[c] >= l) l = lastSeen[c] + 1;\n    lastSeen[c] = r;\n    if (r - l + 1 > best) best = r - l + 1;\n}\nint result = best;",
    "rust": "let mut lastSeen = std::collections::HashMap::new();\nlet mut best: i32 = 0;\nlet mut l: i32 = 0;\nlet sc: Vec<char> = s.chars().collect();\nfor r in 0..sc.len() {\n    let c = sc[r];\n    if let Some(&p) = lastSeen.get(&c) { if p >= l { l = p + 1; } }\n    lastSeen.insert(c, r as i32);\n    if r as i32 - l + 1 > best { best = r as i32 - l + 1; }\n}\nlet result: i32 = best;",
    "swift": "var lastSeen: [Character: Int] = [:]\nvar best = 0\nvar l = 0\nlet sc = Array(s)\nfor r in 0..<sc.count {\n    let c = sc[r]\n    if let p = lastSeen[c], p >= l { l = p + 1 }\n    lastSeen[c] = r\n    if r - l + 1 > best { best = r - l + 1 }\n}\nlet result = best",
})

# ═════════════════════════════════════════════════════════════════════════
# character_replacement(s, extra=k) -> int, longest substring achievable
# via <=k character replacements (sliding window + max-frequency tracking)
# ═════════════════════════════════════════════════════════════════════════
add("longest-repeating-char-replacement", "str1_int", "character_replacement", "int", {
    "go": "counts := make(map[byte]int)\nl := 0\nmaxFreq := 0\nbest := 0\nfor r := 0; r < len(s); r++ {\n\tc := s[r]\n\tcounts[c]++\n\tif counts[c] > maxFreq { maxFreq = counts[c] }\n\tfor (r-l+1)-maxFreq > extra {\n\t\tlc := s[l]\n\t\tcounts[lc]--\n\t\tl++\n\t}\n\tif r-l+1 > best { best = r - l + 1 }\n}\nresult := int64(best)",
    "ruby": "counts = Hash.new(0)\nl = 0\nmax_freq = 0\nbest = 0\ns.each_char.with_index do |c, r|\n  counts[c] += 1\n  max_freq = counts[c] if counts[c] > max_freq\n  while (r - l + 1) - max_freq > extra\n    counts[s[l]] -= 1\n    l += 1\n  end\n  best = r - l + 1 if r - l + 1 > best\nend\nresult = best",
    "kotlin": "val counts = HashMap<Char, Int>()\nvar l = 0\nvar maxFreq = 0\nvar best = 0\nfor (r in s.indices) {\n    val c = s[r]\n    counts[c] = (counts[c] ?: 0) + 1\n    if (counts[c]!! > maxFreq) maxFreq = counts[c]!!\n    while ((r - l + 1) - maxFreq > extra) {\n        val lc = s[l]\n        counts[lc] = counts[lc]!! - 1\n        l++\n    }\n    if (r - l + 1 > best) best = r - l + 1\n}\nval result = best.toLong()",
    "php": "$counts = [];\n$l = 0;\n$maxFreq = 0;\n$best = 0;\nfor ($r = 0; $r < strlen($s); $r++) {\n    $c = $s[$r];\n    $counts[$c] = ($counts[$c] ?? 0) + 1;\n    if ($counts[$c] > $maxFreq) { $maxFreq = $counts[$c]; }\n    while (($r - $l + 1) - $maxFreq > $extra) {\n        $lc = $s[$l];\n        $counts[$lc]--;\n        $l++;\n    }\n    if ($r - $l + 1 > $best) { $best = $r - $l + 1; }\n}\n$result = $best;",
    "scala": "val counts = scala.collection.mutable.HashMap[Char, Int]().withDefaultValue(0)\nvar l = 0\nvar maxFreq = 0\nvar best = 0\nfor (r <- s.indices) {\n  val c = s(r)\n  counts(c) += 1\n  if (counts(c) > maxFreq) maxFreq = counts(c)\n  while ((r - l + 1) - maxFreq > extra) {\n    counts(s(l)) -= 1\n    l += 1\n  }\n  if (r - l + 1 > best) best = r - l + 1\n}\nval result: Long = best",
    "r": "sc <- strsplit(s, \"\")[[1]]\ncounts <- new.env()\ngetc <- function(env, k) if (exists(k, envir = env)) get(k, envir = env) else 0\nl <- 1\nmaxFreq <- 0\nbest <- 0\nn <- length(sc)\nif (n > 0) { for (r in 1:n) {\n  c <- sc[r]\n  v <- getc(counts, c) + 1\n  assign(c, v, envir = counts)\n  if (v > maxFreq) maxFreq <- v\n  while ((r - l + 1) - maxFreq > extra) {\n    lc <- sc[l]\n    assign(lc, getc(counts, lc) - 1, envir = counts)\n    l <- l + 1\n  }\n  if (r - l + 1 > best) best <- r - l + 1\n} }\nresult <- best",
    "javascript": "const counts = new Map();\nlet l = 0, maxFreq = 0, best = 0;\nfor (let r = 0; r < s.length; r++) {\n    const c = s[r];\n    counts.set(c, (counts.get(c) || 0) + 1);\n    if (counts.get(c) > maxFreq) maxFreq = counts.get(c);\n    while ((r - l + 1) - maxFreq > extra) {\n        counts.set(s[l], counts.get(s[l]) - 1);\n        l++;\n    }\n    if (r - l + 1 > best) best = r - l + 1;\n}\nconst result = best;",
    "typescript": "const counts = new Map<string, number>();\nlet l = 0, maxFreq = 0, best = 0;\nfor (let r = 0; r < s.length; r++) {\n    const c = s[r];\n    counts.set(c, (counts.get(c) || 0) + 1);\n    if (counts.get(c)! > maxFreq) maxFreq = counts.get(c)!;\n    while ((r - l + 1) - maxFreq > extra) {\n        counts.set(s[l], counts.get(s[l])! - 1);\n        l++;\n    }\n    if (r - l + 1 > best) best = r - l + 1;\n}\nconst result = best;",
    "perl": "my %counts;\nmy $l = 0;\nmy $maxFreq = 0;\nmy $best = 0;\nmy @sc = split //, $s;\nfor (my $r = 0; $r < scalar(@sc); $r++) {\n    my $c = $sc[$r];\n    $counts{$c}++;\n    $maxFreq = $counts{$c} if $counts{$c} > $maxFreq;\n    while (($r - $l + 1) - $maxFreq > $extra) {\n        $counts{$sc[$l]}--;\n        $l++;\n    }\n    my $len = $r - $l + 1;\n    $best = $len if $len > $best;\n}\nmy $result = $best;",
    "java": "java.util.Map<Character, Integer> counts = new java.util.HashMap<>();\nint l = 0, maxFreq = 0, best = 0;\nfor (int r = 0; r < s.length(); r++) {\n    char c = s.charAt(r);\n    counts.merge(c, 1, Integer::sum);\n    if (counts.get(c) > maxFreq) maxFreq = counts.get(c);\n    while ((r - l + 1) - maxFreq > extra) {\n        counts.merge(s.charAt(l), -1, Integer::sum);\n        l++;\n    }\n    if (r - l + 1 > best) best = r - l + 1;\n}\nint result = best;",
    "cpp": "std::unordered_map<char, int> counts;\nint l = 0, maxFreq = 0, best = 0;\nfor (int r = 0; r < (int) s.size(); r++) {\n    char c = s[r];\n    counts[c]++;\n    if (counts[c] > maxFreq) maxFreq = counts[c];\n    while ((r - l + 1) - maxFreq > extra) {\n        counts[s[l]]--;\n        l++;\n    }\n    if (r - l + 1 > best) best = r - l + 1;\n}\nint result = best;",
    "csharp": "var counts = new System.Collections.Generic.Dictionary<char, int>();\nint l = 0, maxFreq = 0, best = 0;\nfor (int r = 0; r < s.Length; r++) {\n    char c = s[r];\n    counts[c] = counts.ContainsKey(c) ? counts[c] + 1 : 1;\n    if (counts[c] > maxFreq) maxFreq = counts[c];\n    while ((r - l + 1) - maxFreq > extra) {\n        counts[s[l]]--;\n        l++;\n    }\n    if (r - l + 1 > best) best = r - l + 1;\n}\nint result = best;",
    "c": "int counts[256] = {0};\nint l = 0, maxFreq = 0, best = 0;\nint n = (int) strlen(s);\nfor (int r = 0; r < n; r++) {\n    unsigned char c = (unsigned char) s[r];\n    counts[c]++;\n    if (counts[c] > maxFreq) maxFreq = counts[c];\n    while ((r - l + 1) - maxFreq > extra) {\n        counts[(unsigned char) s[l]]--;\n        l++;\n    }\n    if (r - l + 1 > best) best = r - l + 1;\n}\nint result = best;",
    "rust": "let mut counts = std::collections::HashMap::new();\nlet mut l: i32 = 0;\nlet mut max_freq = 0;\nlet mut best = 0;\nlet sc: Vec<char> = s.chars().collect();\nfor r in 0..sc.len() {\n    let c = sc[r];\n    let cnt = counts.entry(c).or_insert(0);\n    *cnt += 1;\n    if *cnt > max_freq { max_freq = *cnt; }\n    while (r as i32 - l + 1) - max_freq > extra {\n        *counts.get_mut(&sc[l as usize]).unwrap() -= 1;\n        l += 1;\n    }\n    if r as i32 - l + 1 > best { best = r as i32 - l + 1; }\n}\nlet result: i32 = best;",
    "swift": "var counts: [Character: Int] = [:]\nvar l = 0\nvar maxFreq = 0\nvar best = 0\nlet sc = Array(s)\nfor r in 0..<sc.count {\n    let c = sc[r]\n    counts[c, default: 0] += 1\n    if counts[c]! > maxFreq { maxFreq = counts[c]! }\n    while (r - l + 1) - maxFreq > extra {\n        counts[sc[l]]! -= 1\n        l += 1\n    }\n    if r - l + 1 > best { best = r - l + 1 }\n}\nlet result = best",
})

# ═════════════════════════════════════════════════════════════════════════
# longest_k_distinct(s, extra=k) -> int, longest substring with at most k
# distinct characters (sliding window)
# ═════════════════════════════════════════════════════════════════════════
add("longest-substring-at-most-k-distinct", "str1_int", "longest_k_distinct", "int", {
    "go": "counts := make(map[byte]int)\nl := 0\nbest := 0\nfor r := 0; r < len(s); r++ {\n\tc := s[r]\n\tcounts[c]++\n\tfor len(counts) > extra {\n\t\tlc := s[l]\n\t\tcounts[lc]--\n\t\tif counts[lc] == 0 { delete(counts, lc) }\n\t\tl++\n\t}\n\tif r-l+1 > best { best = r - l + 1 }\n}\nresult := int64(best)",
    "ruby": "counts = Hash.new(0)\nl = 0\nbest = 0\ns.each_char.with_index do |c, r|\n  counts[c] += 1\n  while counts.size > extra\n    lc = s[l]\n    counts[lc] -= 1\n    counts.delete(lc) if counts[lc] == 0\n    l += 1\n  end\n  best = r - l + 1 if r - l + 1 > best\nend\nresult = best",
    "kotlin": "val counts = HashMap<Char, Int>()\nvar l = 0\nvar best = 0\nfor (r in s.indices) {\n    val c = s[r]\n    counts[c] = (counts[c] ?: 0) + 1\n    while (counts.size > extra) {\n        val lc = s[l]\n        counts[lc] = counts[lc]!! - 1\n        if (counts[lc] == 0) counts.remove(lc)\n        l++\n    }\n    if (r - l + 1 > best) best = r - l + 1\n}\nval result = best.toLong()",
    "php": "$counts = [];\n$l = 0;\n$best = 0;\nfor ($r = 0; $r < strlen($s); $r++) {\n    $c = $s[$r];\n    $counts[$c] = ($counts[$c] ?? 0) + 1;\n    while (count($counts) > $extra) {\n        $lc = $s[$l];\n        $counts[$lc]--;\n        if ($counts[$lc] == 0) { unset($counts[$lc]); }\n        $l++;\n    }\n    if ($r - $l + 1 > $best) { $best = $r - $l + 1; }\n}\n$result = $best;",
    "scala": "val counts = scala.collection.mutable.HashMap[Char, Int]()\nvar l = 0\nvar best = 0\nfor (r <- s.indices) {\n  val c = s(r)\n  counts(c) = counts.getOrElse(c, 0) + 1\n  while (counts.size > extra) {\n    val lc = s(l)\n    counts(lc) -= 1\n    if (counts(lc) == 0) counts.remove(lc)\n    l += 1\n  }\n  if (r - l + 1 > best) best = r - l + 1\n}\nval result: Long = best",
    "r": "sc <- strsplit(s, \"\")[[1]]\ncounts <- new.env()\ngetc <- function(env, k) if (exists(k, envir = env)) get(k, envir = env) else 0\nl <- 1\nbest <- 0\nn <- length(sc)\nif (n > 0) { for (r in 1:n) {\n  c <- sc[r]\n  assign(c, getc(counts, c) + 1, envir = counts)\n  while (length(ls(counts)) > extra) {\n    lc <- sc[l]\n    v <- getc(counts, lc) - 1\n    if (v == 0) { rm(list = lc, envir = counts) } else { assign(lc, v, envir = counts) }\n    l <- l + 1\n  }\n  if (r - l + 1 > best) best <- r - l + 1\n} }\nresult <- best",
    "javascript": "const counts = new Map();\nlet l = 0, best = 0;\nfor (let r = 0; r < s.length; r++) {\n    const c = s[r];\n    counts.set(c, (counts.get(c) || 0) + 1);\n    while (counts.size > extra) {\n        const lc = s[l];\n        counts.set(lc, counts.get(lc) - 1);\n        if (counts.get(lc) === 0) counts.delete(lc);\n        l++;\n    }\n    if (r - l + 1 > best) best = r - l + 1;\n}\nconst result = best;",
    "typescript": "const counts = new Map<string, number>();\nlet l = 0, best = 0;\nfor (let r = 0; r < s.length; r++) {\n    const c = s[r];\n    counts.set(c, (counts.get(c) || 0) + 1);\n    while (counts.size > extra) {\n        const lc = s[l];\n        counts.set(lc, counts.get(lc)! - 1);\n        if (counts.get(lc) === 0) counts.delete(lc);\n        l++;\n    }\n    if (r - l + 1 > best) best = r - l + 1;\n}\nconst result = best;",
    "perl": "my %counts;\nmy $l = 0;\nmy $best = 0;\nmy @sc = split //, $s;\nfor (my $r = 0; $r < scalar(@sc); $r++) {\n    my $c = $sc[$r];\n    $counts{$c}++;\n    while (scalar(keys %counts) > $extra) {\n        my $lc = $sc[$l];\n        $counts{$lc}--;\n        delete $counts{$lc} if $counts{$lc} == 0;\n        $l++;\n    }\n    my $len = $r - $l + 1;\n    $best = $len if $len > $best;\n}\nmy $result = $best;",
    "java": "java.util.Map<Character, Integer> counts = new java.util.HashMap<>();\nint l = 0, best = 0;\nfor (int r = 0; r < s.length(); r++) {\n    char c = s.charAt(r);\n    counts.merge(c, 1, Integer::sum);\n    while (counts.size() > extra) {\n        char lc = s.charAt(l);\n        int v = counts.get(lc) - 1;\n        if (v == 0) counts.remove(lc); else counts.put(lc, v);\n        l++;\n    }\n    if (r - l + 1 > best) best = r - l + 1;\n}\nint result = best;",
    "cpp": "std::unordered_map<char, int> counts;\nint l = 0, best = 0;\nfor (int r = 0; r < (int) s.size(); r++) {\n    char c = s[r];\n    counts[c]++;\n    while ((int) counts.size() > extra) {\n        char lc = s[l];\n        counts[lc]--;\n        if (counts[lc] == 0) counts.erase(lc);\n        l++;\n    }\n    if (r - l + 1 > best) best = r - l + 1;\n}\nint result = best;",
    "csharp": "var counts = new System.Collections.Generic.Dictionary<char, int>();\nint l = 0, best = 0;\nfor (int r = 0; r < s.Length; r++) {\n    char c = s[r];\n    counts[c] = counts.ContainsKey(c) ? counts[c] + 1 : 1;\n    while (counts.Count > extra) {\n        char lc = s[l];\n        counts[lc]--;\n        if (counts[lc] == 0) counts.Remove(lc);\n        l++;\n    }\n    if (r - l + 1 > best) best = r - l + 1;\n}\nint result = best;",
    "c": "int counts[256] = {0};\nint distinct = 0;\nint l = 0, best = 0;\nint n = (int) strlen(s);\nfor (int r = 0; r < n; r++) {\n    unsigned char c = (unsigned char) s[r];\n    if (counts[c] == 0) distinct++;\n    counts[c]++;\n    while (distinct > extra) {\n        unsigned char lc = (unsigned char) s[l];\n        counts[lc]--;\n        if (counts[lc] == 0) distinct--;\n        l++;\n    }\n    if (r - l + 1 > best) best = r - l + 1;\n}\nint result = best;",
    "rust": "let mut counts = std::collections::HashMap::new();\nlet mut l: i32 = 0;\nlet mut best = 0;\nlet sc: Vec<char> = s.chars().collect();\nfor r in 0..sc.len() {\n    let c = sc[r];\n    *counts.entry(c).or_insert(0) += 1;\n    while counts.len() as i32 > extra {\n        let lc = sc[l as usize];\n        let v = counts.get_mut(&lc).unwrap();\n        *v -= 1;\n        if *v == 0 { counts.remove(&lc); }\n        l += 1;\n    }\n    if r as i32 - l + 1 > best { best = r as i32 - l + 1; }\n}\nlet result: i32 = best;",
    "swift": "var counts: [Character: Int] = [:]\nvar l = 0\nvar best = 0\nlet sc = Array(s)\nfor r in 0..<sc.count {\n    let c = sc[r]\n    counts[c, default: 0] += 1\n    while counts.count > extra {\n        let lc = sc[l]\n        counts[lc]! -= 1\n        if counts[lc] == 0 { counts.removeValue(forKey: lc) }\n        l += 1\n    }\n    if r - l + 1 > best { best = r - l + 1 }\n}\nlet result = best",
})

# ═════════════════════════════════════════════════════════════════════════
# is_match(s, p) -> bool, regex with '.' and '*' (LeetCode 10 semantics)
# ═════════════════════════════════════════════════════════════════════════
add("regular-expression-matching", "str2", "is_match", "bool", {
    "go": "n, m := len(s), len(p)\ndp := make([][]bool, n+1)\nfor i := range dp { dp[i] = make([]bool, m+1) }\ndp[0][0] = true\nfor j := 1; j <= m; j++ { if p[j-1] == '*' && j >= 2 { dp[0][j] = dp[0][j-2] } }\nfor i := 1; i <= n; i++ {\n\tfor j := 1; j <= m; j++ {\n\t\tif p[j-1] == '.' || p[j-1] == s[i-1] {\n\t\t\tdp[i][j] = dp[i-1][j-1]\n\t\t} else if p[j-1] == '*' {\n\t\t\tdp[i][j] = dp[i][j-2]\n\t\t\tif p[j-2] == '.' || p[j-2] == s[i-1] { dp[i][j] = dp[i][j] || dp[i-1][j] }\n\t\t}\n\t}\n}\nresult := dp[n][m]",
    "ruby": "n = s.length\nm = p.length\ndp = Array.new(n + 1) { Array.new(m + 1, false) }\ndp[0][0] = true\n(1..m).each { |j| dp[0][j] = (p[j - 1] == '*' && j >= 2) ? dp[0][j - 2] : false }\n(1..n).each do |i|\n  (1..m).each do |j|\n    if p[j - 1] == '.' || p[j - 1] == s[i - 1]\n      dp[i][j] = dp[i - 1][j - 1]\n    elsif p[j - 1] == '*'\n      dp[i][j] = dp[i][j - 2]\n      if p[j - 2] == '.' || p[j - 2] == s[i - 1]\n        dp[i][j] ||= dp[i - 1][j]\n      end\n    end\n  end\nend\nresult = dp[n][m]",
    "kotlin": "val n = s.length\nval m = p.length\nval dp = Array(n + 1) { BooleanArray(m + 1) }\ndp[0][0] = true\nfor (j in 1..m) { if (p[j - 1] == '*' && j >= 2) dp[0][j] = dp[0][j - 2] }\nfor (i in 1..n) {\n    for (j in 1..m) {\n        if (p[j - 1] == '.' || p[j - 1] == s[i - 1]) {\n            dp[i][j] = dp[i - 1][j - 1]\n        } else if (p[j - 1] == '*') {\n            dp[i][j] = dp[i][j - 2]\n            if (p[j - 2] == '.' || p[j - 2] == s[i - 1]) dp[i][j] = dp[i][j] || dp[i - 1][j]\n        }\n    }\n}\nval result = dp[n][m]",
    "php": "$n = strlen($s); $m = strlen($p);\n$dp = array_fill(0, $n + 1, array_fill(0, $m + 1, false));\n$dp[0][0] = true;\nfor ($j = 1; $j <= $m; $j++) { if ($p[$j - 1] == '*' && $j >= 2) { $dp[0][$j] = $dp[0][$j - 2]; } }\nfor ($i = 1; $i <= $n; $i++) {\n    for ($j = 1; $j <= $m; $j++) {\n        if ($p[$j - 1] == '.' || $p[$j - 1] == $s[$i - 1]) {\n            $dp[$i][$j] = $dp[$i - 1][$j - 1];\n        } elseif ($p[$j - 1] == '*') {\n            $dp[$i][$j] = $dp[$i][$j - 2];\n            if ($p[$j - 2] == '.' || $p[$j - 2] == $s[$i - 1]) { $dp[$i][$j] = $dp[$i][$j] || $dp[$i - 1][$j]; }\n        }\n    }\n}\n$result = $dp[$n][$m];",
    "scala": "val n = s.length\nval m = p.length\nval dp = Array.ofDim[Boolean](n + 1, m + 1)\ndp(0)(0) = true\nfor (j <- 1 to m) { if (p(j - 1) == '*' && j >= 2) dp(0)(j) = dp(0)(j - 2) }\nfor (i <- 1 to n) {\n  for (j <- 1 to m) {\n    if (p(j - 1) == '.' || p(j - 1) == s(i - 1)) {\n      dp(i)(j) = dp(i - 1)(j - 1)\n    } else if (p(j - 1) == '*') {\n      dp(i)(j) = dp(i)(j - 2)\n      if (p(j - 2) == '.' || p(j - 2) == s(i - 1)) dp(i)(j) = dp(i)(j) || dp(i - 1)(j)\n    }\n  }\n}\nval result = dp(n)(m)",
    "r": "n <- nchar(s); m <- nchar(p)\nsc <- strsplit(s, \"\")[[1]]\npc <- strsplit(p, \"\")[[1]]\ndp <- matrix(FALSE, nrow = n + 1, ncol = m + 1)\ndp[1, 1] <- TRUE\nif (m > 0) { for (j in 1:m) { if (pc[j] == '*' && j >= 2) dp[1, j + 1] <- dp[1, j - 1] } }\nif (n > 0 && m > 0) {\n  for (i in 1:n) {\n    for (j in 1:m) {\n      if (pc[j] == '.' || pc[j] == sc[i]) {\n        dp[i + 1, j + 1] <- dp[i, j]\n      } else if (pc[j] == '*') {\n        dp[i + 1, j + 1] <- dp[i + 1, j - 1]\n        if (pc[j - 1] == '.' || pc[j - 1] == sc[i]) dp[i + 1, j + 1] <- dp[i + 1, j + 1] || dp[i, j + 1]\n      }\n    }\n  }\n}\nresult <- dp[n + 1, m + 1]",
    "javascript": "const n = s.length, m = p.length;\nconst dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(false));\ndp[0][0] = true;\nfor (let j = 1; j <= m; j++) { if (p[j - 1] === '*' && j >= 2) dp[0][j] = dp[0][j - 2]; }\nfor (let i = 1; i <= n; i++) {\n    for (let j = 1; j <= m; j++) {\n        if (p[j - 1] === '.' || p[j - 1] === s[i - 1]) {\n            dp[i][j] = dp[i - 1][j - 1];\n        } else if (p[j - 1] === '*') {\n            dp[i][j] = dp[i][j - 2];\n            if (p[j - 2] === '.' || p[j - 2] === s[i - 1]) dp[i][j] = dp[i][j] || dp[i - 1][j];\n        }\n    }\n}\nconst result = dp[n][m];",
    "typescript": "const n = s.length, m = p.length;\nconst dp: boolean[][] = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(false));\ndp[0][0] = true;\nfor (let j = 1; j <= m; j++) { if (p[j - 1] === '*' && j >= 2) dp[0][j] = dp[0][j - 2]; }\nfor (let i = 1; i <= n; i++) {\n    for (let j = 1; j <= m; j++) {\n        if (p[j - 1] === '.' || p[j - 1] === s[i - 1]) {\n            dp[i][j] = dp[i - 1][j - 1];\n        } else if (p[j - 1] === '*') {\n            dp[i][j] = dp[i][j - 2];\n            if (p[j - 2] === '.' || p[j - 2] === s[i - 1]) dp[i][j] = dp[i][j] || dp[i - 1][j];\n        }\n    }\n}\nconst result = dp[n][m];",
    "perl": "my $n = length($s); my $m = length($p);\nmy @dp;\nfor my $i (0..$n) { for my $j (0..$m) { $dp[$i][$j] = 0; } }\n$dp[0][0] = 1;\nfor my $j (1..$m) { if (substr($p, $j - 1, 1) eq '*' && $j >= 2) { $dp[0][$j] = $dp[0][$j - 2]; } }\nfor my $i (1..$n) {\n    for my $j (1..$m) {\n        my $pc = substr($p, $j - 1, 1);\n        my $sc = substr($s, $i - 1, 1);\n        if ($pc eq '.' || $pc eq $sc) {\n            $dp[$i][$j] = $dp[$i - 1][$j - 1];\n        } elsif ($pc eq '*') {\n            $dp[$i][$j] = $dp[$i][$j - 2];\n            my $pc2 = substr($p, $j - 2, 1);\n            if ($pc2 eq '.' || $pc2 eq $sc) { $dp[$i][$j] = $dp[$i][$j] || $dp[$i - 1][$j]; }\n        }\n    }\n}\nmy $result = $dp[$n][$m] ? 1 : 0;",
    "java": "int n = s.length(), m = p.length();\nboolean[][] dp = new boolean[n + 1][m + 1];\ndp[0][0] = true;\nfor (int j = 1; j <= m; j++) { if (p.charAt(j - 1) == '*' && j >= 2) dp[0][j] = dp[0][j - 2]; }\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        char pc = p.charAt(j - 1), sc = s.charAt(i - 1);\n        if (pc == '.' || pc == sc) {\n            dp[i][j] = dp[i - 1][j - 1];\n        } else if (pc == '*') {\n            dp[i][j] = dp[i][j - 2];\n            char pc2 = p.charAt(j - 2);\n            if (pc2 == '.' || pc2 == sc) dp[i][j] = dp[i][j] || dp[i - 1][j];\n        }\n    }\n}\nboolean result = dp[n][m];",
    "cpp": "int n = (int) s.size(), m = (int) p.size();\nstd::vector<std::vector<char>> dp(n + 1, std::vector<char>(m + 1, 0));\ndp[0][0] = 1;\nfor (int j = 1; j <= m; j++) { if (p[j - 1] == '*' && j >= 2) dp[0][j] = dp[0][j - 2]; }\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        char pc = p[j - 1], sc = s[i - 1];\n        if (pc == '.' || pc == sc) {\n            dp[i][j] = dp[i - 1][j - 1];\n        } else if (pc == '*') {\n            dp[i][j] = dp[i][j - 2];\n            char pc2 = p[j - 2];\n            if (pc2 == '.' || pc2 == sc) dp[i][j] = dp[i][j] || dp[i - 1][j];\n        }\n    }\n}\nbool result = dp[n][m] != 0;",
    "csharp": "int n = s.Length, m = p.Length;\nvar dp = new bool[n + 1, m + 1];\ndp[0, 0] = true;\nfor (int j = 1; j <= m; j++) { if (p[j - 1] == '*' && j >= 2) dp[0, j] = dp[0, j - 2]; }\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        char pc = p[j - 1], sc = s[i - 1];\n        if (pc == '.' || pc == sc) {\n            dp[i, j] = dp[i - 1, j - 1];\n        } else if (pc == '*') {\n            dp[i, j] = dp[i, j - 2];\n            char pc2 = p[j - 2];\n            if (pc2 == '.' || pc2 == sc) dp[i, j] = dp[i, j] || dp[i - 1, j];\n        }\n    }\n}\nbool result = dp[n, m];",
    "c": "int n = (int) strlen(s), m = (int) strlen(p);\nchar **dp = (char **)malloc(sizeof(char *) * (size_t)(n + 1));\nfor (int i = 0; i <= n; i++) dp[i] = (char *)calloc((size_t)(m + 1), 1);\ndp[0][0] = 1;\nfor (int j = 1; j <= m; j++) { if (p[j - 1] == '*' && j >= 2) dp[0][j] = dp[0][j - 2]; }\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        char pc = p[j - 1], sc = s[i - 1];\n        if (pc == '.' || pc == sc) {\n            dp[i][j] = dp[i - 1][j - 1];\n        } else if (pc == '*') {\n            dp[i][j] = dp[i][j - 2];\n            char pc2 = p[j - 2];\n            if ((pc2 == '.' || pc2 == sc) && dp[i - 1][j]) dp[i][j] = 1;\n        }\n    }\n}\nint result = dp[n][m];",
    "rust": "let sc: Vec<char> = s.chars().collect();\nlet pc: Vec<char> = p.chars().collect();\nlet n = sc.len();\nlet m = pc.len();\nlet mut dp = vec![vec![false; m + 1]; n + 1];\ndp[0][0] = true;\nfor j in 1..=m { if pc[j - 1] == '*' && j >= 2 { dp[0][j] = dp[0][j - 2]; } }\nfor i in 1..=n {\n    for j in 1..=m {\n        let pchar = pc[j - 1];\n        let schar = sc[i - 1];\n        if pchar == '.' || pchar == schar {\n            dp[i][j] = dp[i - 1][j - 1];\n        } else if pchar == '*' {\n            dp[i][j] = dp[i][j - 2];\n            let pchar2 = pc[j - 2];\n            if pchar2 == '.' || pchar2 == schar { dp[i][j] = dp[i][j] || dp[i - 1][j]; }\n        }\n    }\n}\nlet result: bool = dp[n][m];",
    "swift": "let sc = Array(s)\nlet pc = Array(p)\nlet n = sc.count\nlet m = pc.count\nvar dp = Array(repeating: Array(repeating: false, count: m + 1), count: n + 1)\ndp[0][0] = true\nif m > 0 {\n    for j in 1...m { if pc[j - 1] == \"*\" && j >= 2 { dp[0][j] = dp[0][j - 2] } }\n}\nif n > 0 && m > 0 {\n    for i in 1...n {\n        for j in 1...m {\n            let pchar = pc[j - 1]\n            let schar = sc[i - 1]\n            if pchar == \".\" || pchar == schar {\n                dp[i][j] = dp[i - 1][j - 1]\n            } else if pchar == \"*\" {\n                dp[i][j] = dp[i][j - 2]\n                let pchar2 = pc[j - 2]\n                if pchar2 == \".\" || pchar2 == schar { dp[i][j] = dp[i][j] || dp[i - 1][j] }\n            }\n        }\n    }\n}\nlet result = dp[n][m]",
})

# ═════════════════════════════════════════════════════════════════════════
# is_match(s, p) -> bool, wildcard with '?' and '*' (LeetCode 44 semantics)
# ═════════════════════════════════════════════════════════════════════════
add("wildcard-matching", "str2", "is_match", "bool", {
    "go": "n, m := len(s), len(p)\ndp := make([][]bool, n+1)\nfor i := range dp { dp[i] = make([]bool, m+1) }\ndp[0][0] = true\nfor j := 1; j <= m; j++ { if p[j-1] == '*' { dp[0][j] = dp[0][j-1] } }\nfor i := 1; i <= n; i++ {\n\tfor j := 1; j <= m; j++ {\n\t\tif p[j-1] == '?' || p[j-1] == s[i-1] {\n\t\t\tdp[i][j] = dp[i-1][j-1]\n\t\t} else if p[j-1] == '*' {\n\t\t\tdp[i][j] = dp[i-1][j] || dp[i][j-1]\n\t\t}\n\t}\n}\nresult := dp[n][m]",
    "ruby": "n = s.length\nm = p.length\ndp = Array.new(n + 1) { Array.new(m + 1, false) }\ndp[0][0] = true\n(1..m).each { |j| dp[0][j] = (p[j - 1] == '*') ? dp[0][j - 1] : false }\n(1..n).each do |i|\n  (1..m).each do |j|\n    if p[j - 1] == '?' || p[j - 1] == s[i - 1]\n      dp[i][j] = dp[i - 1][j - 1]\n    elsif p[j - 1] == '*'\n      dp[i][j] = dp[i - 1][j] || dp[i][j - 1]\n    end\n  end\nend\nresult = dp[n][m]",
    "kotlin": "val n = s.length\nval m = p.length\nval dp = Array(n + 1) { BooleanArray(m + 1) }\ndp[0][0] = true\nfor (j in 1..m) { if (p[j - 1] == '*') dp[0][j] = dp[0][j - 1] }\nfor (i in 1..n) {\n    for (j in 1..m) {\n        if (p[j - 1] == '?' || p[j - 1] == s[i - 1]) {\n            dp[i][j] = dp[i - 1][j - 1]\n        } else if (p[j - 1] == '*') {\n            dp[i][j] = dp[i - 1][j] || dp[i][j - 1]\n        }\n    }\n}\nval result = dp[n][m]",
    "php": "$n = strlen($s); $m = strlen($p);\n$dp = array_fill(0, $n + 1, array_fill(0, $m + 1, false));\n$dp[0][0] = true;\nfor ($j = 1; $j <= $m; $j++) { if ($p[$j - 1] == '*') { $dp[0][$j] = $dp[0][$j - 1]; } }\nfor ($i = 1; $i <= $n; $i++) {\n    for ($j = 1; $j <= $m; $j++) {\n        if ($p[$j - 1] == '?' || $p[$j - 1] == $s[$i - 1]) {\n            $dp[$i][$j] = $dp[$i - 1][$j - 1];\n        } elseif ($p[$j - 1] == '*') {\n            $dp[$i][$j] = $dp[$i - 1][$j] || $dp[$i][$j - 1];\n        }\n    }\n}\n$result = $dp[$n][$m];",
    "scala": "val n = s.length\nval m = p.length\nval dp = Array.ofDim[Boolean](n + 1, m + 1)\ndp(0)(0) = true\nfor (j <- 1 to m) { if (p(j - 1) == '*') dp(0)(j) = dp(0)(j - 1) }\nfor (i <- 1 to n) {\n  for (j <- 1 to m) {\n    if (p(j - 1) == '?' || p(j - 1) == s(i - 1)) {\n      dp(i)(j) = dp(i - 1)(j - 1)\n    } else if (p(j - 1) == '*') {\n      dp(i)(j) = dp(i - 1)(j) || dp(i)(j - 1)\n    }\n  }\n}\nval result = dp(n)(m)",
    "r": "n <- nchar(s); m <- nchar(p)\nsc <- strsplit(s, \"\")[[1]]\npc <- strsplit(p, \"\")[[1]]\ndp <- matrix(FALSE, nrow = n + 1, ncol = m + 1)\ndp[1, 1] <- TRUE\nif (m > 0) { for (j in 1:m) { if (pc[j] == '*') dp[1, j + 1] <- dp[1, j] } }\nif (n > 0 && m > 0) {\n  for (i in 1:n) {\n    for (j in 1:m) {\n      if (pc[j] == '?' || pc[j] == sc[i]) {\n        dp[i + 1, j + 1] <- dp[i, j]\n      } else if (pc[j] == '*') {\n        dp[i + 1, j + 1] <- dp[i, j + 1] || dp[i + 1, j]\n      }\n    }\n  }\n}\nresult <- dp[n + 1, m + 1]",
    "javascript": "const n = s.length, m = p.length;\nconst dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(false));\ndp[0][0] = true;\nfor (let j = 1; j <= m; j++) { if (p[j - 1] === '*') dp[0][j] = dp[0][j - 1]; }\nfor (let i = 1; i <= n; i++) {\n    for (let j = 1; j <= m; j++) {\n        if (p[j - 1] === '?' || p[j - 1] === s[i - 1]) {\n            dp[i][j] = dp[i - 1][j - 1];\n        } else if (p[j - 1] === '*') {\n            dp[i][j] = dp[i - 1][j] || dp[i][j - 1];\n        }\n    }\n}\nconst result = dp[n][m];",
    "typescript": "const n = s.length, m = p.length;\nconst dp: boolean[][] = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(false));\ndp[0][0] = true;\nfor (let j = 1; j <= m; j++) { if (p[j - 1] === '*') dp[0][j] = dp[0][j - 1]; }\nfor (let i = 1; i <= n; i++) {\n    for (let j = 1; j <= m; j++) {\n        if (p[j - 1] === '?' || p[j - 1] === s[i - 1]) {\n            dp[i][j] = dp[i - 1][j - 1];\n        } else if (p[j - 1] === '*') {\n            dp[i][j] = dp[i - 1][j] || dp[i][j - 1];\n        }\n    }\n}\nconst result = dp[n][m];",
    "perl": "my $n = length($s); my $m = length($p);\nmy @dp;\nfor my $i (0..$n) { for my $j (0..$m) { $dp[$i][$j] = 0; } }\n$dp[0][0] = 1;\nfor my $j (1..$m) { if (substr($p, $j - 1, 1) eq '*') { $dp[0][$j] = $dp[0][$j - 1]; } }\nfor my $i (1..$n) {\n    for my $j (1..$m) {\n        my $pc = substr($p, $j - 1, 1);\n        my $sc = substr($s, $i - 1, 1);\n        if ($pc eq '?' || $pc eq $sc) {\n            $dp[$i][$j] = $dp[$i - 1][$j - 1];\n        } elsif ($pc eq '*') {\n            $dp[$i][$j] = $dp[$i - 1][$j] || $dp[$i][$j - 1];\n        }\n    }\n}\nmy $result = $dp[$n][$m] ? 1 : 0;",
    "java": "int n = s.length(), m = p.length();\nboolean[][] dp = new boolean[n + 1][m + 1];\ndp[0][0] = true;\nfor (int j = 1; j <= m; j++) { if (p.charAt(j - 1) == '*') dp[0][j] = dp[0][j - 1]; }\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        char pc = p.charAt(j - 1), sc = s.charAt(i - 1);\n        if (pc == '?' || pc == sc) {\n            dp[i][j] = dp[i - 1][j - 1];\n        } else if (pc == '*') {\n            dp[i][j] = dp[i - 1][j] || dp[i][j - 1];\n        }\n    }\n}\nboolean result = dp[n][m];",
    "cpp": "int n = (int) s.size(), m = (int) p.size();\nstd::vector<std::vector<char>> dp(n + 1, std::vector<char>(m + 1, 0));\ndp[0][0] = 1;\nfor (int j = 1; j <= m; j++) { if (p[j - 1] == '*') dp[0][j] = dp[0][j - 1]; }\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        char pc = p[j - 1], sc = s[i - 1];\n        if (pc == '?' || pc == sc) {\n            dp[i][j] = dp[i - 1][j - 1];\n        } else if (pc == '*') {\n            dp[i][j] = dp[i - 1][j] || dp[i][j - 1];\n        }\n    }\n}\nbool result = dp[n][m] != 0;",
    "csharp": "int n = s.Length, m = p.Length;\nvar dp = new bool[n + 1, m + 1];\ndp[0, 0] = true;\nfor (int j = 1; j <= m; j++) { if (p[j - 1] == '*') dp[0, j] = dp[0, j - 1]; }\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        char pc = p[j - 1], sc = s[i - 1];\n        if (pc == '?' || pc == sc) {\n            dp[i, j] = dp[i - 1, j - 1];\n        } else if (pc == '*') {\n            dp[i, j] = dp[i - 1, j] || dp[i, j - 1];\n        }\n    }\n}\nbool result = dp[n, m];",
    "c": "int n = (int) strlen(s), m = (int) strlen(p);\nchar **dp = (char **)malloc(sizeof(char *) * (size_t)(n + 1));\nfor (int i = 0; i <= n; i++) dp[i] = (char *)calloc((size_t)(m + 1), 1);\ndp[0][0] = 1;\nfor (int j = 1; j <= m; j++) { if (p[j - 1] == '*') dp[0][j] = dp[0][j - 1]; }\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= m; j++) {\n        char pc = p[j - 1], sc = s[i - 1];\n        if (pc == '?' || pc == sc) {\n            dp[i][j] = dp[i - 1][j - 1];\n        } else if (pc == '*') {\n            dp[i][j] = dp[i - 1][j] || dp[i][j - 1];\n        }\n    }\n}\nint result = dp[n][m];",
    "rust": "let sc: Vec<char> = s.chars().collect();\nlet pc: Vec<char> = p.chars().collect();\nlet n = sc.len();\nlet m = pc.len();\nlet mut dp = vec![vec![false; m + 1]; n + 1];\ndp[0][0] = true;\nfor j in 1..=m { if pc[j - 1] == '*' { dp[0][j] = dp[0][j - 1]; } }\nfor i in 1..=n {\n    for j in 1..=m {\n        let pchar = pc[j - 1];\n        let schar = sc[i - 1];\n        if pchar == '?' || pchar == schar {\n            dp[i][j] = dp[i - 1][j - 1];\n        } else if pchar == '*' {\n            dp[i][j] = dp[i - 1][j] || dp[i][j - 1];\n        }\n    }\n}\nlet result: bool = dp[n][m];",
    "swift": "let sc = Array(s)\nlet pc = Array(p)\nlet n = sc.count\nlet m = pc.count\nvar dp = Array(repeating: Array(repeating: false, count: m + 1), count: n + 1)\ndp[0][0] = true\nif m > 0 {\n    for j in 1...m { if pc[j - 1] == \"*\" { dp[0][j] = dp[0][j - 1] } }\n}\nif n > 0 && m > 0 {\n    for i in 1...n {\n        for j in 1...m {\n            let pchar = pc[j - 1]\n            let schar = sc[i - 1]\n            if pchar == \"?\" || pchar == schar {\n                dp[i][j] = dp[i - 1][j - 1]\n            } else if pchar == \"*\" {\n                dp[i][j] = dp[i - 1][j] || dp[i][j - 1]\n            }\n        }\n    }\n}\nlet result = dp[n][m]",
})

# ═════════════════════════════════════════════════════════════════════════
# restore_ip_count(s) -> int, number of ways to split s into 4 valid
# octets (0-255, no leading zero unless "0" itself)
# ═════════════════════════════════════════════════════════════════════════
add("restore-ip-addresses-count", "str1", "restore_ip_count", "int", {
    "go": "n := len(s)\nvalid := func(seg string) bool {\n\tif len(seg) == 0 || len(seg) > 3 { return false }\n\tif len(seg) > 1 && seg[0] == '0' { return false }\n\tv, _ := strconv.Atoi(seg)\n\treturn v <= 255\n}\nresult := int64(0)\nfor l1 := 1; l1 <= 3; l1++ {\n\tfor l2 := 1; l2 <= 3; l2++ {\n\t\tfor l3 := 1; l3 <= 3; l3++ {\n\t\t\tl4 := n - l1 - l2 - l3\n\t\t\tif l4 < 1 || l4 > 3 { continue }\n\t\t\tif l1+l2+l3 > n { continue }\n\t\t\ta := s[0:l1]\n\t\t\tb := s[l1 : l1+l2]\n\t\t\tc := s[l1+l2 : l1+l2+l3]\n\t\t\td := s[l1+l2+l3:]\n\t\t\tif valid(a) && valid(b) && valid(c) && valid(d) { result++ }\n\t\t}\n\t}\n}",
    "ruby": "n = s.length\nvalid = lambda do |seg|\n  return false if seg.length == 0 || seg.length > 3\n  return false if seg.length > 1 && seg[0] == '0'\n  seg.to_i <= 255\nend\nresult = 0\n(1..3).each do |l1|\n  (1..3).each do |l2|\n    (1..3).each do |l3|\n      l4 = n - l1 - l2 - l3\n      next if l4 < 1 || l4 > 3\n      a = s[0, l1]\n      b = s[l1, l2]\n      c = s[l1 + l2, l3]\n      d = s[(l1 + l2 + l3)..]\n      result += 1 if valid.call(a) && valid.call(b) && valid.call(c) && valid.call(d)\n    end\n  end\nend",
    "kotlin": "val n = s.length\nfun valid(seg: String): Boolean {\n    if (seg.isEmpty() || seg.length > 3) return false\n    if (seg.length > 1 && seg[0] == '0') return false\n    return seg.toInt() <= 255\n}\nvar result = 0L\nfor (l1 in 1..3) {\n    for (l2 in 1..3) {\n        for (l3 in 1..3) {\n            val l4 = n - l1 - l2 - l3\n            if (l4 < 1 || l4 > 3) continue\n            if (l1 + l2 + l3 > n) continue\n            val a = s.substring(0, l1)\n            val b = s.substring(l1, l1 + l2)\n            val c = s.substring(l1 + l2, l1 + l2 + l3)\n            val d = s.substring(l1 + l2 + l3)\n            if (valid(a) && valid(b) && valid(c) && valid(d)) result++\n        }\n    }\n}",
    "php": "$n = strlen($s);\n$valid = function($seg) {\n    if (strlen($seg) == 0 || strlen($seg) > 3) return false;\n    if (strlen($seg) > 1 && $seg[0] == '0') return false;\n    return intval($seg) <= 255;\n};\n$result = 0;\nfor ($l1 = 1; $l1 <= 3; $l1++) {\n    for ($l2 = 1; $l2 <= 3; $l2++) {\n        for ($l3 = 1; $l3 <= 3; $l3++) {\n            $l4 = $n - $l1 - $l2 - $l3;\n            if ($l4 < 1 || $l4 > 3) { continue; }\n            if ($l1 + $l2 + $l3 > $n) { continue; }\n            $a = substr($s, 0, $l1);\n            $b = substr($s, $l1, $l2);\n            $c = substr($s, $l1 + $l2, $l3);\n            $d = substr($s, $l1 + $l2 + $l3);\n            if ($valid($a) && $valid($b) && $valid($c) && $valid($d)) { $result++; }\n        }\n    }\n}",
    "scala": "val n = s.length\ndef valid(seg: String): Boolean = {\n  if (seg.isEmpty || seg.length > 3) return false\n  if (seg.length > 1 && seg(0) == '0') return false\n  seg.toInt <= 255\n}\nvar result: Long = 0L\nfor (l1 <- 1 to 3; l2 <- 1 to 3; l3 <- 1 to 3) {\n  val l4 = n - l1 - l2 - l3\n  if (l4 >= 1 && l4 <= 3 && l1 + l2 + l3 <= n) {\n    val a = s.substring(0, l1)\n    val b = s.substring(l1, l1 + l2)\n    val c = s.substring(l1 + l2, l1 + l2 + l3)\n    val d = s.substring(l1 + l2 + l3)\n    if (valid(a) && valid(b) && valid(c) && valid(d)) result += 1\n  }\n}",
    "r": "n <- nchar(s)\nvalidSeg <- function(seg) {\n  if (nchar(seg) == 0 || nchar(seg) > 3) return(FALSE)\n  if (nchar(seg) > 1 && substr(seg, 1, 1) == '0') return(FALSE)\n  as.integer(seg) <= 255\n}\nresult <- 0\nfor (l1 in 1:3) {\n  for (l2 in 1:3) {\n    for (l3 in 1:3) {\n      l4 <- n - l1 - l2 - l3\n      if (l4 >= 1 && l4 <= 3 && (l1 + l2 + l3) <= n) {\n        a <- substr(s, 1, l1)\n        b <- substr(s, l1 + 1, l1 + l2)\n        cc <- substr(s, l1 + l2 + 1, l1 + l2 + l3)\n        d <- substr(s, l1 + l2 + l3 + 1, n)\n        if (validSeg(a) && validSeg(b) && validSeg(cc) && validSeg(d)) result <- result + 1\n      }\n    }\n  }\n}",
    "javascript": "const n = s.length;\nfunction valid(seg) {\n    if (seg.length === 0 || seg.length > 3) return false;\n    if (seg.length > 1 && seg[0] === '0') return false;\n    return Number(seg) <= 255;\n}\nlet result = 0;\nfor (let l1 = 1; l1 <= 3; l1++) {\n    for (let l2 = 1; l2 <= 3; l2++) {\n        for (let l3 = 1; l3 <= 3; l3++) {\n            const l4 = n - l1 - l2 - l3;\n            if (l4 < 1 || l4 > 3) continue;\n            if (l1 + l2 + l3 > n) continue;\n            const a = s.slice(0, l1), b = s.slice(l1, l1 + l2), c = s.slice(l1 + l2, l1 + l2 + l3), d = s.slice(l1 + l2 + l3);\n            if (valid(a) && valid(b) && valid(c) && valid(d)) result++;\n        }\n    }\n}",
    "typescript": "const n = s.length;\nfunction valid(seg: string): boolean {\n    if (seg.length === 0 || seg.length > 3) return false;\n    if (seg.length > 1 && seg[0] === '0') return false;\n    return Number(seg) <= 255;\n}\nlet result = 0;\nfor (let l1 = 1; l1 <= 3; l1++) {\n    for (let l2 = 1; l2 <= 3; l2++) {\n        for (let l3 = 1; l3 <= 3; l3++) {\n            const l4 = n - l1 - l2 - l3;\n            if (l4 < 1 || l4 > 3) continue;\n            if (l1 + l2 + l3 > n) continue;\n            const a = s.slice(0, l1), b = s.slice(l1, l1 + l2), c = s.slice(l1 + l2, l1 + l2 + l3), d = s.slice(l1 + l2 + l3);\n            if (valid(a) && valid(b) && valid(c) && valid(d)) result++;\n        }\n    }\n}",
    "perl": "my $n = length($s);\nsub valid_seg {\n    my ($seg) = @_;\n    return 0 if length($seg) == 0 || length($seg) > 3;\n    return 0 if length($seg) > 1 && substr($seg, 0, 1) eq '0';\n    return $seg <= 255;\n}\nmy $result = 0;\nfor (my $l1 = 1; $l1 <= 3; $l1++) {\n    for (my $l2 = 1; $l2 <= 3; $l2++) {\n        for (my $l3 = 1; $l3 <= 3; $l3++) {\n            my $l4 = $n - $l1 - $l2 - $l3;\n            next if $l4 < 1 || $l4 > 3;\n            next if $l1 + $l2 + $l3 > $n;\n            my $a = substr($s, 0, $l1);\n            my $b = substr($s, $l1, $l2);\n            my $c = substr($s, $l1 + $l2, $l3);\n            my $d = substr($s, $l1 + $l2 + $l3);\n            $result++ if valid_seg($a) && valid_seg($b) && valid_seg($c) && valid_seg($d);\n        }\n    }\n}",
    "java": "int n = s.length();\njava.util.function.Predicate<String> valid = seg -> {\n    if (seg.length() == 0 || seg.length() > 3) return false;\n    if (seg.length() > 1 && seg.charAt(0) == '0') return false;\n    return Integer.parseInt(seg) <= 255;\n};\nint result = 0;\nfor (int l1 = 1; l1 <= 3; l1++) {\n    for (int l2 = 1; l2 <= 3; l2++) {\n        for (int l3 = 1; l3 <= 3; l3++) {\n            int l4 = n - l1 - l2 - l3;\n            if (l4 < 1 || l4 > 3) continue;\n            if (l1 + l2 + l3 > n) continue;\n            String a = s.substring(0, l1), b = s.substring(l1, l1 + l2), c = s.substring(l1 + l2, l1 + l2 + l3), d = s.substring(l1 + l2 + l3);\n            if (valid.test(a) && valid.test(b) && valid.test(c) && valid.test(d)) result++;\n        }\n    }\n}",
    "cpp": "int n = (int) s.size();\nauto valid = [](const std::string &seg) {\n    if (seg.size() == 0 || seg.size() > 3) return false;\n    if (seg.size() > 1 && seg[0] == '0') return false;\n    return std::stoi(seg) <= 255;\n};\nint result = 0;\nfor (int l1 = 1; l1 <= 3; l1++) {\n    for (int l2 = 1; l2 <= 3; l2++) {\n        for (int l3 = 1; l3 <= 3; l3++) {\n            int l4 = n - l1 - l2 - l3;\n            if (l4 < 1 || l4 > 3) continue;\n            if (l1 + l2 + l3 > n) continue;\n            std::string a = s.substr(0, l1), b = s.substr(l1, l2), c = s.substr(l1 + l2, l3), d = s.substr(l1 + l2 + l3);\n            if (valid(a) && valid(b) && valid(c) && valid(d)) result++;\n        }\n    }\n}",
    "csharp": "int n = s.Length;\nSystem.Func<string, bool> valid = seg => {\n    if (seg.Length == 0 || seg.Length > 3) return false;\n    if (seg.Length > 1 && seg[0] == '0') return false;\n    return int.Parse(seg) <= 255;\n};\nint result = 0;\nfor (int l1 = 1; l1 <= 3; l1++) {\n    for (int l2 = 1; l2 <= 3; l2++) {\n        for (int l3 = 1; l3 <= 3; l3++) {\n            int l4 = n - l1 - l2 - l3;\n            if (l4 < 1 || l4 > 3) continue;\n            if (l1 + l2 + l3 > n) continue;\n            string a = s.Substring(0, l1), b = s.Substring(l1, l2), c = s.Substring(l1 + l2, l3), d = s.Substring(l1 + l2 + l3);\n            if (valid(a) && valid(b) && valid(c) && valid(d)) result++;\n        }\n    }\n}",
    "c": "int n = (int) strlen(s);\nint result = 0;\nfor (int l1 = 1; l1 <= 3; l1++) {\n    for (int l2 = 1; l2 <= 3; l2++) {\n        for (int l3 = 1; l3 <= 3; l3++) {\n            int l4 = n - l1 - l2 - l3;\n            if (l4 < 1 || l4 > 3) continue;\n            if (l1 + l2 + l3 > n) continue;\n            char a[4] = {0}, b[4] = {0}, c[4] = {0}, d[4] = {0};\n            memcpy(a, s, (size_t) l1);\n            memcpy(b, s + l1, (size_t) l2);\n            memcpy(c, s + l1 + l2, (size_t) l3);\n            memcpy(d, s + l1 + l2 + l3, (size_t) l4);\n            char *segs[4] = {a, b, c, d};\n            int lens[4] = {l1, l2, l3, l4};\n            int ok = 1;\n            for (int k = 0; k < 4; k++) {\n                if (lens[k] > 1 && segs[k][0] == '0') { ok = 0; break; }\n                if (atoi(segs[k]) > 255) { ok = 0; break; }\n            }\n            if (ok) result++;\n        }\n    }\n}",
    "rust": "let n = s.len();\nlet bytes = s.as_bytes();\nlet valid = |seg: &str| -> bool {\n    if seg.is_empty() || seg.len() > 3 { return false; }\n    if seg.len() > 1 && seg.as_bytes()[0] == b'0' { return false; }\n    seg.parse::<i32>().map(|v| v <= 255).unwrap_or(false)\n};\nlet mut result: i32 = 0;\nfor l1 in 1..=3usize {\n    for l2 in 1..=3usize {\n        for l3 in 1..=3usize {\n            if l1 + l2 + l3 > n { continue; }\n            let l4 = n - l1 - l2 - l3;\n            if l4 < 1 || l4 > 3 { continue; }\n            let a = std::str::from_utf8(&bytes[0..l1]).unwrap();\n            let b = std::str::from_utf8(&bytes[l1..l1+l2]).unwrap();\n            let c = std::str::from_utf8(&bytes[l1+l2..l1+l2+l3]).unwrap();\n            let d = std::str::from_utf8(&bytes[l1+l2+l3..]).unwrap();\n            if valid(a) && valid(b) && valid(c) && valid(d) { result += 1; }\n        }\n    }\n}",
    "swift": "let n = s.count\nlet sc = Array(s)\nfunc valid(_ seg: [Character]) -> Bool {\n    if seg.isEmpty || seg.count > 3 { return false }\n    if seg.count > 1 && seg[0] == \"0\" { return false }\n    let str = String(seg)\n    guard let v = Int(str) else { return false }\n    return v <= 255\n}\nvar result = 0\nfor l1 in 1...3 {\n    for l2 in 1...3 {\n        for l3 in 1...3 {\n            let l4 = n - l1 - l2 - l3\n            if l4 < 1 || l4 > 3 { continue }\n            if l1 + l2 + l3 > n { continue }\n            let a = Array(sc[0..<l1])\n            let b = Array(sc[l1..<(l1+l2)])\n            let c = Array(sc[(l1+l2)..<(l1+l2+l3)])\n            let d = Array(sc[(l1+l2+l3)...])\n            if valid(a) && valid(b) && valid(c) && valid(d) { result += 1 }\n        }\n    }\n}",
})


if __name__ == "__main__":
    sys.exit(asyncio.run(sh.main()))
