"""Program Mode expansion using the ALL-15-LANGUAGES shape harness
(atlascode_shapes_all15.py) -- javascript, typescript, java, cpp, csharp,
perl, c, rust, go, kotlin, php, r, ruby, scala, swift. Per explicit user
direction (2026-07-12): never scope a batch to a language subset; every
add() call below supplies bodies for all 15, and the harness's own
already-verified check skips whichever ones a prior session already
covered for that specific problem (coverage is NOT uniform across
languages -- e.g. binary-search already had go/kotlin/ruby from an earlier
session while most other searching-family problems didn't).
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import logging
logging.disable(logging.CRITICAL)

import atlascode_shapes_all15 as sh

add = sh.add

# ═════════════════════════════════════════════════════════════════════════
# binary_search(nums, extra) -> index of extra in SORTED nums, or -1
# ═════════════════════════════════════════════════════════════════════════
add("binary-search", "arr1_int", "binary_search", "int", {
    "go": "lo, hi := 0, len(nums)-1\nresult := int64(-1)\nfor lo <= hi {\n\tmid := (lo + hi) / 2\n\tif nums[mid] == extra { result = int64(mid); break }\n\tif nums[mid] < extra { lo = mid + 1 } else { hi = mid - 1 }\n}",
    "ruby": "lo = 0\nhi = nums.length - 1\nresult = -1\nwhile lo <= hi\n  mid = (lo + hi) / 2\n  if nums[mid] == extra\n    result = mid\n    break\n  elsif nums[mid] < extra\n    lo = mid + 1\n  else\n    hi = mid - 1\n  end\nend",
    "kotlin": "var lo = 0\nvar hi = nums.size - 1\nvar result = -1L\nwhile (lo <= hi) {\n    val mid = (lo + hi) / 2\n    if (nums[mid] == extra) { result = mid.toLong(); break }\n    if (nums[mid] < extra) lo = mid + 1 else hi = mid - 1\n}",
    "php": "$lo = 0; $hi = count($nums) - 1; $result = -1;\nwhile ($lo <= $hi) {\n    $mid = intdiv($lo + $hi, 2);\n    if ($nums[$mid] == $extra) { $result = $mid; break; }\n    if ($nums[$mid] < $extra) { $lo = $mid + 1; } else { $hi = $mid - 1; }\n}",
    "scala": "var lo = 0\nvar hi = nums.length - 1\nvar result: Long = -1L\nvar found = false\nwhile (lo <= hi && !found) {\n  val mid = (lo + hi) / 2\n  if (nums(mid) == extra) { result = mid.toLong; found = true }\n  else if (nums(mid) < extra) lo = mid + 1\n  else hi = mid - 1\n}",
    "r": "lo <- 1; hi <- length(nums); result <- -1\nwhile (lo <= hi) {\n  mid <- (lo + hi) %/% 2\n  if (nums[mid] == extra) { result <- mid - 1; break }\n  else if (nums[mid] < extra) { lo <- mid + 1 } else { hi <- mid - 1 }\n}",
    "javascript": "let lo = 0, hi = nums.length - 1;\nlet result = -1;\nwhile (lo <= hi) {\n    const mid = (lo + hi) >> 1;\n    if (nums[mid] === extra) { result = mid; break; }\n    if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n}",
    "typescript": "let lo = 0, hi = nums.length - 1;\nlet result = -1;\nwhile (lo <= hi) {\n    const mid = (lo + hi) >> 1;\n    if (nums[mid] === extra) { result = mid; break; }\n    if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n}",
    "perl": "my $lo = 0; my $hi = scalar(@{$nums}) - 1; my $result = -1;\nwhile ($lo <= $hi) {\n    my $mid = int(($lo + $hi) / 2);\n    if ($nums->[$mid] == $extra) { $result = $mid; last; }\n    if ($nums->[$mid] < $extra) { $lo = $mid + 1; } else { $hi = $mid - 1; }\n}",
    "java": "int lo = 0, hi = nums.length - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] == extra) { result = mid; break; }\n    if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n}",
    "cpp": "int lo = 0, hi = (int) nums.size() - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] == extra) { result = mid; break; }\n    if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n}",
    "csharp": "int lo = 0, hi = nums.Length - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] == extra) { result = mid; break; }\n    if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n}",
    "c": "int lo = 0, hi = n - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] == extra) { result = mid; break; }\n    if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n}",
    "rust": "let mut lo: i32 = 0;\nlet mut hi: i32 = nums.len() as i32 - 1;\nlet mut result: i32 = -1;\nwhile lo <= hi {\n    let mid = (lo + hi) / 2;\n    if nums[mid as usize] == extra { result = mid; break; }\n    if nums[mid as usize] < extra { lo = mid + 1; } else { hi = mid - 1; }\n}",
    "swift": "var lo = 0\nvar hi = nums.count - 1\nvar result = -1\nwhile lo <= hi {\n    let mid = (lo + hi) / 2\n    if nums[mid] == extra { result = mid; break }\n    if nums[mid] < extra { lo = mid + 1 } else { hi = mid - 1 }\n}",
})


# ═════════════════════════════════════════════════════════════════════════
# linear_search(nums, extra) -> first index of extra, or -1
# ═════════════════════════════════════════════════════════════════════════
add("linear-search", "arr1_int", "linear_search", "int", {
    "go": "result := int64(-1)\nfor i, v := range nums {\n\tif v == extra { result = int64(i); break }\n}",
    "ruby": "result = -1\nnums.each_with_index do |v, i|\n  if v == extra\n    result = i\n    break\n  end\nend",
    "kotlin": "var result = -1L\nfor (i in nums.indices) { if (nums[i] == extra) { result = i.toLong(); break } }",
    "php": "$result = -1;\nforeach ($nums as $i => $v) { if ($v == $extra) { $result = $i; break; } }",
    "scala": "var result: Long = -1L\nvar found = false\nfor (i <- nums.indices if !found) { if (nums(i) == extra) { result = i.toLong; found = true } }",
    "r": "result <- -1\nif (length(nums) > 0) { for (i in 1:length(nums)) { if (nums[i] == extra) { result <- i - 1; break } } }",
    "javascript": "let result = -1;\nfor (let i = 0; i < nums.length; i++) { if (nums[i] === extra) { result = i; break; } }",
    "typescript": "let result = -1;\nfor (let i = 0; i < nums.length; i++) { if (nums[i] === extra) { result = i; break; } }",
    "perl": "my $result = -1;\nfor (my $i = 0; $i < scalar(@{$nums}); $i++) { if ($nums->[$i] == $extra) { $result = $i; last; } }",
    "java": "int result = -1;\nfor (int i = 0; i < nums.length; i++) { if (nums[i] == extra) { result = i; break; } }",
    "cpp": "int result = -1;\nfor (int i = 0; i < (int) nums.size(); i++) { if (nums[i] == extra) { result = i; break; } }",
    "csharp": "int result = -1;\nfor (int i = 0; i < nums.Length; i++) { if (nums[i] == extra) { result = i; break; } }",
    "c": "int result = -1;\nfor (int i = 0; i < n; i++) { if (nums[i] == extra) { result = i; break; } }",
    "rust": "let mut result: i32 = -1;\nfor i in 0..nums.len() { if nums[i] == extra { result = i as i32; break; } }",
    "swift": "var result = -1\nfor i in 0..<nums.count { if nums[i] == extra { result = i; break } }",
})

# ═════════════════════════════════════════════════════════════════════════
# jump_search(nums, extra) -> index via block-jump then linear scan, or -1
# ═════════════════════════════════════════════════════════════════════════
add("jump-search", "arr1_int", "jump_search", "int", {
    "go": ("n := len(nums)\nresult := int64(-1)\nstep := int(math.Sqrt(float64(n)))\nif step < 1 { step = 1 }\nprev := 0\ncurr := step\nfor curr < n && nums[curr-1] < extra {\n\tprev = curr\n\tcurr += step\n}\nif prev > n { prev = n }\nif curr > n { curr = n }\nfor i := prev; i < curr; i++ {\n\tif nums[i] == extra { result = int64(i); break }\n}"),
    "ruby": ("n = nums.length\nresult = -1\nstep = Math.sqrt(n).to_i\nstep = 1 if step < 1\nprev = 0\ncurr = step\nwhile curr < n && nums[curr - 1] < extra\n  prev = curr\n  curr += step\nend\nprev = n if prev > n\ncurr = n if curr > n\n(prev...curr).each do |i|\n  if nums[i] == extra\n    result = i\n    break\n  end\nend"),
    "kotlin": ("val n = nums.size\nvar result = -1L\nvar step = Math.sqrt(n.toDouble()).toInt()\nif (step < 1) step = 1\nvar prev = 0\nvar curr = step\nwhile (curr < n && nums[curr - 1] < extra) { prev = curr; curr += step }\nif (prev > n) prev = n\nif (curr > n) curr = n\nfor (i in prev until curr) { if (nums[i] == extra) { result = i.toLong(); break } }"),
    "php": ("$n = count($nums);\n$result = -1;\n$step = (int) sqrt($n);\nif ($step < 1) { $step = 1; }\n$prev = 0; $curr = $step;\nwhile ($curr < $n && $nums[$curr - 1] < $extra) { $prev = $curr; $curr += $step; }\nif ($prev > $n) { $prev = $n; }\nif ($curr > $n) { $curr = $n; }\nfor ($i = $prev; $i < $curr; $i++) { if ($nums[$i] == $extra) { $result = $i; break; } }"),
    "scala": ("val n = nums.length\nvar result: Long = -1L\nvar step = math.sqrt(n.toDouble).toInt\nif (step < 1) step = 1\nvar prev = 0\nvar curr = step\nwhile (curr < n && nums(curr - 1) < extra) { prev = curr; curr += step }\nif (prev > n) prev = n\nif (curr > n) curr = n\nvar found = false\nfor (i <- prev until curr if !found) { if (nums(i) == extra) { result = i.toLong; found = true } }"),
    "r": ("n <- length(nums)\nresult <- -1\nstep <- as.integer(floor(sqrt(n)))\nif (step < 1) step <- 1\nprev <- 0\ncurr <- step\nwhile (curr < n && nums[curr] < extra) { prev <- curr; curr <- curr + step }\nif (prev > n) prev <- n\nif (curr > n) curr <- n\nif (prev < curr) { for (i in (prev + 1):curr) { if (nums[i] == extra) { result <- i - 1; break } } }"),
    "javascript": ("const n = nums.length;\nlet result = -1;\nlet step = Math.floor(Math.sqrt(n));\nif (step < 1) step = 1;\nlet prev = 0, curr = step;\nwhile (curr < n && nums[curr - 1] < extra) { prev = curr; curr += step; }\nif (prev > n) prev = n;\nif (curr > n) curr = n;\nfor (let i = prev; i < curr; i++) { if (nums[i] === extra) { result = i; break; } }"),
    "typescript": ("const n = nums.length;\nlet result = -1;\nlet step = Math.floor(Math.sqrt(n));\nif (step < 1) step = 1;\nlet prev = 0, curr = step;\nwhile (curr < n && nums[curr - 1] < extra) { prev = curr; curr += step; }\nif (prev > n) prev = n;\nif (curr > n) curr = n;\nfor (let i = prev; i < curr; i++) { if (nums[i] === extra) { result = i; break; } }"),
    "perl": ("my $n = scalar(@{$nums});\nmy $result = -1;\nmy $step = int(sqrt($n));\n$step = 1 if $step < 1;\nmy $prev = 0; my $curr = $step;\nwhile ($curr < $n && $nums->[$curr - 1] < $extra) { $prev = $curr; $curr += $step; }\n$prev = $n if $prev > $n;\n$curr = $n if $curr > $n;\nfor (my $i = $prev; $i < $curr; $i++) { if ($nums->[$i] == $extra) { $result = $i; last; } }"),
    "java": ("int n = nums.length;\nint result = -1;\nint step = (int) Math.sqrt(n);\nif (step < 1) step = 1;\nint prev = 0, curr = step;\nwhile (curr < n && nums[curr - 1] < extra) { prev = curr; curr += step; }\nif (prev > n) prev = n;\nif (curr > n) curr = n;\nfor (int i = prev; i < curr; i++) { if (nums[i] == extra) { result = i; break; } }"),
    "cpp": ("int n = (int) nums.size();\nint result = -1;\nint step = (int) sqrt((double) n);\nif (step < 1) step = 1;\nint prev = 0, curr = step;\nwhile (curr < n && nums[curr - 1] < extra) { prev = curr; curr += step; }\nif (prev > n) prev = n;\nif (curr > n) curr = n;\nfor (int i = prev; i < curr; i++) { if (nums[i] == extra) { result = i; break; } }"),
    "csharp": ("int n = nums.Length;\nint result = -1;\nint step = (int) System.Math.Sqrt(n);\nif (step < 1) step = 1;\nint prev = 0, curr = step;\nwhile (curr < n && nums[curr - 1] < extra) { prev = curr; curr += step; }\nif (prev > n) prev = n;\nif (curr > n) curr = n;\nfor (int i = prev; i < curr; i++) { if (nums[i] == extra) { result = i; break; } }"),
    "c": ("int result = -1;\nint step = (int) sqrt((double) n);\nif (step < 1) step = 1;\nint prev = 0, curr = step;\nwhile (curr < n && nums[curr - 1] < extra) { prev = curr; curr += step; }\nif (prev > n) prev = n;\nif (curr > n) curr = n;\nfor (int i = prev; i < curr; i++) { if (nums[i] == extra) { result = i; break; } }"),
    "rust": ("let n = nums.len() as i32;\nlet mut result: i32 = -1;\nlet mut step = (n as f64).sqrt() as i32;\nif step < 1 { step = 1; }\nlet mut prev = 0;\nlet mut curr = step;\nwhile curr < n && nums[(curr - 1) as usize] < extra { prev = curr; curr += step; }\nif prev > n { prev = n; }\nif curr > n { curr = n; }\nlet mut i = prev;\nwhile i < curr { if nums[i as usize] == extra { result = i; break; } i += 1; }"),
    "swift": ("let n = nums.count\nvar result = -1\nvar step = Int(Double(n).squareRoot())\nif step < 1 { step = 1 }\nvar prev = 0\nvar curr = step\nwhile curr < n && nums[curr - 1] < extra { prev = curr; curr += step }\nif prev > n { prev = n }\nif curr > n { curr = n }\nvar i = prev\nwhile i < curr { if nums[i] == extra { result = i; break }; i += 1 }"),
})

# ═════════════════════════════════════════════════════════════════════════
# exponential_search(nums, extra) -> range doubling then binary search
# ═════════════════════════════════════════════════════════════════════════
add("exponential-search", "arr1_int", "exponential_search", "int", {
    "go": ("n := len(nums)\nresult := int64(-1)\nif n > 0 {\n\tif nums[0] == extra {\n\t\tresult = 0\n\t} else {\n\t\tbound := 1\n\t\tfor bound < n && nums[bound] < extra { bound *= 2 }\n\t\tlo := bound / 2\n\t\thi := bound\n\t\tif hi >= n { hi = n - 1 }\n\t\tfor lo <= hi {\n\t\t\tmid := (lo + hi) / 2\n\t\t\tif nums[mid] == extra { result = int64(mid); break }\n\t\t\tif nums[mid] < extra { lo = mid + 1 } else { hi = mid - 1 }\n\t\t}\n\t}\n}"),
    "ruby": ("n = nums.length\nresult = -1\nif n > 0\n  if nums[0] == extra\n    result = 0\n  else\n    bound = 1\n    while bound < n && nums[bound] < extra\n      bound *= 2\n    end\n    lo = bound / 2\n    hi = [bound, n - 1].min\n    while lo <= hi\n      mid = (lo + hi) / 2\n      if nums[mid] == extra\n        result = mid\n        break\n      elsif nums[mid] < extra\n        lo = mid + 1\n      else\n        hi = mid - 1\n      end\n    end\n  end\nend"),
    "kotlin": ("val n = nums.size\nvar result = -1L\nif (n > 0) {\n    if (nums[0] == extra) {\n        result = 0L\n    } else {\n        var bound = 1\n        while (bound < n && nums[bound] < extra) bound *= 2\n        var lo = bound / 2\n        var hi = minOf(bound, n - 1)\n        while (lo <= hi) {\n            val mid = (lo + hi) / 2\n            if (nums[mid] == extra) { result = mid.toLong(); break }\n            if (nums[mid] < extra) lo = mid + 1 else hi = mid - 1\n        }\n    }\n}"),
    "php": ("$n = count($nums);\n$result = -1;\nif ($n > 0) {\n    if ($nums[0] == $extra) {\n        $result = 0;\n    } else {\n        $bound = 1;\n        while ($bound < $n && $nums[$bound] < $extra) { $bound *= 2; }\n        $lo = intdiv($bound, 2);\n        $hi = min($bound, $n - 1);\n        while ($lo <= $hi) {\n            $mid = intdiv($lo + $hi, 2);\n            if ($nums[$mid] == $extra) { $result = $mid; break; }\n            if ($nums[$mid] < $extra) { $lo = $mid + 1; } else { $hi = $mid - 1; }\n        }\n    }\n}"),
    "scala": ("val n = nums.length\nvar result: Long = -1L\nif (n > 0) {\n  if (nums(0) == extra) {\n    result = 0L\n  } else {\n    var bound = 1\n    while (bound < n && nums(bound) < extra) bound *= 2\n    var lo = bound / 2\n    var hi = math.min(bound, n - 1)\n    var found = false\n    while (lo <= hi && !found) {\n      val mid = (lo + hi) / 2\n      if (nums(mid) == extra) { result = mid.toLong; found = true }\n      else if (nums(mid) < extra) lo = mid + 1\n      else hi = mid - 1\n    }\n  }\n}"),
    "r": ("n <- length(nums)\nresult <- -1\nif (n > 0) {\n  if (nums[1] == extra) {\n    result <- 0\n  } else {\n    bound <- 1\n    while (bound < n && nums[bound + 1] < extra) { bound <- bound * 2 }\n    lo <- bound %/% 2 + 1\n    hi <- min(bound + 1, n)\n    while (lo <= hi) {\n      mid <- (lo + hi) %/% 2\n      if (nums[mid] == extra) { result <- mid - 1; break }\n      else if (nums[mid] < extra) { lo <- mid + 1 } else { hi <- mid - 1 }\n    }\n  }\n}"),
    "javascript": ("const n = nums.length;\nlet result = -1;\nif (n > 0) {\n  if (nums[0] === extra) { result = 0; }\n  else {\n    let bound = 1;\n    while (bound < n && nums[bound] < extra) bound *= 2;\n    let lo = Math.floor(bound / 2);\n    let hi = Math.min(bound, n - 1);\n    while (lo <= hi) {\n      const mid = (lo + hi) >> 1;\n      if (nums[mid] === extra) { result = mid; break; }\n      if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n    }\n  }\n}"),
    "typescript": ("const n = nums.length;\nlet result = -1;\nif (n > 0) {\n  if (nums[0] === extra) { result = 0; }\n  else {\n    let bound = 1;\n    while (bound < n && nums[bound] < extra) bound *= 2;\n    let lo = Math.floor(bound / 2);\n    let hi = Math.min(bound, n - 1);\n    while (lo <= hi) {\n      const mid = (lo + hi) >> 1;\n      if (nums[mid] === extra) { result = mid; break; }\n      if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n    }\n  }\n}"),
    "perl": ("my $n = scalar(@{$nums});\nmy $result = -1;\nif ($n > 0) {\n  if ($nums->[0] == $extra) { $result = 0; }\n  else {\n    my $bound = 1;\n    while ($bound < $n && $nums->[$bound] < $extra) { $bound *= 2; }\n    my $lo = int($bound / 2);\n    my $hi = $bound < $n - 1 ? $bound : $n - 1;\n    while ($lo <= $hi) {\n      my $mid = int(($lo + $hi) / 2);\n      if ($nums->[$mid] == $extra) { $result = $mid; last; }\n      if ($nums->[$mid] < $extra) { $lo = $mid + 1; } else { $hi = $mid - 1; }\n    }\n  }\n}"),
    "java": ("int n = nums.length;\nint result = -1;\nif (n > 0) {\n  if (nums[0] == extra) { result = 0; }\n  else {\n    int bound = 1;\n    while (bound < n && nums[bound] < extra) bound *= 2;\n    int lo = bound / 2;\n    int hi = Math.min(bound, n - 1);\n    while (lo <= hi) {\n      int mid = (lo + hi) / 2;\n      if (nums[mid] == extra) { result = mid; break; }\n      if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n    }\n  }\n}"),
    "cpp": ("int n = (int) nums.size();\nint result = -1;\nif (n > 0) {\n  if (nums[0] == extra) { result = 0; }\n  else {\n    int bound = 1;\n    while (bound < n && nums[bound] < extra) bound *= 2;\n    int lo = bound / 2;\n    int hi = std::min(bound, n - 1);\n    while (lo <= hi) {\n      int mid = (lo + hi) / 2;\n      if (nums[mid] == extra) { result = mid; break; }\n      if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n    }\n  }\n}"),
    "csharp": ("int n = nums.Length;\nint result = -1;\nif (n > 0) {\n  if (nums[0] == extra) { result = 0; }\n  else {\n    int bound = 1;\n    while (bound < n && nums[bound] < extra) bound *= 2;\n    int lo = bound / 2;\n    int hi = System.Math.Min(bound, n - 1);\n    while (lo <= hi) {\n      int mid = (lo + hi) / 2;\n      if (nums[mid] == extra) { result = mid; break; }\n      if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n    }\n  }\n}"),
    "c": ("int result = -1;\nif (n > 0) {\n  if (nums[0] == extra) { result = 0; }\n  else {\n    int bound = 1;\n    while (bound < n && nums[bound] < extra) bound *= 2;\n    int lo = bound / 2;\n    int hi = bound < n - 1 ? bound : n - 1;\n    while (lo <= hi) {\n      int mid = (lo + hi) / 2;\n      if (nums[mid] == extra) { result = mid; break; }\n      if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n    }\n  }\n}"),
    "rust": ("let n = nums.len() as i32;\nlet mut result: i32 = -1;\nif n > 0 {\n  if nums[0] == extra { result = 0; }\n  else {\n    let mut bound = 1;\n    while bound < n && nums[bound as usize] < extra { bound *= 2; }\n    let mut lo = bound / 2;\n    let mut hi = std::cmp::min(bound, n - 1);\n    while lo <= hi {\n      let mid = (lo + hi) / 2;\n      if nums[mid as usize] == extra { result = mid; break; }\n      if nums[mid as usize] < extra { lo = mid + 1; } else { hi = mid - 1; }\n    }\n  }\n}"),
    "swift": ("let n = nums.count\nvar result = -1\nif n > 0 {\n  if nums[0] == extra { result = 0 }\n  else {\n    var bound = 1\n    while bound < n && nums[bound] < extra { bound *= 2 }\n    var lo = bound / 2\n    var hi = min(bound, n - 1)\n    while lo <= hi {\n      let mid = (lo + hi) / 2\n      if nums[mid] == extra { result = mid; break }\n      if nums[mid] < extra { lo = mid + 1 } else { hi = mid - 1 }\n    }\n  }\n}"),
})

# ═════════════════════════════════════════════════════════════════════════
# interpolation_search(nums, extra) -> probes by interpolated position
# ═════════════════════════════════════════════════════════════════════════
add("interpolation-search", "arr1_int", "interpolation_search", "int", {
    "go": ("lo, hi := 0, len(nums)-1\nresult := int64(-1)\nfor lo <= hi && extra >= nums[lo] && extra <= nums[hi] {\n\tif nums[hi] == nums[lo] {\n\t\tif nums[lo] == extra { result = int64(lo) }\n\t\tbreak\n\t}\n\tpos := lo + ((extra-nums[lo])*(hi-lo))/(nums[hi]-nums[lo])\n\tif pos < lo || pos > hi { break }\n\tif nums[pos] == extra { result = int64(pos); break }\n\tif nums[pos] < extra { lo = pos + 1 } else { hi = pos - 1 }\n}"),
    "ruby": ("lo = 0\nhi = nums.length - 1\nresult = -1\nwhile lo <= hi && extra >= nums[lo] && extra <= nums[hi]\n  if nums[hi] == nums[lo]\n    result = lo if nums[lo] == extra\n    break\n  end\n  pos = lo + ((extra - nums[lo]) * (hi - lo)) / (nums[hi] - nums[lo])\n  break if pos < lo || pos > hi\n  if nums[pos] == extra\n    result = pos\n    break\n  elsif nums[pos] < extra\n    lo = pos + 1\n  else\n    hi = pos - 1\n  end\nend"),
    "kotlin": ("var lo = 0\nvar hi = nums.size - 1\nvar result = -1L\nwhile (lo <= hi && extra >= nums[lo] && extra <= nums[hi]) {\n    if (nums[hi] == nums[lo]) {\n        if (nums[lo] == extra) result = lo.toLong()\n        break\n    }\n    val pos = lo + ((extra - nums[lo]) * (hi - lo)) / (nums[hi] - nums[lo])\n    if (pos < lo || pos > hi) break\n    if (nums[pos] == extra) { result = pos.toLong(); break }\n    if (nums[pos] < extra) lo = pos + 1 else hi = pos - 1\n}"),
    "php": ("$lo = 0; $hi = count($nums) - 1; $result = -1;\nwhile ($lo <= $hi && $extra >= $nums[$lo] && $extra <= $nums[$hi]) {\n    if ($nums[$hi] == $nums[$lo]) {\n        if ($nums[$lo] == $extra) { $result = $lo; }\n        break;\n    }\n    $pos = $lo + intdiv(($extra - $nums[$lo]) * ($hi - $lo), $nums[$hi] - $nums[$lo]);\n    if ($pos < $lo || $pos > $hi) { break; }\n    if ($nums[$pos] == $extra) { $result = $pos; break; }\n    if ($nums[$pos] < $extra) { $lo = $pos + 1; } else { $hi = $pos - 1; }\n}"),
    "scala": ("var lo = 0\nvar hi = nums.length - 1\nvar result: Long = -1L\nvar stop = false\nwhile (lo <= hi && extra >= nums(lo) && extra <= nums(hi) && !stop) {\n  if (nums(hi) == nums(lo)) {\n    if (nums(lo) == extra) result = lo.toLong\n    stop = true\n  } else {\n    val pos = lo + ((extra - nums(lo)) * (hi - lo)) / (nums(hi) - nums(lo))\n    if (pos < lo || pos > hi) { stop = true }\n    else if (nums(pos) == extra) { result = pos.toLong; stop = true }\n    else if (nums(pos) < extra) lo = pos + 1\n    else hi = pos - 1\n  }\n}"),
    "r": ("lo <- 1; hi <- length(nums); result <- -1\nwhile (lo <= hi && extra >= nums[lo] && extra <= nums[hi]) {\n  if (nums[hi] == nums[lo]) {\n    if (nums[lo] == extra) result <- lo - 1\n    break\n  }\n  pos <- lo + ((extra - nums[lo]) * (hi - lo)) %/% (nums[hi] - nums[lo])\n  if (pos < lo || pos > hi) break\n  if (nums[pos] == extra) { result <- pos - 1; break }\n  else if (nums[pos] < extra) { lo <- pos + 1 } else { hi <- pos - 1 }\n}"),
    "javascript": ("let lo = 0, hi = nums.length - 1;\nlet result = -1;\nwhile (lo <= hi && extra >= nums[lo] && extra <= nums[hi]) {\n  if (nums[hi] === nums[lo]) { if (nums[lo] === extra) result = lo; break; }\n  const pos = lo + Math.floor(((extra - nums[lo]) * (hi - lo)) / (nums[hi] - nums[lo]));\n  if (pos < lo || pos > hi) break;\n  if (nums[pos] === extra) { result = pos; break; }\n  if (nums[pos] < extra) lo = pos + 1; else hi = pos - 1;\n}"),
    "typescript": ("let lo = 0, hi = nums.length - 1;\nlet result = -1;\nwhile (lo <= hi && extra >= nums[lo] && extra <= nums[hi]) {\n  if (nums[hi] === nums[lo]) { if (nums[lo] === extra) result = lo; break; }\n  const pos = lo + Math.floor(((extra - nums[lo]) * (hi - lo)) / (nums[hi] - nums[lo]));\n  if (pos < lo || pos > hi) break;\n  if (nums[pos] === extra) { result = pos; break; }\n  if (nums[pos] < extra) lo = pos + 1; else hi = pos - 1;\n}"),
    "perl": ("my $lo = 0; my $hi = scalar(@{$nums}) - 1; my $result = -1;\nwhile ($lo <= $hi && $extra >= $nums->[$lo] && $extra <= $nums->[$hi]) {\n  if ($nums->[$hi] == $nums->[$lo]) { if ($nums->[$lo] == $extra) { $result = $lo; } last; }\n  my $pos = $lo + int((($extra - $nums->[$lo]) * ($hi - $lo)) / ($nums->[$hi] - $nums->[$lo]));\n  last if $pos < $lo || $pos > $hi;\n  if ($nums->[$pos] == $extra) { $result = $pos; last; }\n  if ($nums->[$pos] < $extra) { $lo = $pos + 1; } else { $hi = $pos - 1; }\n}"),
    "java": ("int lo = 0, hi = nums.length - 1;\nint result = -1;\nwhile (lo <= hi && extra >= nums[lo] && extra <= nums[hi]) {\n  if (nums[hi] == nums[lo]) { if (nums[lo] == extra) result = lo; break; }\n  int pos = lo + ((extra - nums[lo]) * (hi - lo)) / (nums[hi] - nums[lo]);\n  if (pos < lo || pos > hi) break;\n  if (nums[pos] == extra) { result = pos; break; }\n  if (nums[pos] < extra) lo = pos + 1; else hi = pos - 1;\n}"),
    "cpp": ("int lo = 0, hi = (int) nums.size() - 1;\nint result = -1;\nwhile (lo <= hi && extra >= nums[lo] && extra <= nums[hi]) {\n  if (nums[hi] == nums[lo]) { if (nums[lo] == extra) result = lo; break; }\n  int pos = lo + ((extra - nums[lo]) * (hi - lo)) / (nums[hi] - nums[lo]);\n  if (pos < lo || pos > hi) break;\n  if (nums[pos] == extra) { result = pos; break; }\n  if (nums[pos] < extra) lo = pos + 1; else hi = pos - 1;\n}"),
    "csharp": ("int lo = 0, hi = nums.Length - 1;\nint result = -1;\nwhile (lo <= hi && extra >= nums[lo] && extra <= nums[hi]) {\n  if (nums[hi] == nums[lo]) { if (nums[lo] == extra) result = lo; break; }\n  int pos = lo + ((extra - nums[lo]) * (hi - lo)) / (nums[hi] - nums[lo]);\n  if (pos < lo || pos > hi) break;\n  if (nums[pos] == extra) { result = pos; break; }\n  if (nums[pos] < extra) lo = pos + 1; else hi = pos - 1;\n}"),
    "c": ("int lo = 0, hi = n - 1;\nint result = -1;\nwhile (lo <= hi && extra >= nums[lo] && extra <= nums[hi]) {\n  if (nums[hi] == nums[lo]) { if (nums[lo] == extra) result = lo; break; }\n  int pos = lo + ((extra - nums[lo]) * (hi - lo)) / (nums[hi] - nums[lo]);\n  if (pos < lo || pos > hi) break;\n  if (nums[pos] == extra) { result = pos; break; }\n  if (nums[pos] < extra) lo = pos + 1; else hi = pos - 1;\n}"),
    "rust": ("let mut lo: i32 = 0;\nlet mut hi: i32 = nums.len() as i32 - 1;\nlet mut result: i32 = -1;\nwhile lo <= hi && extra >= nums[lo as usize] && extra <= nums[hi as usize] {\n  if nums[hi as usize] == nums[lo as usize] {\n    if nums[lo as usize] == extra { result = lo; }\n    break;\n  }\n  let pos = lo + ((extra - nums[lo as usize]) * (hi - lo)) / (nums[hi as usize] - nums[lo as usize]);\n  if pos < lo || pos > hi { break; }\n  if nums[pos as usize] == extra { result = pos; break; }\n  if nums[pos as usize] < extra { lo = pos + 1; } else { hi = pos - 1; }\n}"),
    "swift": ("var lo = 0\nvar hi = nums.count - 1\nvar result = -1\nwhile lo <= hi && extra >= nums[lo] && extra <= nums[hi] {\n  if nums[hi] == nums[lo] { if nums[lo] == extra { result = lo }; break }\n  let pos = lo + ((extra - nums[lo]) * (hi - lo)) / (nums[hi] - nums[lo])\n  if pos < lo || pos > hi { break }\n  if nums[pos] == extra { result = pos; break }\n  if nums[pos] < extra { lo = pos + 1 } else { hi = pos - 1 }\n}"),
})

# ═════════════════════════════════════════════════════════════════════════
# fibonacci_search(nums, extra) -> classic Fibonacci-search technique
# ═════════════════════════════════════════════════════════════════════════
add("fibonacci-search", "arr1_int", "fibonacci_search", "int", {
    "go": ("n := len(nums)\nresult := int64(-1)\nfibMMm2 := 0\nfibMMm1 := 1\nfibM := fibMMm2 + fibMMm1\nfor fibM < n {\n\tfibMMm2 = fibMMm1\n\tfibMMm1 = fibM\n\tfibM = fibMMm2 + fibMMm1\n}\noffset := -1\nfor fibM > 1 {\n\ti := offset + fibMMm2\n\tif i < n-1 { i = i } else { i = n - 1 }\n\tif i < 0 { i = 0 }\n\tif nums[i] < extra {\n\t\tfibM = fibMMm1\n\t\tfibMMm1 = fibMMm2\n\t\tfibMMm2 = fibM - fibMMm1\n\t\toffset = i\n\t} else if nums[i] > extra {\n\t\tfibM = fibMMm2\n\t\tfibMMm1 = fibMMm1 - fibMMm2\n\t\tfibMMm2 = fibM - fibMMm1\n\t} else {\n\t\tresult = int64(i)\n\t\tbreak\n\t}\n}\nif result == -1 && fibMMm1 == 1 && offset+1 < n && nums[offset+1] == extra {\n\tresult = int64(offset + 1)\n}"),
    "ruby": ("n = nums.length\nresult = -1\nfib_mm2 = 0\nfib_mm1 = 1\nfib_m = fib_mm2 + fib_mm1\nwhile fib_m < n\n  fib_mm2 = fib_mm1\n  fib_mm1 = fib_m\n  fib_m = fib_mm2 + fib_mm1\nend\noffset = -1\nwhile fib_m > 1\n  i = [offset + fib_mm2, n - 1].min\n  i = 0 if i < 0\n  if nums[i] < extra\n    fib_m = fib_mm1\n    fib_mm1 = fib_mm2\n    fib_mm2 = fib_m - fib_mm1\n    offset = i\n  elsif nums[i] > extra\n    fib_m = fib_mm2\n    fib_mm1 = fib_mm1 - fib_mm2\n    fib_mm2 = fib_m - fib_mm1\n  else\n    result = i\n    break\n  end\nend\nif result == -1 && fib_mm1 == 1 && offset + 1 < n && nums[offset + 1] == extra\n  result = offset + 1\nend"),
    "kotlin": ("val n = nums.size\nvar result = -1L\nvar fibMMm2 = 0\nvar fibMMm1 = 1\nvar fibM = fibMMm2 + fibMMm1\nwhile (fibM < n) { fibMMm2 = fibMMm1; fibMMm1 = fibM; fibM = fibMMm2 + fibMMm1 }\nvar offset = -1\nwhile (fibM > 1) {\n    var i = minOf(offset + fibMMm2, n - 1)\n    if (i < 0) i = 0\n    if (nums[i] < extra) {\n        fibM = fibMMm1; fibMMm1 = fibMMm2; fibMMm2 = fibM - fibMMm1; offset = i\n    } else if (nums[i] > extra) {\n        fibM = fibMMm2; fibMMm1 -= fibMMm2; fibMMm2 = fibM - fibMMm1\n    } else {\n        result = i.toLong(); break\n    }\n}\nif (result == -1L && fibMMm1 == 1 && offset + 1 < n && nums[offset + 1] == extra) result = (offset + 1).toLong()"),
    "php": ("$n = count($nums);\n$result = -1;\n$fibMMm2 = 0; $fibMMm1 = 1; $fibM = $fibMMm2 + $fibMMm1;\nwhile ($fibM < $n) { $fibMMm2 = $fibMMm1; $fibMMm1 = $fibM; $fibM = $fibMMm2 + $fibMMm1; }\n$offset = -1;\nwhile ($fibM > 1) {\n    $i = min($offset + $fibMMm2, $n - 1);\n    if ($i < 0) { $i = 0; }\n    if ($nums[$i] < $extra) {\n        $fibM = $fibMMm1; $fibMMm1 = $fibMMm2; $fibMMm2 = $fibM - $fibMMm1; $offset = $i;\n    } elseif ($nums[$i] > $extra) {\n        $fibM = $fibMMm2; $fibMMm1 -= $fibMMm2; $fibMMm2 = $fibM - $fibMMm1;\n    } else {\n        $result = $i; break;\n    }\n}\nif ($result == -1 && $fibMMm1 == 1 && $offset + 1 < $n && $nums[$offset + 1] == $extra) { $result = $offset + 1; }"),
    "scala": ("val n = nums.length\nvar result: Long = -1L\nvar fibMMm2 = 0\nvar fibMMm1 = 1\nvar fibM = fibMMm2 + fibMMm1\nwhile (fibM < n) { fibMMm2 = fibMMm1; fibMMm1 = fibM; fibM = fibMMm2 + fibMMm1 }\nvar offset = -1\nvar found = false\nwhile (fibM > 1 && !found) {\n  var i = math.min(offset + fibMMm2, n - 1)\n  if (i < 0) i = 0\n  if (nums(i) < extra) {\n    fibM = fibMMm1; fibMMm1 = fibMMm2; fibMMm2 = fibM - fibMMm1; offset = i\n  } else if (nums(i) > extra) {\n    fibM = fibMMm2; fibMMm1 -= fibMMm2; fibMMm2 = fibM - fibMMm1\n  } else {\n    result = i.toLong; found = true\n  }\n}\nif (!found && fibMMm1 == 1 && offset + 1 < n && nums(offset + 1) == extra) result = (offset + 1).toLong"),
    "r": ("n <- length(nums)\nresult <- -1\nfibMMm2 <- 0; fibMMm1 <- 1; fibM <- fibMMm2 + fibMMm1\nwhile (fibM < n) { fibMMm2 <- fibMMm1; fibMMm1 <- fibM; fibM <- fibMMm2 + fibMMm1 }\noffset <- -1\nfound <- FALSE\nwhile (fibM > 1 && !found) {\n  i <- min(offset + fibMMm2, n - 1)\n  if (i < 0) i <- 0\n  if (nums[i + 1] < extra) {\n    fibM <- fibMMm1; fibMMm1 <- fibMMm2; fibMMm2 <- fibM - fibMMm1; offset <- i\n  } else if (nums[i + 1] > extra) {\n    fibM <- fibMMm2; fibMMm1 <- fibMMm1 - fibMMm2; fibMMm2 <- fibM - fibMMm1\n  } else {\n    result <- i; found <- TRUE\n  }\n}\nif (!found && fibMMm1 == 1 && offset + 1 < n && nums[offset + 2] == extra) result <- offset + 1"),
    "javascript": ("const n = nums.length;\nlet result = -1;\nlet fibMMm2 = 0, fibMMm1 = 1, fibM = fibMMm2 + fibMMm1;\nwhile (fibM < n) { fibMMm2 = fibMMm1; fibMMm1 = fibM; fibM = fibMMm2 + fibMMm1; }\nlet offset = -1;\nwhile (fibM > 1) {\n  let i = Math.min(offset + fibMMm2, n - 1);\n  if (i < 0) i = 0;\n  if (nums[i] < extra) { fibM = fibMMm1; fibMMm1 = fibMMm2; fibMMm2 = fibM - fibMMm1; offset = i; }\n  else if (nums[i] > extra) { fibM = fibMMm2; fibMMm1 = fibMMm1 - fibMMm2; fibMMm2 = fibM - fibMMm1; }\n  else { result = i; break; }\n}\nif (result === -1 && fibMMm1 === 1 && offset + 1 < n && nums[offset + 1] === extra) result = offset + 1;"),
    "typescript": ("const n = nums.length;\nlet result = -1;\nlet fibMMm2 = 0, fibMMm1 = 1, fibM = fibMMm2 + fibMMm1;\nwhile (fibM < n) { fibMMm2 = fibMMm1; fibMMm1 = fibM; fibM = fibMMm2 + fibMMm1; }\nlet offset = -1;\nwhile (fibM > 1) {\n  let i = Math.min(offset + fibMMm2, n - 1);\n  if (i < 0) i = 0;\n  if (nums[i] < extra) { fibM = fibMMm1; fibMMm1 = fibMMm2; fibMMm2 = fibM - fibMMm1; offset = i; }\n  else if (nums[i] > extra) { fibM = fibMMm2; fibMMm1 = fibMMm1 - fibMMm2; fibMMm2 = fibM - fibMMm1; }\n  else { result = i; break; }\n}\nif (result === -1 && fibMMm1 === 1 && offset + 1 < n && nums[offset + 1] === extra) result = offset + 1;"),
    "perl": ("my $n = scalar(@{$nums});\nmy $result = -1;\nmy $fibMMm2 = 0; my $fibMMm1 = 1; my $fibM = $fibMMm2 + $fibMMm1;\nwhile ($fibM < $n) { $fibMMm2 = $fibMMm1; $fibMMm1 = $fibM; $fibM = $fibMMm2 + $fibMMm1; }\nmy $offset = -1;\nwhile ($fibM > 1) {\n  my $i = $offset + $fibMMm2 < $n - 1 ? $offset + $fibMMm2 : $n - 1;\n  $i = 0 if $i < 0;\n  if ($nums->[$i] < $extra) { $fibM = $fibMMm1; $fibMMm1 = $fibMMm2; $fibMMm2 = $fibM - $fibMMm1; $offset = $i; }\n  elsif ($nums->[$i] > $extra) { $fibM = $fibMMm2; $fibMMm1 = $fibMMm1 - $fibMMm2; $fibMMm2 = $fibM - $fibMMm1; }\n  else { $result = $i; last; }\n}\nif ($result == -1 && $fibMMm1 == 1 && $offset + 1 < $n && $nums->[$offset + 1] == $extra) { $result = $offset + 1; }"),
    "java": ("int n = nums.length;\nint result = -1;\nint fibMMm2 = 0, fibMMm1 = 1, fibM = fibMMm2 + fibMMm1;\nwhile (fibM < n) { fibMMm2 = fibMMm1; fibMMm1 = fibM; fibM = fibMMm2 + fibMMm1; }\nint offset = -1;\nwhile (fibM > 1) {\n    int i = Math.min(offset + fibMMm2, n - 1);\n    if (i < 0) i = 0;\n    if (nums[i] < extra) { fibM = fibMMm1; fibMMm1 = fibMMm2; fibMMm2 = fibM - fibMMm1; offset = i; }\n    else if (nums[i] > extra) { fibM = fibMMm2; fibMMm1 -= fibMMm2; fibMMm2 = fibM - fibMMm1; }\n    else { result = i; break; }\n}\nif (result == -1 && fibMMm1 == 1 && offset + 1 < n && nums[offset + 1] == extra) result = offset + 1;"),
    "cpp": ("int n = (int) nums.size();\nint result = -1;\nint fibMMm2 = 0, fibMMm1 = 1, fibM = fibMMm2 + fibMMm1;\nwhile (fibM < n) { fibMMm2 = fibMMm1; fibMMm1 = fibM; fibM = fibMMm2 + fibMMm1; }\nint offset = -1;\nwhile (fibM > 1) {\n    int i = std::min(offset + fibMMm2, n - 1);\n    if (i < 0) i = 0;\n    if (nums[i] < extra) { fibM = fibMMm1; fibMMm1 = fibMMm2; fibMMm2 = fibM - fibMMm1; offset = i; }\n    else if (nums[i] > extra) { fibM = fibMMm2; fibMMm1 -= fibMMm2; fibMMm2 = fibM - fibMMm1; }\n    else { result = i; break; }\n}\nif (result == -1 && fibMMm1 == 1 && offset + 1 < n && nums[offset + 1] == extra) result = offset + 1;"),
    "csharp": ("int n = nums.Length;\nint result = -1;\nint fibMMm2 = 0, fibMMm1 = 1, fibM = fibMMm2 + fibMMm1;\nwhile (fibM < n) { fibMMm2 = fibMMm1; fibMMm1 = fibM; fibM = fibMMm2 + fibMMm1; }\nint offset = -1;\nwhile (fibM > 1) {\n    int i = System.Math.Min(offset + fibMMm2, n - 1);\n    if (i < 0) i = 0;\n    if (nums[i] < extra) { fibM = fibMMm1; fibMMm1 = fibMMm2; fibMMm2 = fibM - fibMMm1; offset = i; }\n    else if (nums[i] > extra) { fibM = fibMMm2; fibMMm1 -= fibMMm2; fibMMm2 = fibM - fibMMm1; }\n    else { result = i; break; }\n}\nif (result == -1 && fibMMm1 == 1 && offset + 1 < n && nums[offset + 1] == extra) result = offset + 1;"),
    "c": ("int result = -1;\nint fibMMm2 = 0, fibMMm1 = 1, fibM = fibMMm2 + fibMMm1;\nwhile (fibM < n) { fibMMm2 = fibMMm1; fibMMm1 = fibM; fibM = fibMMm2 + fibMMm1; }\nint offset = -1;\nwhile (fibM > 1) {\n    int i = (offset + fibMMm2 < n - 1) ? (offset + fibMMm2) : (n - 1);\n    if (i < 0) i = 0;\n    if (nums[i] < extra) { fibM = fibMMm1; fibMMm1 = fibMMm2; fibMMm2 = fibM - fibMMm1; offset = i; }\n    else if (nums[i] > extra) { fibM = fibMMm2; fibMMm1 -= fibMMm2; fibMMm2 = fibM - fibMMm1; }\n    else { result = i; break; }\n}\nif (result == -1 && fibMMm1 == 1 && offset + 1 < n && nums[offset + 1] == extra) result = offset + 1;"),
    "rust": ("let n = nums.len() as i32;\nlet mut result: i32 = -1;\nlet mut fib_mm2: i32 = 0;\nlet mut fib_mm1: i32 = 1;\nlet mut fib_m = fib_mm2 + fib_mm1;\nwhile fib_m < n { fib_mm2 = fib_mm1; fib_mm1 = fib_m; fib_m = fib_mm2 + fib_mm1; }\nlet mut offset: i32 = -1;\nwhile fib_m > 1 {\n    let mut i = std::cmp::min(offset + fib_mm2, n - 1);\n    if i < 0 { i = 0; }\n    if nums[i as usize] < extra { fib_m = fib_mm1; fib_mm1 = fib_mm2; fib_mm2 = fib_m - fib_mm1; offset = i; }\n    else if nums[i as usize] > extra { fib_m = fib_mm2; fib_mm1 -= fib_mm2; fib_mm2 = fib_m - fib_mm1; }\n    else { result = i; break; }\n}\nif result == -1 && fib_mm1 == 1 && offset + 1 < n && nums[(offset + 1) as usize] == extra { result = offset + 1; }"),
    "swift": ("let n = nums.count\nvar result = -1\nvar fibMMm2 = 0\nvar fibMMm1 = 1\nvar fibM = fibMMm2 + fibMMm1\nwhile fibM < n { fibMMm2 = fibMMm1; fibMMm1 = fibM; fibM = fibMMm2 + fibMMm1 }\nvar offset = -1\nwhile fibM > 1 {\n    var i = min(offset + fibMMm2, n - 1)\n    if i < 0 { i = 0 }\n    if nums[i] < extra { fibM = fibMMm1; fibMMm1 = fibMMm2; fibMMm2 = fibM - fibMMm1; offset = i }\n    else if nums[i] > extra { fibM = fibMMm2; fibMMm1 -= fibMMm2; fibMMm2 = fibM - fibMMm1 }\n    else { result = i; break }\n}\nif result == -1 && fibMMm1 == 1 && offset + 1 < n && nums[offset + 1] == extra { result = offset + 1 }"),
})

# ═════════════════════════════════════════════════════════════════════════
# ternary_search(nums, extra) -> divide sorted range into 3 parts each step
# ═════════════════════════════════════════════════════════════════════════
add("ternary-search", "arr1_int", "ternary_search", "int", {
    "go": ("lo, hi := 0, len(nums)-1\nresult := int64(-1)\nfor lo <= hi {\n\tthird := (hi - lo) / 3\n\tm1 := lo + third\n\tm2 := hi - third\n\tif nums[m1] == extra { result = int64(m1); break }\n\tif nums[m2] == extra { result = int64(m2); break }\n\tif extra < nums[m1] {\n\t\thi = m1 - 1\n\t} else if extra > nums[m2] {\n\t\tlo = m2 + 1\n\t} else {\n\t\tlo = m1 + 1\n\t\thi = m2 - 1\n\t}\n}"),
    "ruby": ("lo = 0\nhi = nums.length - 1\nresult = -1\nwhile lo <= hi\n  third = (hi - lo) / 3\n  m1 = lo + third\n  m2 = hi - third\n  if nums[m1] == extra\n    result = m1\n    break\n  elsif nums[m2] == extra\n    result = m2\n    break\n  elsif extra < nums[m1]\n    hi = m1 - 1\n  elsif extra > nums[m2]\n    lo = m2 + 1\n  else\n    lo = m1 + 1\n    hi = m2 - 1\n  end\nend"),
    "kotlin": ("var lo = 0\nvar hi = nums.size - 1\nvar result = -1L\nwhile (lo <= hi) {\n    val third = (hi - lo) / 3\n    val m1 = lo + third\n    val m2 = hi - third\n    if (nums[m1] == extra) { result = m1.toLong(); break }\n    if (nums[m2] == extra) { result = m2.toLong(); break }\n    if (extra < nums[m1]) hi = m1 - 1\n    else if (extra > nums[m2]) lo = m2 + 1\n    else { lo = m1 + 1; hi = m2 - 1 }\n}"),
    "php": ("$lo = 0; $hi = count($nums) - 1; $result = -1;\nwhile ($lo <= $hi) {\n    $third = intdiv($hi - $lo, 3);\n    $m1 = $lo + $third;\n    $m2 = $hi - $third;\n    if ($nums[$m1] == $extra) { $result = $m1; break; }\n    if ($nums[$m2] == $extra) { $result = $m2; break; }\n    if ($extra < $nums[$m1]) { $hi = $m1 - 1; }\n    elseif ($extra > $nums[$m2]) { $lo = $m2 + 1; }\n    else { $lo = $m1 + 1; $hi = $m2 - 1; }\n}"),
    "scala": ("var lo = 0\nvar hi = nums.length - 1\nvar result: Long = -1L\nvar found = false\nwhile (lo <= hi && !found) {\n  val third = (hi - lo) / 3\n  val m1 = lo + third\n  val m2 = hi - third\n  if (nums(m1) == extra) { result = m1.toLong; found = true }\n  else if (nums(m2) == extra) { result = m2.toLong; found = true }\n  else if (extra < nums(m1)) hi = m1 - 1\n  else if (extra > nums(m2)) lo = m2 + 1\n  else { lo = m1 + 1; hi = m2 - 1 }\n}"),
    "r": ("lo <- 1; hi <- length(nums); result <- -1\nwhile (lo <= hi) {\n  third <- (hi - lo) %/% 3\n  m1 <- lo + third\n  m2 <- hi - third\n  if (nums[m1] == extra) { result <- m1 - 1; break }\n  else if (nums[m2] == extra) { result <- m2 - 1; break }\n  else if (extra < nums[m1]) { hi <- m1 - 1 }\n  else if (extra > nums[m2]) { lo <- m2 + 1 }\n  else { lo <- m1 + 1; hi <- m2 - 1 }\n}"),
    "javascript": ("let lo = 0, hi = nums.length - 1;\nlet result = -1;\nwhile (lo <= hi) {\n  const third = Math.floor((hi - lo) / 3);\n  const m1 = lo + third, m2 = hi - third;\n  if (nums[m1] === extra) { result = m1; break; }\n  if (nums[m2] === extra) { result = m2; break; }\n  if (extra < nums[m1]) hi = m1 - 1;\n  else if (extra > nums[m2]) lo = m2 + 1;\n  else { lo = m1 + 1; hi = m2 - 1; }\n}"),
    "typescript": ("let lo = 0, hi = nums.length - 1;\nlet result = -1;\nwhile (lo <= hi) {\n  const third = Math.floor((hi - lo) / 3);\n  const m1 = lo + third, m2 = hi - third;\n  if (nums[m1] === extra) { result = m1; break; }\n  if (nums[m2] === extra) { result = m2; break; }\n  if (extra < nums[m1]) hi = m1 - 1;\n  else if (extra > nums[m2]) lo = m2 + 1;\n  else { lo = m1 + 1; hi = m2 - 1; }\n}"),
    "perl": ("my $lo = 0; my $hi = scalar(@{$nums}) - 1; my $result = -1;\nwhile ($lo <= $hi) {\n  my $third = int(($hi - $lo) / 3);\n  my $m1 = $lo + $third; my $m2 = $hi - $third;\n  if ($nums->[$m1] == $extra) { $result = $m1; last; }\n  if ($nums->[$m2] == $extra) { $result = $m2; last; }\n  if ($extra < $nums->[$m1]) { $hi = $m1 - 1; }\n  elsif ($extra > $nums->[$m2]) { $lo = $m2 + 1; }\n  else { $lo = $m1 + 1; $hi = $m2 - 1; }\n}"),
    "java": ("int lo = 0, hi = nums.length - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int third = (hi - lo) / 3;\n    int m1 = lo + third, m2 = hi - third;\n    if (nums[m1] == extra) { result = m1; break; }\n    if (nums[m2] == extra) { result = m2; break; }\n    if (extra < nums[m1]) hi = m1 - 1;\n    else if (extra > nums[m2]) lo = m2 + 1;\n    else { lo = m1 + 1; hi = m2 - 1; }\n}"),
    "cpp": ("int lo = 0, hi = (int) nums.size() - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int third = (hi - lo) / 3;\n    int m1 = lo + third, m2 = hi - third;\n    if (nums[m1] == extra) { result = m1; break; }\n    if (nums[m2] == extra) { result = m2; break; }\n    if (extra < nums[m1]) hi = m1 - 1;\n    else if (extra > nums[m2]) lo = m2 + 1;\n    else { lo = m1 + 1; hi = m2 - 1; }\n}"),
    "csharp": ("int lo = 0, hi = nums.Length - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int third = (hi - lo) / 3;\n    int m1 = lo + third, m2 = hi - third;\n    if (nums[m1] == extra) { result = m1; break; }\n    if (nums[m2] == extra) { result = m2; break; }\n    if (extra < nums[m1]) hi = m1 - 1;\n    else if (extra > nums[m2]) lo = m2 + 1;\n    else { lo = m1 + 1; hi = m2 - 1; }\n}"),
    "c": ("int lo = 0, hi = n - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int third = (hi - lo) / 3;\n    int m1 = lo + third, m2 = hi - third;\n    if (nums[m1] == extra) { result = m1; break; }\n    if (nums[m2] == extra) { result = m2; break; }\n    if (extra < nums[m1]) hi = m1 - 1;\n    else if (extra > nums[m2]) lo = m2 + 1;\n    else { lo = m1 + 1; hi = m2 - 1; }\n}"),
    "rust": ("let mut lo: i32 = 0;\nlet mut hi: i32 = nums.len() as i32 - 1;\nlet mut result: i32 = -1;\nwhile lo <= hi {\n    let third = (hi - lo) / 3;\n    let m1 = lo + third;\n    let m2 = hi - third;\n    if nums[m1 as usize] == extra { result = m1; break; }\n    if nums[m2 as usize] == extra { result = m2; break; }\n    if extra < nums[m1 as usize] { hi = m1 - 1; }\n    else if extra > nums[m2 as usize] { lo = m2 + 1; }\n    else { lo = m1 + 1; hi = m2 - 1; }\n}"),
    "swift": ("var lo = 0\nvar hi = nums.count - 1\nvar result = -1\nwhile lo <= hi {\n    let third = (hi - lo) / 3\n    let m1 = lo + third, m2 = hi - third\n    if nums[m1] == extra { result = m1; break }\n    if nums[m2] == extra { result = m2; break }\n    if extra < nums[m1] { hi = m1 - 1 }\n    else if extra > nums[m2] { lo = m2 + 1 }\n    else { lo = m1 + 1; hi = m2 - 1 }\n}"),
})

# ═════════════════════════════════════════════════════════════════════════
# search(nums, extra) -> index of extra in a ROTATED sorted array, or -1
# ═════════════════════════════════════════════════════════════════════════
add("rotated-binary-search", "arr1_int", "search", "int", {
    "go": ("lo, hi := 0, len(nums)-1\nresult := int64(-1)\nfor lo <= hi {\n\tmid := (lo + hi) / 2\n\tif nums[mid] == extra { result = int64(mid); break }\n\tif nums[lo] <= nums[mid] {\n\t\tif nums[lo] <= extra && extra < nums[mid] { hi = mid - 1 } else { lo = mid + 1 }\n\t} else {\n\t\tif nums[mid] < extra && extra <= nums[hi] { lo = mid + 1 } else { hi = mid - 1 }\n\t}\n}"),
    "ruby": ("lo = 0\nhi = nums.length - 1\nresult = -1\nwhile lo <= hi\n  mid = (lo + hi) / 2\n  if nums[mid] == extra\n    result = mid\n    break\n  end\n  if nums[lo] <= nums[mid]\n    if nums[lo] <= extra && extra < nums[mid]\n      hi = mid - 1\n    else\n      lo = mid + 1\n    end\n  else\n    if nums[mid] < extra && extra <= nums[hi]\n      lo = mid + 1\n    else\n      hi = mid - 1\n    end\n  end\nend"),
    "kotlin": ("var lo = 0\nvar hi = nums.size - 1\nvar result = -1L\nwhile (lo <= hi) {\n    val mid = (lo + hi) / 2\n    if (nums[mid] == extra) { result = mid.toLong(); break }\n    if (nums[lo] <= nums[mid]) {\n        if (nums[lo] <= extra && extra < nums[mid]) hi = mid - 1 else lo = mid + 1\n    } else {\n        if (nums[mid] < extra && extra <= nums[hi]) lo = mid + 1 else hi = mid - 1\n    }\n}"),
    "php": ("$lo = 0; $hi = count($nums) - 1; $result = -1;\nwhile ($lo <= $hi) {\n    $mid = intdiv($lo + $hi, 2);\n    if ($nums[$mid] == $extra) { $result = $mid; break; }\n    if ($nums[$lo] <= $nums[$mid]) {\n        if ($nums[$lo] <= $extra && $extra < $nums[$mid]) { $hi = $mid - 1; } else { $lo = $mid + 1; }\n    } else {\n        if ($nums[$mid] < $extra && $extra <= $nums[$hi]) { $lo = $mid + 1; } else { $hi = $mid - 1; }\n    }\n}"),
    "scala": ("var lo = 0\nvar hi = nums.length - 1\nvar result: Long = -1L\nvar found = false\nwhile (lo <= hi && !found) {\n  val mid = (lo + hi) / 2\n  if (nums(mid) == extra) { result = mid.toLong; found = true }\n  else if (nums(lo) <= nums(mid)) {\n    if (nums(lo) <= extra && extra < nums(mid)) hi = mid - 1 else lo = mid + 1\n  } else {\n    if (nums(mid) < extra && extra <= nums(hi)) lo = mid + 1 else hi = mid - 1\n  }\n}"),
    "r": ("lo <- 1; hi <- length(nums); result <- -1\nwhile (lo <= hi) {\n  mid <- (lo + hi) %/% 2\n  if (nums[mid] == extra) { result <- mid - 1; break }\n  if (nums[lo] <= nums[mid]) {\n    if (nums[lo] <= extra && extra < nums[mid]) { hi <- mid - 1 } else { lo <- mid + 1 }\n  } else {\n    if (nums[mid] < extra && extra <= nums[hi]) { lo <- mid + 1 } else { hi <- mid - 1 }\n  }\n}"),
    "javascript": ("let lo = 0, hi = nums.length - 1;\nlet result = -1;\nwhile (lo <= hi) {\n  const mid = (lo + hi) >> 1;\n  if (nums[mid] === extra) { result = mid; break; }\n  if (nums[lo] <= nums[mid]) {\n    if (nums[lo] <= extra && extra < nums[mid]) hi = mid - 1; else lo = mid + 1;\n  } else {\n    if (nums[mid] < extra && extra <= nums[hi]) lo = mid + 1; else hi = mid - 1;\n  }\n}"),
    "typescript": ("let lo = 0, hi = nums.length - 1;\nlet result = -1;\nwhile (lo <= hi) {\n  const mid = (lo + hi) >> 1;\n  if (nums[mid] === extra) { result = mid; break; }\n  if (nums[lo] <= nums[mid]) {\n    if (nums[lo] <= extra && extra < nums[mid]) hi = mid - 1; else lo = mid + 1;\n  } else {\n    if (nums[mid] < extra && extra <= nums[hi]) lo = mid + 1; else hi = mid - 1;\n  }\n}"),
    "perl": ("my $lo = 0; my $hi = scalar(@{$nums}) - 1; my $result = -1;\nwhile ($lo <= $hi) {\n  my $mid = int(($lo + $hi) / 2);\n  if ($nums->[$mid] == $extra) { $result = $mid; last; }\n  if ($nums->[$lo] <= $nums->[$mid]) {\n    if ($nums->[$lo] <= $extra && $extra < $nums->[$mid]) { $hi = $mid - 1; } else { $lo = $mid + 1; }\n  } else {\n    if ($nums->[$mid] < $extra && $extra <= $nums->[$hi]) { $lo = $mid + 1; } else { $hi = $mid - 1; }\n  }\n}"),
    "java": ("int lo = 0, hi = nums.length - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] == extra) { result = mid; break; }\n    if (nums[lo] <= nums[mid]) {\n        if (nums[lo] <= extra && extra < nums[mid]) hi = mid - 1; else lo = mid + 1;\n    } else {\n        if (nums[mid] < extra && extra <= nums[hi]) lo = mid + 1; else hi = mid - 1;\n    }\n}"),
    "cpp": ("int lo = 0, hi = (int) nums.size() - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] == extra) { result = mid; break; }\n    if (nums[lo] <= nums[mid]) {\n        if (nums[lo] <= extra && extra < nums[mid]) hi = mid - 1; else lo = mid + 1;\n    } else {\n        if (nums[mid] < extra && extra <= nums[hi]) lo = mid + 1; else hi = mid - 1;\n    }\n}"),
    "csharp": ("int lo = 0, hi = nums.Length - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] == extra) { result = mid; break; }\n    if (nums[lo] <= nums[mid]) {\n        if (nums[lo] <= extra && extra < nums[mid]) hi = mid - 1; else lo = mid + 1;\n    } else {\n        if (nums[mid] < extra && extra <= nums[hi]) lo = mid + 1; else hi = mid - 1;\n    }\n}"),
    "c": ("int lo = 0, hi = n - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] == extra) { result = mid; break; }\n    if (nums[lo] <= nums[mid]) {\n        if (nums[lo] <= extra && extra < nums[mid]) hi = mid - 1; else lo = mid + 1;\n    } else {\n        if (nums[mid] < extra && extra <= nums[hi]) lo = mid + 1; else hi = mid - 1;\n    }\n}"),
    "rust": ("let mut lo: i32 = 0;\nlet mut hi: i32 = nums.len() as i32 - 1;\nlet mut result: i32 = -1;\nwhile lo <= hi {\n    let mid = (lo + hi) / 2;\n    if nums[mid as usize] == extra { result = mid; break; }\n    if nums[lo as usize] <= nums[mid as usize] {\n        if nums[lo as usize] <= extra && extra < nums[mid as usize] { hi = mid - 1; } else { lo = mid + 1; }\n    } else {\n        if nums[mid as usize] < extra && extra <= nums[hi as usize] { lo = mid + 1; } else { hi = mid - 1; }\n    }\n}"),
    "swift": ("var lo = 0\nvar hi = nums.count - 1\nvar result = -1\nwhile lo <= hi {\n    let mid = (lo + hi) / 2\n    if nums[mid] == extra { result = mid; break }\n    if nums[lo] <= nums[mid] {\n        if nums[lo] <= extra && extra < nums[mid] { hi = mid - 1 } else { lo = mid + 1 }\n    } else {\n        if nums[mid] < extra && extra <= nums[hi] { lo = mid + 1 } else { hi = mid - 1 }\n    }\n}"),
})

# ═════════════════════════════════════════════════════════════════════════
# first_occurrence(nums, extra) -> leftmost index of extra, or -1
# ═════════════════════════════════════════════════════════════════════════
add("first-occurrence", "arr1_int", "first_occurrence", "int", {
    "go": "lo, hi := 0, len(nums)-1\nresult := int64(-1)\nfor lo <= hi {\n\tmid := (lo + hi) / 2\n\tif nums[mid] == extra { result = int64(mid); hi = mid - 1 } else if nums[mid] < extra { lo = mid + 1 } else { hi = mid - 1 }\n}",
    "ruby": "lo = 0\nhi = nums.length - 1\nresult = -1\nwhile lo <= hi\n  mid = (lo + hi) / 2\n  if nums[mid] == extra\n    result = mid\n    hi = mid - 1\n  elsif nums[mid] < extra\n    lo = mid + 1\n  else\n    hi = mid - 1\n  end\nend",
    "kotlin": "var lo = 0\nvar hi = nums.size - 1\nvar result = -1L\nwhile (lo <= hi) {\n    val mid = (lo + hi) / 2\n    if (nums[mid] == extra) { result = mid.toLong(); hi = mid - 1 }\n    else if (nums[mid] < extra) lo = mid + 1 else hi = mid - 1\n}",
    "php": "$lo = 0; $hi = count($nums) - 1; $result = -1;\nwhile ($lo <= $hi) {\n    $mid = intdiv($lo + $hi, 2);\n    if ($nums[$mid] == $extra) { $result = $mid; $hi = $mid - 1; }\n    elseif ($nums[$mid] < $extra) { $lo = $mid + 1; } else { $hi = $mid - 1; }\n}",
    "scala": "var lo = 0\nvar hi = nums.length - 1\nvar result: Long = -1L\nwhile (lo <= hi) {\n  val mid = (lo + hi) / 2\n  if (nums(mid) == extra) { result = mid.toLong; hi = mid - 1 }\n  else if (nums(mid) < extra) lo = mid + 1\n  else hi = mid - 1\n}",
    "r": "lo <- 1; hi <- length(nums); result <- -1\nwhile (lo <= hi) {\n  mid <- (lo + hi) %/% 2\n  if (nums[mid] == extra) { result <- mid - 1; hi <- mid - 1 }\n  else if (nums[mid] < extra) { lo <- mid + 1 } else { hi <- mid - 1 }\n}",
    "javascript": "let lo = 0, hi = nums.length - 1;\nlet result = -1;\nwhile (lo <= hi) {\n  const mid = (lo + hi) >> 1;\n  if (nums[mid] === extra) { result = mid; hi = mid - 1; }\n  else if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n}",
    "typescript": "let lo = 0, hi = nums.length - 1;\nlet result = -1;\nwhile (lo <= hi) {\n  const mid = (lo + hi) >> 1;\n  if (nums[mid] === extra) { result = mid; hi = mid - 1; }\n  else if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n}",
    "perl": "my $lo = 0; my $hi = scalar(@{$nums}) - 1; my $result = -1;\nwhile ($lo <= $hi) {\n  my $mid = int(($lo + $hi) / 2);\n  if ($nums->[$mid] == $extra) { $result = $mid; $hi = $mid - 1; }\n  elsif ($nums->[$mid] < $extra) { $lo = $mid + 1; } else { $hi = $mid - 1; }\n}",
    "java": "int lo = 0, hi = nums.length - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] == extra) { result = mid; hi = mid - 1; }\n    else if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n}",
    "cpp": "int lo = 0, hi = (int) nums.size() - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] == extra) { result = mid; hi = mid - 1; }\n    else if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n}",
    "csharp": "int lo = 0, hi = nums.Length - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] == extra) { result = mid; hi = mid - 1; }\n    else if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n}",
    "c": "int lo = 0, hi = n - 1;\nint result = -1;\nwhile (lo <= hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] == extra) { result = mid; hi = mid - 1; }\n    else if (nums[mid] < extra) lo = mid + 1; else hi = mid - 1;\n}",
    "rust": "let mut lo: i32 = 0;\nlet mut hi: i32 = nums.len() as i32 - 1;\nlet mut result: i32 = -1;\nwhile lo <= hi {\n    let mid = (lo + hi) / 2;\n    if nums[mid as usize] == extra { result = mid; hi = mid - 1; }\n    else if nums[mid as usize] < extra { lo = mid + 1; } else { hi = mid - 1; }\n}",
    "swift": "var lo = 0\nvar hi = nums.count - 1\nvar result = -1\nwhile lo <= hi {\n    let mid = (lo + hi) / 2\n    if nums[mid] == extra { result = mid; hi = mid - 1 }\n    else if nums[mid] < extra { lo = mid + 1 } else { hi = mid - 1 }\n}",
})

# ═════════════════════════════════════════════════════════════════════════
# search_insert(nums, extra) -> index where extra is / would be inserted
# ═════════════════════════════════════════════════════════════════════════
add("search-insert-position", "arr1_int", "search_insert", "int", {
    "go": "lo, hi := 0, len(nums)\nfor lo < hi {\n\tmid := (lo + hi) / 2\n\tif nums[mid] < extra { lo = mid + 1 } else { hi = mid }\n}\nresult := int64(lo)",
    "ruby": "lo = 0\nhi = nums.length\nwhile lo < hi\n  mid = (lo + hi) / 2\n  if nums[mid] < extra\n    lo = mid + 1\n  else\n    hi = mid\n  end\nend\nresult = lo",
    "kotlin": "var lo = 0\nvar hi = nums.size\nwhile (lo < hi) {\n    val mid = (lo + hi) / 2\n    if (nums[mid] < extra) lo = mid + 1 else hi = mid\n}\nval result = lo.toLong()",
    "php": "$lo = 0; $hi = count($nums);\nwhile ($lo < $hi) {\n    $mid = intdiv($lo + $hi, 2);\n    if ($nums[$mid] < $extra) { $lo = $mid + 1; } else { $hi = $mid; }\n}\n$result = $lo;",
    "scala": "var lo = 0\nvar hi = nums.length\nwhile (lo < hi) {\n  val mid = (lo + hi) / 2\n  if (nums(mid) < extra) lo = mid + 1 else hi = mid\n}\nval result: Long = lo",
    "r": "lo <- 1; hi <- length(nums) + 1\nwhile (lo < hi) {\n  mid <- (lo + hi) %/% 2\n  if (nums[mid] < extra) { lo <- mid + 1 } else { hi <- mid }\n}\nresult <- lo - 1",
    "javascript": "let lo = 0, hi = nums.length;\nwhile (lo < hi) {\n  const mid = (lo + hi) >> 1;\n  if (nums[mid] < extra) lo = mid + 1; else hi = mid;\n}\nconst result = lo;",
    "typescript": "let lo = 0, hi = nums.length;\nwhile (lo < hi) {\n  const mid = (lo + hi) >> 1;\n  if (nums[mid] < extra) lo = mid + 1; else hi = mid;\n}\nconst result = lo;",
    "perl": "my $lo = 0; my $hi = scalar(@{$nums});\nwhile ($lo < $hi) {\n  my $mid = int(($lo + $hi) / 2);\n  if ($nums->[$mid] < $extra) { $lo = $mid + 1; } else { $hi = $mid; }\n}\nmy $result = $lo;",
    "java": "int lo = 0, hi = nums.length;\nwhile (lo < hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] < extra) lo = mid + 1; else hi = mid;\n}\nint result = lo;",
    "cpp": "int lo = 0, hi = (int) nums.size();\nwhile (lo < hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] < extra) lo = mid + 1; else hi = mid;\n}\nint result = lo;",
    "csharp": "int lo = 0, hi = nums.Length;\nwhile (lo < hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] < extra) lo = mid + 1; else hi = mid;\n}\nint result = lo;",
    "c": "int lo = 0, hi = n;\nwhile (lo < hi) {\n    int mid = (lo + hi) / 2;\n    if (nums[mid] < extra) lo = mid + 1; else hi = mid;\n}\nint result = lo;",
    "rust": "let mut lo: i32 = 0;\nlet mut hi: i32 = nums.len() as i32;\nwhile lo < hi {\n    let mid = (lo + hi) / 2;\n    if nums[mid as usize] < extra { lo = mid + 1; } else { hi = mid; }\n}\nlet result: i32 = lo;",
    "swift": "var lo = 0\nvar hi = nums.count\nwhile lo < hi {\n    let mid = (lo + hi) / 2\n    if nums[mid] < extra { lo = mid + 1 } else { hi = mid }\n}\nlet result = lo",
})

# ═════════════════════════════════════════════════════════════════════════
# subarray_sum(nums, extra) -> count of contiguous subarrays summing to
# extra (prefix-sum + hashmap of counts; O(n^2) prefix-diff for C, whose
# corpus tops out around n=5700 -- comfortably fast enough)
# ═════════════════════════════════════════════════════════════════════════
add("subarray-sum-equals-k", "arr1_int", "subarray_sum", "int", {
    "go": ("counts := map[int]int{0: 1}\nsum := 0\nresult := int64(0)\nfor _, v := range nums {\n\tsum += v\n\tif c, ok := counts[sum-extra]; ok { result += int64(c) }\n\tcounts[sum]++\n}"),
    "ruby": "counts = Hash.new(0)\ncounts[0] = 1\nsum = 0\nresult = 0\nnums.each do |v|\n  sum += v\n  result += counts[sum - extra]\n  counts[sum] += 1\nend",
    "kotlin": "val counts = HashMap<Int, Int>()\ncounts[0] = 1\nvar sum = 0\nvar result = 0L\nfor (v in nums) {\n    sum += v\n    result += (counts[sum - extra] ?: 0)\n    counts[sum] = (counts[sum] ?: 0) + 1\n}",
    "php": "$counts = [0 => 1];\n$sum = 0;\n$result = 0;\nforeach ($nums as $v) {\n    $sum += $v;\n    $result += ($counts[$sum - $extra] ?? 0);\n    $counts[$sum] = ($counts[$sum] ?? 0) + 1;\n}",
    "scala": "val counts = scala.collection.mutable.HashMap[Int, Int](0 -> 1).withDefaultValue(0)\nvar sum = 0\nvar result: Long = 0L\nfor (v <- nums) {\n  sum += v\n  result += counts(sum - extra)\n  counts(sum) += 1\n}",
    "r": "counts <- new.env()\nassign('0', 1, envir = counts)\nsum <- 0\nresult <- 0\nfor (v in nums) {\n  sum <- sum + v\n  key <- as.character(sum - extra)\n  if (exists(key, envir = counts)) { result <- result + get(key, envir = counts) }\n  skey <- as.character(sum)\n  if (exists(skey, envir = counts)) { assign(skey, get(skey, envir = counts) + 1, envir = counts) } else { assign(skey, 1, envir = counts) }\n}",
    "javascript": "const counts = new Map();\ncounts.set(0, 1);\nlet sum = 0;\nlet result = 0;\nfor (const v of nums) {\n  sum += v;\n  result += (counts.get(sum - extra) || 0);\n  counts.set(sum, (counts.get(sum) || 0) + 1);\n}",
    "typescript": "const counts = new Map<number, number>();\ncounts.set(0, 1);\nlet sum = 0;\nlet result = 0;\nfor (const v of nums) {\n  sum += v;\n  result += (counts.get(sum - extra) || 0);\n  counts.set(sum, (counts.get(sum) || 0) + 1);\n}",
    "perl": "my %counts = (0 => 1);\nmy $sum = 0;\nmy $result = 0;\nforeach my $v (@{$nums}) {\n  $sum += $v;\n  $result += ($counts{$sum - $extra} // 0);\n  $counts{$sum} = ($counts{$sum} // 0) + 1;\n}",
    "java": "java.util.Map<Integer, Integer> counts = new java.util.HashMap<>();\ncounts.put(0, 1);\nint sum = 0;\nint result = 0;\nfor (int v : nums) {\n    sum += v;\n    result += counts.getOrDefault(sum - extra, 0);\n    counts.merge(sum, 1, Integer::sum);\n}",
    "cpp": "std::unordered_map<int, int> counts;\ncounts[0] = 1;\nint sum = 0;\nint result = 0;\nfor (int v : nums) {\n    sum += v;\n    auto it = counts.find(sum - extra);\n    if (it != counts.end()) result += it->second;\n    counts[sum]++;\n}",
    "csharp": "var counts = new System.Collections.Generic.Dictionary<int, int>();\ncounts[0] = 1;\nint sum = 0;\nint result = 0;\nforeach (var v in nums) {\n    sum += v;\n    if (counts.ContainsKey(sum - extra)) result += counts[sum - extra];\n    counts[sum] = counts.ContainsKey(sum) ? counts[sum] + 1 : 1;\n}",
    "c": "int result = 0;\nint *prefix = (int *)malloc(sizeof(int) * (size_t)(n + 1));\nprefix[0] = 0;\nfor (int i = 0; i < n; i++) prefix[i+1] = prefix[i] + nums[i];\nfor (int i = 0; i < n; i++) {\n    for (int j = i + 1; j <= n; j++) {\n        if (prefix[j] - prefix[i] == extra) result++;\n    }\n}\nfree(prefix);",
    "rust": "let mut counts = std::collections::HashMap::new();\ncounts.insert(0, 1);\nlet mut sum = 0;\nlet mut result = 0;\nfor v in nums.iter() {\n    sum += v;\n    result += counts.get(&(sum - extra)).copied().unwrap_or(0);\n    *counts.entry(sum).or_insert(0) += 1;\n}",
    "swift": "var counts: [Int: Int] = [0: 1]\nvar sum = 0\nvar result = 0\nfor v in nums {\n    sum += v\n    result += counts[sum - extra, default: 0]\n    counts[sum, default: 0] += 1\n}",
})


if __name__ == "__main__":
    sys.exit(asyncio.run(sh.main()))
