"""
Coverage manifest — one status record per CANONICAL algorithm (all 250, not
just the ones mapped to a problem). This is the audit artifact required
before claiming any coverage number: it must always sum back to the exact
canonical algorithm count discovered by discovery.py.

Status values:
  CURATED             — hand-authored problem, statement + tests written by a human
  GENERATED_STANDARD   — problem generated by a family factory, exact-match judge
  GENERATED_STRUCTURED — reserved for future structured (tree/graph-serialization) judges
  PROPERTY_JUDGE       — multiple outputs can be correct; needs a property validator (not yet built)
  INTERACTIVE_ONLY     — better suited to the existing visualization than a coding judge
  BENCHMARK_ONLY       — stochastic/approximate output; only benchmarking makes sense
  NEEDS_REVIEW         — plausible future STANDARD/STRUCTURED candidate, factory not yet implemented
  UNSUPPORTED          — no reasonable judge contract identified
"""
from __future__ import annotations

from dataclasses import dataclass

from .discovery import CanonicalAlgorithm

# Categories whose *nature* makes exact-match/property judging a poor fit today.
_BENCHMARK_ONLY_CATEGORIES = {"machine-learning", "optimization", "probability", "randomized"}
_INTERACTIVE_ONLY_CATEGORIES = {"cellular-automata", "distributed-systems"}
# Categories where multiple outputs can be valid → need a property validator we haven't built yet.
_PROPERTY_JUDGE_CATEGORIES = {"graph", "backtracking", "tree", "computational-geometry"}
# Categories that are plausible STANDARD_JUDGE/STRUCTURED_JUDGE candidates for future batches.
_NEEDS_REVIEW_CATEGORIES = {
    "dynamic-programming", "greedy", "number-theory", "string",
    "divide-and-conquer", "cryptography", "data-structures",
}


@dataclass(frozen=True)
class CoverageEntry:
    algorithm_slug: str
    category: str
    atlascode_problem_slug: str | None
    judge_type: str
    family: str
    comparator: str | None
    oracle: str | None
    starter_template_strategy: str | None
    status: str
    reason: str | None

    def to_dict(self) -> dict:
        return {
            "algorithm_slug": self.algorithm_slug,
            "category": self.category,
            "atlascode_problem_slug": self.atlascode_problem_slug,
            "judge_type": self.judge_type,
            "family": self.family,
            "comparator": self.comparator,
            "oracle": self.oracle,
            "starter_template_strategy": self.starter_template_strategy,
            "status": self.status,
            "reason": self.reason,
        }


def _default_status_for_category(category: str) -> tuple[str, str]:
    """(status, reason) for an algorithm not curated or generated this batch."""
    if category in _BENCHMARK_ONLY_CATEGORIES:
        return "BENCHMARK_ONLY", f"'{category}' algorithms produce stochastic/approximate output, not exact-match-judgeable."
    if category in _INTERACTIVE_ONLY_CATEGORIES:
        return "INTERACTIVE_ONLY", f"'{category}' algorithms are simulation/visualization-oriented; no natural coding-challenge contract."
    if category in _PROPERTY_JUDGE_CATEGORIES:
        return "PROPERTY_JUDGE", f"'{category}' problems often have multiple valid outputs; needs a property validator (not yet implemented)."
    if category in _NEEDS_REVIEW_CATEGORIES:
        return "NEEDS_REVIEW", f"Plausible STANDARD_JUDGE/STRUCTURED_JUDGE candidate in '{category}'; family factory not yet implemented."
    return "NEEDS_REVIEW", f"Uncategorized family '{category}'; needs manual review."


def build_coverage_manifest(
    canonical: list[CanonicalAlgorithm],
    curated_slugs: dict[str, str],      # algorithm_slug -> problem_id (NOT always equal — e.g. "kmp" -> "kmp-string-matching")
    generated_slugs: dict[str, tuple[str, str]],  # algorithm_slug -> (family name, problem_id)
    skipped: dict[str, str],           # slug -> skip reason, for algorithms a factory looked at but declined
) -> list[CoverageEntry]:
    entries: list[CoverageEntry] = []

    for algo in canonical:
        if algo.slug in curated_slugs:
            entries.append(CoverageEntry(
                algorithm_slug=algo.slug,
                category=algo.category,
                atlascode_problem_slug=curated_slugs[algo.slug],
                judge_type="STANDARD_JUDGE",
                family="curated",
                comparator="exact_trimmed",
                oracle="hand_written_reference_solution",
                starter_template_strategy="stdin_stdout_wrapper",
                status="CURATED",
                reason=None,
            ))
        elif algo.slug in generated_slugs:
            # sorting/searching: plugin terminal state IS the oracle, but it's
            # self-verifying (an invariant check — sorted(input)==output, or
            # found_at actually points at target — runs before shipping, see
            # oracle.py). number-theory (and any future family built the same
            # way): a plugin-free independent_oracles.py function is the sole
            # source of truth — see that module's docstring for why plugin
            # terminal state was rejected as an oracle for this family.
            _family, _problem_id = generated_slugs[algo.slug]
            _oracle_kind = (
                "plugin_steps_terminal_state_with_invariant_check"
                if _family in ("sorting", "searching")
                else "independent_oracle"
            )
            entries.append(CoverageEntry(
                algorithm_slug=algo.slug,
                category=algo.category,
                atlascode_problem_slug=_problem_id,
                judge_type="STANDARD_JUDGE",
                family=_family,
                comparator="exact_trimmed",
                oracle=_oracle_kind,
                starter_template_strategy="stdin_stdout_wrapper",
                status="GENERATED_STANDARD",
                reason=None,
            ))
        elif algo.slug in skipped:
            entries.append(CoverageEntry(
                algorithm_slug=algo.slug,
                category=algo.category,
                atlascode_problem_slug=None,
                judge_type="STANDARD_JUDGE",
                family=algo.category,
                comparator=None,
                oracle=None,
                starter_template_strategy=None,
                status="NEEDS_REVIEW",
                reason=f"Family factory attempted but declined: {skipped[algo.slug]}",
            ))
        else:
            status, reason = _default_status_for_category(algo.category)
            entries.append(CoverageEntry(
                algorithm_slug=algo.slug,
                category=algo.category,
                atlascode_problem_slug=None,
                judge_type=status if status in ("PROPERTY_JUDGE", "BENCHMARK_ONLY", "INTERACTIVE_ONLY") else "STANDARD_JUDGE",
                family=algo.category,
                comparator=None,
                oracle=None,
                starter_template_strategy=None,
                status=status,
                reason=reason,
            ))

    return entries


def summarize(entries: list[CoverageEntry]) -> dict[str, int]:
    summary: dict[str, int] = {}
    for e in entries:
        summary[e.status] = summary.get(e.status, 0) + 1
    return summary
